### ISSUE TITLE
Issue: chinese characters present in the index.js file of the pro-table/src/Form/index.tsx

### ISSUE THREAD

**Issue by AKedar21** [ant-design/pro-table#10]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/pro-table/blame/master/src/Form/index.tsx](https://github.com/ant-design/pro-table/blame/master/src/Form/index.tsx)

### Steps to reproduce
https://github.com/ant-design/pro-table/blame/master/src/Form/index.tsx
Check the content of this file

### What is expected?
It should be in english

### What is actually happening?
It is in Chinese

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | react |
| System | i5 |
| Browser | chrome latest |

**Comment by chenshuai2144** [comment]
Before joining internationalization, I will only support Chinese
You can wait for a while

**Comment by AKedar21** [comment]
> Before joining internationalization, I will only support Chinese
> You can wait for a while

Could you please provide some estimation when it will be available.
And thanks for your quick reply.

**Comment by chenshuai2144** [comment]
@AKedar21 
About a month

**Comment by beyoursun** [comment]
@chenshuai2144 I would like to help with this.

About the [placeholder](https://github.com/ant-design/pro-table/blob/master/src/Form/index.tsx#L34)，we can pass the props from columns to override it. And about [buttons & collapse](https://github.com/ant-design/pro-table/blob/master/src/Form/index.tsx#L204-L231), we add some new props to configure it, such as `searchText`, `resetText`.

What do you think?

**Comment by chenshuai2144** [comment]
```
search:{
  searchText:string
  resetText:string
  collapseRender:( collapsed)=> React.Node
}
```
How is this?
