### ISSUE TITLE
🐛[BUG] component/alert/index.tsx 中有未国际化资源

### ISSUE THREAD

**Issue by zhengcan** [ant-design/pro-table#100]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
https://github.com/ant-design/pro-table/blob/master/src/component/alert/index.tsx 中有未国际化资源

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
n/a

### 🏞 期望结果 [描述你原本期望看到的结果]
进行完整的国际化

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
n/a

### © 版本信息
master

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
n/a

**Comment by chenshuai2144** [comment]
@zhengcan  你可以通过 alertIInfoRender  自定一的

**Comment by effapp** [comment]
请问可以把tableAlert中的清空按钮去掉吗？

**Comment by chenshuai2144** [comment]
我加一下
