### ISSUE TITLE
🧐国家化语言为什么没有作用？

### ISSUE THREAD

**Issue by YIDING-CODER** [ant-design/pro-table#102]

**Comment by YIDING-CODER** [comment]
pro-table/src/component/intlContext/index.tsx 的第46行 `const IntlContext = React.createContext<IntlType>(zhCNIntl);` 把语言写成固定的了。。

**Comment by chenshuai2144** [comment]
https://protable.ant.design/example#english
来这里看看用法，你是不是用错了
