### ISSUE TITLE
👑 [需求] ellipsis 希望支持多行支持

### ISSUE THREAD

**Issue by wulucxy** [ant-design/pro-table#103]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]

`ellipsis` 希望支持多行支持，参考 antd [Typography.Paragrapy](https://ant.design/components/typography-cn/#Typography.Paragraph) 实现

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

场景如下：
![image](https://user-images.githubusercontent.com/5326403/73537105-9b3a6280-4462-11ea-979b-0eee7c13142c.png)

**Comment by chenshuai2144** [comment]
可以自行render一下，多行使用 缩略的概率还是比较小的
