### ISSUE TITLE
👑 [需求]希望增加Api 用于设置默认显示列

### ISSUE THREAD

**Issue by jhzzzz** [ant-design/pro-table#105]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]

设置 hideInTable 后，便无法让指定字段出现，也无法在搜索区通过该字段搜索.
事实上我们希望能做到默认不展示，但用户可以根据需要通过列设置按钮勾选来显示。

**Comment by chenshuai2144** [comment]
https://protable.ant.design/example?anchor=%E5%8F%97%E6%8E%A7%E6%A8%A1%E5%BC%8F#%E5%8F%97%E6%8E%A7%E6%A8%A1%E5%BC%8F
试试这个 api
