### ISSUE TITLE
👑 [需求]能否提供用Class实现的pro-table组件

### ISSUE THREAD

**Issue by effapp** [ant-design/pro-table#106]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]

能否提供用Class实现的pro-table组件

### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]

提供用Class实现的pro-table组件

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

用function + useState实现的组件重复render的问题难于查找和解决

**Comment by chenshuai2144** [comment]
debug 和 function 无关的，使用 class 很多功能实现起来太累

**Comment by effapp** [comment]
> debug 和 function 无关的，使用 class 很多功能实现起来太累

使用useState在首次加载组件时多次render，导致多次访问服务端重复取数据，难处理

**Comment by afc163** [comment]
> 使用useState在首次加载组件时多次render，导致多次访问服务端重复取数据，难处理

看看怎么写的，一般都是写错了。
