### ISSUE TITLE
🐛[BUG]官方提供的demo的codesandbox例子报错

### ISSUE THREAD

**Issue by effapp** [ant-design/pro-table#107]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

官方提供的demo的codesandbox例子报错，错误如下：

Error
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `ToolBar`.
▶ 28 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
This error overlay is powered by `react-error-overlay` used in `create-react-app`.

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

复现地址： https://codesandbox.io/s/7vnzy?module=/demo.tsx

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

复现地址： https://codesandbox.io/s/7vnzy?module=/demo.tsx

**Comment by chenshuai2144** [comment]
fixed，我们提供了css 和 js
