### ISSUE TITLE
🐛[BUG]当pro-table最大化时不能显示antd Modal组件

### ISSUE THREAD

**Issue by effapp** [ant-design/pro-table#108]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

当pro-table最大化时不能显示antd Modal组件

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

当pro-table最大化时，单击按钮弹出antd Modal组件，但没有任何显示。

### © 版本信息

- pro-table :[ version: 2.0.1 ]

**Comment by chenshuai2144** [comment]
@effapp  全屏模式需要用 https://ant.design/components/config-provider-cn/   getPopupContainer 来挂载到 全屏的 dom 上

**Comment by effapp** [comment]
还是不太明白，能用codesandbox做一个简单的例子吗？

**Comment by chenshuai2144** [comment]
你查看一下全屏的dom 就知道为什么了, pro-table 代码中有类似的代码

**Comment by icyes** [comment]
> 你查看一下全屏的dom 就知道为什么了, pro-table 代码中有类似的代码

搞不定，类似代码在哪

**Comment by icyes** [comment]
@chenshuai2144 全屏的dom在哪？？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-table/blob/b52365e8b7b3e5a084f296a9723dac1a43fbc4d4/src/Table.tsx#L657
在这里
