### ISSUE TITLE
🧐[问题]请问在Class组件中如何使用actionRef和formRef?

### ISSUE THREAD

**Issue by effapp** [ant-design/pro-table#109]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

请问在Class组件中如何使用actionRef和formRef?请举个例子。

**Comment by chenshuai2144** [comment]
formRef={(ref)=>this.xxx=ref}

**Comment by wulinjie122** [comment]
formRef={(ref)=>this.xxx=ref}，在class组件不起作用


`
class SysMenuList extends React.Component {

  constructor(props) {
    super(props);
    this.actionRef = React.createRef();
  }
`

`actionRef={(ref) => {
            this.actionRef = ref;
          }}`


`
// 列表刷新
              this.actionRef.current?.reload();
`
