### ISSUE TITLE
🐛[BUG] windows 获取不到actionRef的值

### ISSUE THREAD

**Issue by aniude** [ant-design/pro-table#112]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
windows 环境下useEffect 获取不到actionRef的值。
原因未知，感觉很神奇，切换到 windows 开发环境意外发现。

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
useEffect(() => {
  console.log(actionRef); //undefined
});
### © 版本信息

- Ant Design Pro 版本: 
- umi 版本
- 浏览器环境 Chrome
- 开发环境 window 10

**Comment by chenshuai2144** [comment]
来个详细代码，js 应该与平台无关的

**Comment by aniude** [comment]
https://codesandbox.io/s/pro-table-llbmu  @chenshuai2144  我在原始https://github.com/ant-design/pro-table 改的。点击列表的刷新可重现。

**Comment by aniude** [comment]
https://codesandbox.io/s/pro-table-13qk2, 点 按 time 列排序  @chenshuai2144
