### ISSUE TITLE
🧐[问题]表单初始值的问题

### ISSUE THREAD

**Issue by xclw2000** [ant-design/pro-table#114]
如何设置查询表单中某一项的初始值，我在column中设置了initialValue，发现不起作用。

**Comment by xclw2000** [comment]
怎么没有人回复呢？我自己顶一下

**Comment by chenshuai2144** [comment]
无法再现

**Comment by wccw** [comment]
> 如何设置查询表单中某一项的初始值，我在column中设置了initialValue，发现不起作用。

我接手了一个老项目，情况和你差不多，有个界面设置 initialValue 无效，自己新建一个新工程做测试，和该界面一样的代码，设置 initialValue 是有效的，不知道是工程的问题还是配置的问题，这个后续你有没有解决方案

**Comment by Alsmile** [comment]
明明一直存在，就关闭了。还让重写beforeSearchSubmit去解决：https://github.com/ant-design/pro-table/issues/134
