### ISSUE TITLE
🧐[问题]如何实现首次加载不执行查询

### ISSUE THREAD

**Issue by xclw2000** [ant-design/pro-table#115]
现在默认的行为是页面一加载就会马上执行查询。我想实现默认加载不执行查询，而是让用户通过点击查询后才执行查询。

**Comment by xclw2000** [comment]
怎么没有人回复呢？自己顶一下

**Comment by qindj** [comment]
用datasource，不要用request，初始datasource为空，点击后再赋值

**Comment by zyd0113** [comment]
> 用datasource，不要用request，初始datasource为空，点击后再赋值

那么怎么重写点击查询按钮的方法？

**Comment by qindj** [comment]
不用重写点击查询按钮的方法，设个本地state就是了

**Comment by WynterDing** [comment]
https://github.com/ant-design/pro-components/pull/31

有好些重复的issue，PR 我已经提了，关注这个 PR即可
