### ISSUE TITLE
🐛[BUG]selectedRowKeys不会因为条目被移除而改变

### ISSUE THREAD

**Issue by myonlylonely** [ant-design/pro-table#12]
以下例子打印出的selectedRowKeys，即使重载了数据，已经删除条目的Key仍然在其中。
但selectedRows中的条目是正常更新的。

```javascript
const rowSelection = {
      onChange: (selectedRowKeys, selectedRows) => {
          console.log(`selectedRowKeys: ${selectedRowKeys}`, 'selectedRows: ', selectedRows);
    },
  };
//ProTable定义
<ProTable
//...
        rowSelection={rowSelection}
//...
```

**Comment by chenshuai2144** [comment]
rows 时根据data 和 keys 算出来的，rows 其实是当前页选中的 rows

**Comment by myonlylonely** [comment]
> rows 时根据data 和 keys 算出来的，rows 其实是当前页选中的 rows

那请问selectedRowKeys中包含已经删除的Key，这个行为是符合预期还是Bug？

**Comment by chenshuai2144** [comment]
@myonlylonely  这个是故意的，不然翻页会丢失掉选中的 key。批量删除这种的需要这个特性。

**Comment by axolo** [comment]
可惜selectedRowKeys不带这个特性，否则批量操作不用再去查一次数据库详情。另外最好有一个开关，选择项是否仅本页。
