### ISSUE TITLE
proTable（2.0.1） 使用 antd4时，ellipsis: true，必须指定width才能生效🐛[BUG]

### ISSUE THREAD

**Issue by kaoding** [ant-design/pro-table#122]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
![image](https://user-images.githubusercontent.com/18542211/74106030-0cce8b00-4b9e-11ea-8ba0-e30f2c783bac.png)

![image](https://user-images.githubusercontent.com/18542211/74106049-3b4c6600-4b9e-11ea-862a-a27a7e2086a2.png)

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
**加上copyable：true,超出范围的显示不出来。**
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by kaoding** [comment]
ellipsis: true 原生antd3和antd4中都支持的。

**Comment by chenshuai2144** [comment]
实现方式不同，官方 ellipsis 使用 css 实现的，只支持title
