### ISSUE TITLE
 antd_es_form__WEBPACK_IMPORTED_MODULE_7__.default.useForm is not a function 🐛[BUG]

### ISSUE THREAD

**Issue by Wmstone** [ant-design/pro-table#124]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

-  antd_es_form__WEBPACK_IMPORTED_MODULE_7__.default.useForm is not a function
- The above error occurred in the <FormSearch> component

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
使用的是pro-table 2.0.1版本，昨天（2月9日）开发测试时候没有问题，今天发现报错

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
4.0.0
- umi 版本
2.8.7
- 浏览器环境
谷歌
- 开发环境 [e.g. mac OS]
windows

**Comment by Wmstone** [comment]
在测试后发现<Protable ></Protable>使用了columns就会报错

**Comment by Wmstone** [comment]
const columns: ProColumns[] = [
    {
        title: 'age',
        dataIndex: 'age'
    },
    {
        title: 'name',
        dataIndex: 'name'
    }
]

                <ProTable
                    columns={columns}
                >

                </ProTable>

**Comment by chenshuai2144** [comment]
需要antd 4.0

**Comment by Wmstone** [comment]
好的

**Comment by chenshuai2144** [comment]
3.0 可以用 1.x 版本

**Comment by deevannaveed** [comment]
Same error and I don't know what is wrong! if its only supported in 4.0 then WTH they don't mention the version number in docs!!!!!!!!!!!!!!!
