### ISSUE TITLE
1.x和2.x比较🧐[问题]

### ISSUE THREAD

**Issue by kaoding** [ant-design/pro-table#125]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
1.x（下面截图）
![image](https://user-images.githubusercontent.com/18542211/74124393-235ffb00-4c0d-11ea-9c38-5ae63bfa32dc.png)

2.x（下面截图）
![image](https://user-images.githubusercontent.com/18542211/74124369-13e0b200-4c0d-11ea-8c9e-194f93cfe795.png)

**2.x问题**

1. 查询下面留白比较多
2. 字段为 ellipsis: true 时，显示有问题。

**Comment by chenshuai2144** [comment]
已经发布了新版本，还是不能使用原生的，会有一些别的问题
