### ISSUE TITLE
🧐[问题]请问通过request参数设置一个promise请求,为什么出现多次重复的请求呢

### ISSUE THREAD

**Issue by liwei1991** [ant-design/pro-table#13]
请问通过request参数设置一个promise请求,为什么出现多次重复的请求呢，我通过谷歌浏览器刷新页面，发现有3次重复的请求，重复请求后端的接口数据

**Comment by guchongxi** [comment]
同楼上，README 中 codesandbox 示例可稳定复现

尝试在 index.tsx 中加入 log 

![image](https://user-images.githubusercontent.com/21251584/71248631-4d581800-2356-11ea-8365-f42ca75d1abe.png)

打开控制台可看到

![image](https://user-images.githubusercontent.com/21251584/71248666-682a8c80-2356-11ea-824b-67bdaade833a.png)

**Comment by guchongxi** [comment]
查看源码，发现 props 传入 manual 可以避免请求两次，但是文档没有说明这个字段是什么意思

**Comment by chenshuai2144** [comment]
新版本中会解决这个问题，是因为 pageIndex 从 null 变成 1 导致的。

**Comment by myonlylonely** [comment]
类似的问题，初次打开页面，第一页会请求2次。

**Comment by chenshuai2144** [comment]
fix in v1.0.21

**Comment by xclw2000** [comment]
仍然会请求2次
![image](https://user-images.githubusercontent.com/32091566/71405879-9ddeb680-2671-11ea-8809-a1e21fccf30b.png)

**Comment by chenshuai2144** [comment]
求一个重现

**Comment by xclw2000** [comment]
> 求一个重现

删掉node_module，重新yarn一下，又好了。谢谢

**Comment by effapp** [comment]
升级到1.0.34,首次加载仍然会请求2次
