### ISSUE TITLE
 type=form 在 Model 不显示“提交”和“重置” 👑 [需求]

### ISSUE THREAD

**Issue by kaoding** [ant-design/pro-table#131]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]

![image](https://user-images.githubusercontent.com/18542211/74304378-cba1cb00-4d97-11ea-8ca3-d9582a1bbd11.png)

### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]

**提供  type=form 在  Model 不显示“提交”和“重置”**

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

```
<ProTable
            type="form"
            columns={columns}
            onSubmit={params => {
              // eslint-disable-next-line no-console
              console.log(params);
            }}
            search={{ submitText: '确认', resetText: '取消' }}
   />
```
**在ProTable  加上 type=form 代码后，在console报出下错误**

![image](https://user-images.githubusercontent.com/18542211/74304326-9ac19600-4d97-11ea-8d71-2c76ce65225f.png)

![image](https://user-images.githubusercontent.com/18542211/74304343-a57c2b00-4d97-11ea-9cd3-d4b1a2b00b2b.png)

![image](https://user-images.githubusercontent.com/18542211/74304262-664dda00-4d97-11ea-9909-742fe7ac64b2.png)

**Comment by kaoding** [comment]
### 使用 ProTable type="form" 和 自定义的 Model **比较** 的结果：

1. “提交”和“重置”不能自定义，无法使用 Model 的 onOk 和 onCancel
2.  ProTable type="form" 只能使用预设的组件（这个问题是实际比较难解决的）
3.  ProTable type="form" 的行高比 自定义的 Model 行距比较大
4.  ProTable type="form" 不能统一赋值（https://github.com/ant-design/pro-table/issues/132）

-  ### 下面是 : ProTable type="form"
![image](https://user-images.githubusercontent.com/18542211/74334228-759f4880-4dd4-11ea-9f94-a64c4850a950.png)

-  ### 下面是 : 自定义的 Model 
![image](https://user-images.githubusercontent.com/18542211/74334164-5f918800-4dd4-11ea-92c4-6817586283fd.png)

@chenshuai2144 @afc163

**Comment by chenshuai2144** [comment]
> “提交”和“重置”不能自定义，无法使用 Model 的 onOk 和 onCancel

会提供一个api，来隐藏操作按钮

2. ProTable type="form" 只能使用预设的组件（这个问题是实际比较难解决的）

可以用renderIten解决，并且使用hideInFrom

ProTable type="form" 的行高比 自定义的 Model 行距比较大

> 这个没有听懂

> ProTable type="form" 不能统一赋值（https://github.com/ant-design/pro-table/issues/132）

可以为每个单独设置

**Comment by kaoding** [comment]
ProTable type="form" 的行高比 自定义的 Model 行距比较大

这个没有听懂：上下表单间的间距比较大。

**Comment by liuyun521** [comment]
> ### 使用 ProTable type="form" 和 自定义的 Model **比较** 的结果：
> 1. “提交”和“重置”不能自定义，无法使用 Model 的 onOk 和 onCancel
> 2. ProTable type="form" 只能使用预设的组件（这个问题是实际比较难解决的）
> 3. ProTable type="form" 的行高比 自定义的 Model 行距比较大
> 4. ProTable type="form" 不能统一赋值（[https://github.com/ant-design/pro-table/issues/132）](https://github.com/ant-design/pro-table/issues/132%EF%BC%89)
> 
> * ### 下面是 : ProTable type="form"
> 
> ![image](https://user-images.githubusercontent.com/18542211/74334228-759f4880-4dd4-11ea-9f94-a64c4850a950.png)
> 
> * ### 下面是 : 自定义的 Model
> 
> ![image](https://user-images.githubusercontent.com/18542211/74334164-5f918800-4dd4-11ea-92c4-6817586283fd.png)
> 
> @chenshuai2144 @afc163

没懂怎么设置使用

**Comment by wj100** [comment]
同问，怎么取消protable的重置、查询按钮，我也是把table嵌在modal里面

**Comment by iambabewin** [comment]
<ProTable
  form={{
    submitter: {
      resetButtonProps: {hidden: true},
      submitButtonProps: {loading: true},
    },
  }}
/>

**Comment by iambabewin** [comment]
> 同问，怎么取消protable的重置、查询按钮，我也是把table嵌在modal里面

```
<ProTable
type="form"
form={{
submitter: {
resetButtonProps: {hidden: true},
submitButtonProps: {loading: true},
},
}}
/>
```
