### ISSUE TITLE
type="form" 赋值表单项 👑 [需求]

### ISSUE THREAD

**Issue by kaoding** [ant-design/pro-table#132]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]

1. 现在的做法：为colums里的每列使用 initialValue 赋值给表单项 或者通过 formItemProps 透传给表单项，不能做到统一 赋值表单项。
2. 新需求：为colums里点“编辑”，一般是将当前行数据（record）做为一个对象统一赋值的，如果不将这个问题解决，type="form"时只能做“新增”使用，做“更新”使用就比较麻烦。

### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]

1. 在<ProTable> 提供 **initialValues** props

```
 <ProTable
            type="form"
            columns={columns}
            initialValues={{ remember: true }}
            onSubmit={params => {
              // eslint-disable-next-line no-console
              console.log(params);
            }}
            search={{ submitText: '确认', resetText: '取消' }}
 />
```

2. 在非 type !='form' 里也可以给查询的表单项统一赋值使用。

**Comment by kaoding** [comment]
加了 type="form" 后，版本号该为 v2.1.x 比较合理。

**Comment by chenshuai2144** [comment]
@kaoding  正式发布的时候会加，现在是个尝鲜模式

**Comment by chenshuai2144** [comment]
要复制可以在每一项里设置 initialValue，而不是统一设置
