### ISSUE TITLE
initialValue在首次加载时并没有应用到request🐛[BUG]

### ISSUE THREAD

**Issue by xclw2000** [ant-design/pro-table#134]
版本号2.0.5
问题描述：
1.设置column.initialValue
2.SearchForm中正常显示initialValue
3.request的param中并没用应用初始值
4.点击SearchForm中的查询按钮，初始值被应用

问题2：如果设置页面加载后默认不执行request，而是等用户点击查询才执行request?数据较多不想用户默认加载数据

**Comment by kaoding** [comment]
1. initialValue只作用在Form中，和request的param没有关系
2. 本来ProTable中有一个params属性设置的值会直接反应在request的param参数中，看样子后面会把ProTable中的params拿掉（的确意义不大）
3. 设置查询初始值可以直接在request的param参数做更改

**Comment by xclw2000** [comment]
> 1. initialValue只作用在Form中，和request的param没有关系
> 2. 本来ProTable中有一个params属性设置的值会直接反应在request的param参数中，看样子后面会把ProTable中的params拿掉（的确意义不大）
> 3. 设置查询初始值可以直接在request的param参数做更改

也就是我应该在request方法中只直接忽略传给我的param, 改为自己从formRef中获取一下，然后再传给后台方法。因为我现在的现象是加载后首次调用request时，传给我的param并没有取到formRef中的值，只有点过一次查询按钮后，这个param才从form中取值。所以我干脆直接每次都是自己从formRef中取值得了。

另外我的问题2应该怎么解决呢？

**Comment by uliian** [comment]
同问，初次调用request时，param里没有form中的数据
并且formRef中的current为undefined

**Comment by qiqizjl** [comment]
同样的问题 怀疑是request请求的时候form未加载完成导致formref取不到对应的值 请问有解决方案了么

**Comment by chenshuai2144** [comment]
@qiqizjl 可以在 params 里面设置进去

**Comment by chenchen0501** [comment]
> @qiqizjl 可以在 params 里面设置进去

这样并不能提现默认值的作用吧，默认值不是只有第一次有效吗，如果按你这么加的话，是不是每一次都会把这个默认值带进去

**Comment by bluescurry** [comment]
@chenshuai2144 请问这个问题现在有解决方案了吗

**Comment by lhsaq2009** [comment]
```
{
    title: '时间选择',
    dataIndex: 'dateRange',
    valueType: 'date',
    hideInTable: true,
    initialValue: [
        moment(localStorage.getItem(cache.dateRange_begin) || moment().startOf('day').subtract(1, 'month'), dateFormat),
        moment(localStorage.getItem(cache.dateRange_end) || moment().startOf('day'), dateFormat)
    ],
    renderFormItem: (_, {value, onChange, type, defaultRender, ...rest}, form) => {
        return <RangePicker
            onChange={(time, timeString) => {
                // 得回调 ProColumnType 的 onChange，否则谁知道 initialValue 是个啥玩意。
                // ?. 是 ts 3.7 的 Optional Chaining 新语法
                onChange?.(time);                                            
                localStorage.setItem(cache.dateRange_begin, timeString[0]);
                localStorage.setItem(cache.dateRange_end, timeString[1]);
            }}
        />
    },
}
```
