### ISSUE TITLE
🐛[BUG] antd pro 4 下1.0.35报错

### ISSUE THREAD

**Issue by uliian** [ant-design/pro-table#135]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
对于antd pro 4 下，1.0.35破坏了兼容性，导致无法正常使用
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
使用antd-pro + umi进行antd pro开发时，正常添加antd模板，添加查询表格模板，运行时报错：
`antd_es_form.default.create(...)` is not a function

![image](https://user-images.githubusercontent.com/3947701/74586305-403b6a80-5021-11ea-82ad-b45b93dd7eeb.png)

### 🏞 期望结果 [描述你原本期望看到的结果]
正常执行
### © 版本信息

- Ant Design Pro 版本: [4.0.0]
- umi 版本：1.8.3
- 浏览器环境：Microsoft Edge（chromium） 80.0.361.50
- 开发环境  win10

**Comment by chenshuai2144** [comment]
使用2.0 即可，1.0是基于antd@3的
