### ISSUE TITLE
valueType='digit' 👑 [需求]

### ISSUE THREAD

**Issue by kaoding** [ant-design/pro-table#136]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
现在的 valueType=‘money’ 在查询和Form时是使用 InputNumber，但在table显示时前面有 ¥，在有一些需求中（如：年龄）就是纯数字，在显示的时候不加前缀，所以希望可以增加类型这种纯属数字的valueType

**Comment by chenshuai2144** [comment]
纯数字需要格式化吗？还是说只是希望可以使用inputnumber？

**Comment by kaoding** [comment]
只是希望可以使用InputNumber，格式化的工作交给用户自己完成。 
@chenshuai2144

**Comment by kaoding** [comment]
up

**Comment by afc163** [comment]
又忘记关联 issue 了。

**Comment by kaoding** [comment]
https://github.com/ant-design/pro-table/commit/b4b53abc112066081303293349a5875437c1830f

**Comment by kaoding** [comment]
> 又忘记关联 issue 了。

https://github.com/ant-design/pro-table/commit/b4b53abc112066081303293349a5875437c1830f
