### ISSUE TITLE
🐛[BUG]search.md  beforeSearchSubmit 重复

### ISSUE THREAD

**Issue by ibmsoft** [ant-design/pro-table#137]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
| beforeSearchSubmit | 搜索之前进行一些修改 | `(params:T)=>T` | - |
重复

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
来个pr吧
