### ISSUE TITLE
🧐[问题] ProTable request 属性传入的方法里面如何获取state更新的值

### ISSUE THREAD

**Issue by yinlianggood** [ant-design/pro-table#140]
![image](https://user-images.githubusercontent.com/10203628/74666303-3742c880-51dc-11ea-9865-ed1a7d4ef2da.png)
initData方法里面，会获取最新的值作为参数去请求不同的数据，但是每次取的都是第一次的旧值，实际这个值有更新。 请问一下，传入的这个initData方法里面是无法获取到新的状态值吗 ？

所以我使用了dataSource属性来更新数据，但是使用了dataSource属性后，pageSize, current, total 这些参数我该如何传入至组件呢 ？ 使用request 属性来获取数据，initData 会返回这些数据到组件， 但是我用dataSource属性，不知道如何传入

**Comment by chenshuai2144** [comment]
> 最新的值

你的值是从哪里来的？

**Comment by yinlianggood** [comment]
@chenshuai2144 
![image](https://user-images.githubusercontent.com/10203628/74697447-b31d2f00-5235-11ea-8be7-9f52f09de45e.png)
其它方法里面调用setSelectIndex(index)更新的值， initData里面会使用selectIndex，但是取到的值都是第一次的值，不是最新的。

**Comment by chenshuai2144** [comment]
放到 params 里面就好了，会自动注入的

**Comment by yinlianggood** [comment]
@chenshuai2144  
![image](https://user-images.githubusercontent.com/10203628/74698370-7999f300-5238-11ea-84db-4f6f40b97692.png)
可以了，谢谢你！

**Comment by chenshuai2144** [comment]
@yinlianggood  table 有个params 的属性，你放到 params 里面，这样selectIndex 修改不会触发reload的

**Comment by yinlianggood** [comment]
@chenshuai2144 
![image](https://user-images.githubusercontent.com/10203628/74698642-8cf98e00-5239-11ea-9a29-8a250d6d901e.png)
好了， 谢谢您！
