### ISSUE TITLE
🧐[问题] 如何默认加载第 N 页的数据

### ISSUE THREAD

**Issue by weekwood** [ant-design/pro-table#141]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
由于 url 里返回了对应的默认加载比如加载第三页，但是我传入current 以及 pagesize 到 params 并不会更新对应的 pageInfo，每次都是读取的 pageInfo 的默认值 current:1 以及 pageSize:10
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
https://github.com/ant-design/pro-table/blob/1e692661f71110fd20cf32483d59c52468b32887/src/useFetchData.tsx#L98
目前看来首次加载的时候这一行 pageInfo 读取的是之前的默认值
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/310350/74706513-1b7a0980-5252-11ea-9140-30439f84e531.png)

虽然我返回了正确的当前页
![image](https://user-images.githubusercontent.com/310350/74706708-a78c3100-5252-11ea-980e-f83fdfe9ffee.png)

但是由于 setPageInfo 只针对 total 进行了更新，所以引发了这个错误
![image](https://user-images.githubusercontent.com/310350/74706723-b2df5c80-5252-11ea-93a1-ded17c643241.png)

**Comment by chenshuai2144** [comment]
是个bug，我来修一下

**Comment by tianyunperfect** [comment]
defaultPageSize 在哪设置的？

**Comment by NoXCZJ** [comment]
> defaultPageSize 在哪设置的？

ProTable继承了antd 的table，你可以直接用pagination属性，在pagination中配置defaultPageSize就可以了
