### ISSUE TITLE
🐛[BUG]type=form时，在检验失败的情况下，仍会提交

### ISSUE THREAD

**Issue by qindj** [ant-design/pro-table#143]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
如题

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
1.yarn-create-umi 新建antd@4项目
2.模板创建的tablelist, 自带createForm
3. 点击新建，不填，直接点提交
4. 字段过不了检验，红色显示为必填项，console有错误提示
5. handleAdd会继续执行、提示成功、提示刷新

### 🏞 期望结果 [描述你原本期望看到的结果]
检验失败，不应继续执行

### © 版本信息

- Ant Design Pro 版本: 5.0.2
- umi 版本
- 浏览器环境 Chrome
- 开发环境 mac OS

**Comment by aLIEzsss4** [comment]
"@ant-design/pro-table": "^2.1.3",
升级到最新版，还是会出现该问题

**Comment by qindj** [comment]
@aLIEzsss4 还没发布呢吧，2.1.3之后才修复的

**Comment by qindj** [comment]
@chenshuai2144 大佬啥时候发个小版本~
