### ISSUE TITLE
ProTable API 拆分建议 👑 [需求]

### ISSUE THREAD

**Issue by kaoding** [ant-design/pro-table#145]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]

1. 现有的ProTable在Table的基础扩展了三块内容（一块增强了Table，另两块就是“Search”和“Form")
2. 现在的”Search“是和ProTable一起进行控制的，如：<ProTable search={true} ...props />，而“Form"则是独立的ProTable控制，如：<ProTable type="form" ...props />，而这三块内容共享了同一个columns
3. 这种方式API看上去没有什么”规则“

### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]

1. 按 **ProLayout** 的API组织方式是否更好，如下：

`import ProTable，{ ProTableSearch, ProTableForm } from '@ant-design/pro-table';`

2. “Search”显示的位置可以由用户放置<ProTableSearch columns={columns}} />

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

- 问题：如果按拆分设置 API，ProTable，ProTableSearch 和 ProTableForm 之间数据联动怎么办？
- 注：现有的是通过 columns

**Comment by okool** [comment]
pro-table 非官方的组件,没人响应,太浪费时间了,主要想用官方的区块.
因为没法很好的支持自定义form和table.放弃使用pro-table
重写一个 form+toolbar+table+page 就完工了.

**Comment by WynterDing** [comment]
@kaoding 你的建议挺好的，我们也正在考虑在把一些组件单独拆分开来，对 API 进行一些梳理。

@okool pro-table 后续会作为pro-components 系列维护，我们也算是官方了，有什么问题、使用上的痛点都欢迎提 issue 交流

**Comment by kaoding** [comment]
> @kaoding 你的建议挺好的，我们也正在考虑在把一些组件单独拆分开来，对 API 进行一些梳理。
> 
> @okool pro-table 后续会作为pro-components 系列维护，我们也算是官方了，有什么问题、使用上的痛点都欢迎提 issue 交流

OK
