### ISSUE TITLE
🐛[BUG]columns配置renderFormItem后控制台报错

### ISSUE THREAD

**Issue by zlyyyy** [ant-design/pro-table#147]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
columns配置后控制台报错如图

<img width="1390" alt="屏幕快照 2020-02-19 下午6 54 37" src="https://user-images.githubusercontent.com/22760932/74828236-b99ccb00-5349-11ea-9962-089e40196999.png">

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
```javascript
{
      title: '进度',
      dataIndex: 'progress',
      valueType: 'progress',
      renderFormItem: (item, props)=> {
        return (
          <InputNumber {...props} />
        )
      }
    },
```
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by zlyyyy** [comment]
还是说配置参数不对

**Comment by chenshuai2144** [comment]
@zlyyyy  这个是说有些参数被透传到 dom 上了，不会影响功能的

**Comment by zlyyyy** [comment]
@chenshuai2144 好的，感谢

**Comment by chenshuai2144** [comment]
也是问题，需要修一下的

**Comment by kaoding** [comment]
和这个是同一个问题
https://github.com/ant-design/pro-table/issues/146
