### ISSUE TITLE
api suggestion

### ISSUE THREAD

**Issue by zombieJ** [ant-design/pro-table#15]
* `dataSource`  可以直接支持 function，`request` 可以省了
* `filterData` -> `postData`，随便过滤添加，反正自己改着玩就行
* `manual` 和 `effects`  太裸了，需要封装掉或者帮用户处理掉
* `onInit` -> `onPostData`
* `momentFormat` 看看能不能做到一个诸如 `valueFormatter` 的属性里，让用户配置：
```tsx
valueFormatter = {
  moment: d => d.format('YYYY-MM-DD'),
  xxx: xxxx => xxxx,
}
```

**Comment by afc163** [comment]
action.xxx 建议都去掉。

**Comment by chenshuai2144** [comment]
重新加载还是个很常见的需求。如果不能通过行为控制，要刷新 table 的时候会很痛苦

**Comment by afc163** [comment]
`重新加载` 这个可以，和请求相关的（非 UI），相当于 refetch。

**Comment by crashsol** [comment]
最近用umijs Hook那种方式来操作Table，感觉也挺好用的

**Comment by chenshuai2144** [comment]
dataSource  我直接透传了，还是希望用户可以降级回 antd table的模式

**Comment by chenshuai2144** [comment]
valueFormatter  感觉应该是个 function，不是一个object. 
现在只有moment 这种的处理起来很烦，但是比较格式化。剩下的在 `beforeSearchSubmit` 处理就可以了

**Comment by zombieJ** [comment]
特地做一个 moment api 不太好，v4 用户是可以和 moment 解耦的，如果要用 dayjs 还得来个 dayjsFormatter

**Comment by chenshuai2144** [comment]
dateFormatter?

**Comment by zombieJ** [comment]
`dateFormatter` 你怎么判断是那个日期库呢？

**Comment by chenshuai2144** [comment]
emmm 也是，但是 moment 格式化让人很烦躁，如果能默认做掉是最好的。
dateFormatter = string | number | ()=>any

这样呢 ，识别一下 moment 和 dayjs

**Comment by zombieJ** [comment]
日期库不止这两个，如果用户了用原生的？感觉枚举不完了。
另外 `() => any` 这个，相当于传入任何一个 object 都被过一遍 `dateFormatter` 即便它不是一个 date object。

**Comment by chenshuai2144** [comment]
现在先支持 dayjs 和 moment 吧  bigfish 和 antd 内置的都是 moment。由第三方需求的可以用 `beforeSearchSubmit `
