### ISSUE TITLE
🧐[问题]使用dataSource 和 loading时,如何获取到查询按钮跟刷新按钮的事件

### ISSUE THREAD

**Issue by l745230** [ant-design/pro-table#151]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
目前文档中,使用dataSource 和 loading的demo,查询跟刷新按钮是无效的操作

**Comment by qindj** [comment]
reload可以传function进去，看下文档，options参数
表单提交没理解错的话，用onSubmit，多看看文档和源码

https://github.com/ant-design/pro-table/blob/abd50cd025b11309181d5bca8f513857640fc8ea/src/Table.tsx#L252-L255

**Comment by l745230** [comment]
@qindj 求指导,reload试了好多种写法,点击时控制台都无法输出
![image](https://user-images.githubusercontent.com/15940920/74996297-26b97900-548e-11ea-84b8-a1c6800ccc72.png)

**Comment by qindj** [comment]
@l745230 我也没用过，等大佬解惑  @chenshuai2144

**Comment by l745230** [comment]
reload: () => {
          console.log(1)
        },

点击按钮,能触发到reload了,但是还有个问题,当前参数如何获取到? 
参数需求: 当前搜索的内容,页数页码,排序字段.

**Comment by chenshuai2144** [comment]
可以在 request 里面去找一下，现在好像没有好办法
