### ISSUE TITLE
🐛[BUG]移动端进行滚动的时候,控制台出现大量错误

### ISSUE THREAD

**Issue by l745230** [ant-design/pro-table#156]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

![image](https://user-images.githubusercontent.com/15940920/74998895-fa552b00-5494-11ea-86c1-db0c46099781.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
这个是因为 father doc 的滚动事件没有正确设置参数导致的。
https://github.com/umijs/father-doc/pull/84
