### ISSUE TITLE
🐛[BUG] 单元格无法合并

### ISSUE THREAD

**Issue by hanwensheng666** [ant-design/pro-table#158]
### 🐛  rc-table 的 render函数可返回一个对象 {props,children} ，pro-table中未做处理
![image](https://user-images.githubusercontent.com/34360878/75010158-6c3e6c00-54b7-11ea-8c0c-d90bf9998383.png)

### 💻 复现代码
![image](https://user-images.githubusercontent.com/34360878/75010386-f2f34900-54b7-11ea-8d80-11c4643e67f8.png)

### © 版本信息

- pro-table 版本: 1.0.35

**Comment by YangYuHub** [comment]
没有很懂如何和合并单元格， 请问有DEMO？
