### ISSUE TITLE
👑 [需求]字段生成查询,时间类型加个RangePicker.

### ISSUE THREAD

**Issue by l745230** [ant-design/pro-table#160]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
![image](https://user-images.githubusercontent.com/15940920/75025720-a703cc80-54d6-11ea-98db-1863a9c2afa9.png)
很多时间字段的查询都需要使用到RangePicker.~~

**Comment by chenshuai2144** [comment]
已经有了 
https://protable.ant.design/value-type#valuetype
