### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by peerswu** [ant-design/pro-table#162]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
表单select复选两个选项，查询出现报错

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
选择复选两个select option查询时，出现报错：
index.js:247 Uncaught (in promise) TypeError: itemValue[0].format is not a function
    at index.js:247
    at Array.forEach (<anonymous>)
    at genValue (index.js:227)
    at _callee$ (index.js:365)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:271)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at asyncGeneratorStep (index.js:20)
    at _next (index.js:22)
    at index.js:22
    at new Promise (<anonymous>)
    at index.js:22
    at submit (index.js:398)
    at onClick (index.js:514)

index.js:247行代码如下：
225 var genValue = function genValue(value, dateFormatter, proColumnsMap) {
226   var tmpValue = {};
227   Object.keys(value).forEach(function (key) {
228     var itemValue = value[key];
229 
230     if (itemValue && itemValue !== 'all') {
231       if (moment.isMoment(itemValue) && dateFormatter) {
232         if (dateFormatter === 'string') {
233           var formatString = dateFormatterMap[(proColumnsMap[key || 'null'] || {}).valueType || 'dateTime'];
234           tmpValue[key] = itemValue.format(formatString || 'YYYY-MM-DD HH:mm:ss');
235           return;
236         }
237 
238         if (dateFormatter === 'number') {
239           tmpValue[key] = itemValue.valueOf();
240           return;
241         }
242       }
243 
244       if (Array.isArray(itemValue) && itemValue.length === 2 && dateFormatter) {
245         if (dateFormatter === 'string') {
246           var _formatString = dateFormatterMap[(proColumnsMap[key || 'null'] || {}).valueType || 'dateTime'];
247           tmpValue[key] = [itemValue[0].format(_formatString || 'YYYY-MM-DD HH:mm:ss'), itemValue[1].format(_formatString || 'YYYY-MM-DD HH:mm:ss')];
248           return;
249         }
250 
251         if (dateFormatter === 'number') {
252           tmpValue[key] = [itemValue[0].valueOf(), itemValue[1].valueOf()];
253           return;
254         }
255       }
256 
257       tmpValue[key] = itemValue;
258     }
259   });
260   return tmpValue;
261 };

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
const columns: ProColumns<TableListItem>[] = [
    {
      title: '运营商',
      dataIndex: 'isp',
      valueEnum: {
        1: '未知',
        2: '电信',
        3: '联通',
        4: '移动'
      },
      formItemProps: { mode: 'multiple' }
    }
];
return (
      <ProTable<TableListItem>
        columns={columns}
        ...>
      </ProTable<TableListItem>
)

选择两个运营商，点击提交，出现报错信息

### © 版本信息

- Ant Design Pro 版本: [1.0.39]
- umi 版本
- 浏览器环境 chrome 79.0.3945.130
- 开发环境 [mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/8359841/75091017-d6ccd600-55a3-11ea-9ac0-311011bad642.png)
![image](https://user-images.githubusercontent.com/8359841/75091083-8b66f780-55a4-11ea-8e0c-962e2b5b6d1c.png)

**Comment by chenshuai2144** [comment]
判断没写好，我来修一下
