### ISSUE TITLE
🐛[BUG]  嵌套数据不能正确获取

### ISSUE THREAD

**Issue by XiaYaXia** [ant-design/pro-table#163]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
columns:里面
dataIndex: 'userData.login_times',   嵌套数据不能正确获取呢  以前都可以的！

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本

**Comment by chenshuai2144** [comment]
都要写标题，不写看起来很奇怪，就没人来帮你看了

**Comment by XiaYaXia** [comment]
好的 收到

**Comment by chenshuai2144** [comment]
新版本中要通过 string数据组来使用 
`["userData","login_times"] `

**Comment by XiaYaXia** [comment]
哦哦哦  谢谢

**Comment by XiaYaXia** [comment]
{
      title: '登录次数',
      dataIndex: '["userData","login_times"]',
      sorter: true,
      renderText: (val: string) => `${val} 次`,
    },


还是无法正常显示    undefined 次

**Comment by chenshuai2144** [comment]
你的 antd 的版本是？

**Comment by XiaYaXia** [comment]
4.0.0-rc.5

**Comment by chenshuai2144** [comment]
把你的数据和配置 show 一下？

我来本地重现一下

**Comment by XiaYaXia** [comment]
接口数据
`{"code":1,"msg":"数据加载成功","data":{"list":[{"id":2,"username":"12312312333","nickname":"123123123","avatar":null,"password":"**************","create_time":"2020-02-09 09:24:30","create_ip":"127.0.0.1","update_time":"2020-02-23 01:49:59","status":0,"openid":"","userData":{"id":2,"login_times":0,"last_login_ip":"0","last_login_time":"1970-01-01 08:00:00","uid":2,"head_img":null},"group_id":[1]},{"id":1,"username":"root","nickname":"root","avatar":"https:\/\/avatars1.githubusercontent.com\/u\/8186664?s=40&v=4","password":"**************","create_time":"2019-10-08 13:58:52","create_ip":"2130706433","update_time":"2020-01-06 15:38:57","status":1,"openid":null,"userData":{"id":1,"login_times":312,"last_login_ip":"127.0.0.1","last_login_time":"2020-02-23 02:18:16","uid":1,"head_img":""},"group_id":[1]}],"count":2}}`

columns 配置项
`{
      title: '用户ID',
      dataIndex: 'id',
    },
    {
      title: '头像',
      dataIndex: 'avatar',      
      render: (val) => (<Avatar shape="square" src={val} />),
    },
    {
      title: '用户名',
      dataIndex: 'username',
    },
    {
      title: '昵称',
      dataIndex: 'nickname',
    },
    {
      title: '手机号',
      dataIndex: 'mobile',
    },
    {
      title: '余额',
      dataIndex: 'money',
      valueType: 'money',
    },
    {
      title: '登录IP',
      dataIndex: 'create_ip',
    },
    {
      title: '登录次数',
      dataIndex: '["userData","login_times"]',
      sorter: true,
      renderText: (val: number) => `${val} 次`,
    },    `

**Comment by XiaYaXia** [comment]
protable 是区块导入的表格模板

**Comment by kun391** [comment]
I have same isssue with @XiaYaXia

**Comment by chennng** [comment]
> {
> title: '登录次数',
> dataIndex: '["userData","login_times"]',
> sorter: true,
> renderText: (val: string) => `${val} 次`,
> },
> 
> 还是无法正常显示 undefined 次

改为数组，不是json字符串 dataIndex: ["userData","login_times"],
