### ISSUE TITLE
🧐[问题] 搜索表单可以支持自定义搜索函数吗

### ISSUE THREAD

**Issue by Mu-xue** [ant-design/pro-table#165]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
当表格是分页请求数据的时候，点击搜索，应该发送请求至后端，后端返回符合条件的数据，目前ProTable好像还没有类似于onSearch的属性去自定义搜索操作

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
无

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/26177732/75140335-a57e1280-5729-11ea-92bb-17a2727f5d16.png)

**Comment by qindj** [comment]
beforeSearchSubmit 可以格式化搜索表单所提及的数据
onSubmit会在表单提交时触发

**Comment by axolo** [comment]
param参数可以自动注入呀，见官方文档。https://protable.ant.design/example#toolbar-%E6%90%9C%E7%B4%A2
因为重复检查机制问题，需要在请求时格式化查询参数，别动state，否则很可能再次查询不发请求。
