### ISSUE TITLE
🐛[BUG]表头高度不跟随密度变化而调整

### ISSUE THREAD

**Issue by axolo** [ant-design/pro-table#166]
### 🐛 bug 描述

调整表格密度时，表头不跟随变化，很不协调。

### 📷 复现步骤

右上角表格控制密度按钮，选择密度，表头高度始终不变

### 🏞 期望结果

表头高度根据密度变化，顺便把antd紧凑模式表头底色变白的bug给解决了吧

### © 版本信息

- Ant Design Pro 版本： 4.0
- umi 版本： 2.13.3
- 浏览器环境： Chrome 80
- 开发环境： Windows 10

**Comment by chenshuai2144** [comment]
这是 antd 的特性了，bug 应该提交到 antd

**Comment by kaoding** [comment]
antd 就是这样的
