### ISSUE TITLE
🐛[BUG]1.0.40的搜索不带搜索表单参数了

### ISSUE THREAD

**Issue by zlyyyy** [ant-design/pro-table#169]
版本1.0.40
![image](https://user-images.githubusercontent.com/22760932/75424181-1a945680-597b-11ea-80bd-922002eac5b2.png)
查询事件params没有form中输入的参数

**Comment by zlyyyy** [comment]
是不是跟我用的antd版本有关系 现在我用的antd^4.0.0-rc.1

**Comment by cocowhr4545** [comment]
无关
不带参数+1
考虑降级中

**Comment by zlyyyy** [comment]
@cocowhr4545 我感觉有关系，报错
![image](https://user-images.githubusercontent.com/22760932/75425096-fb96c400-597c-11ea-908d-8612645e54e3.png)

**Comment by zlyyyy** [comment]
@chenshuai2144 大佬有时间看看咋回事嘛

**Comment by vip55zxc** [comment]
我也是遇到了此问题，前几天还可以用，今天突然不可以用了。我这里没报错 就是拿不到值了，你们是怎么解决的？

**Comment by zlyyyy** [comment]
@vip55zxc 没人处理，我暂时自己写搜索表单了

**Comment by cocowhr4545** [comment]
> 我也是遇到了此问题，前几天还可以用，今天突然不可以用了。我这里没报错 就是拿不到值了，你们是怎么解决的？
降到1.0.39

**Comment by guozongwei** [comment]
我的是1.0.40 ，列表中的key如果是驼峰就不行，搜索输入的值拿不到，我的解决方式是在key中用-链接，请求前处理下参数。。。skuId --->sku-id

**Comment by chenshuai2144** [comment]
试着更新一下版本，已经解决了。

**Comment by zlyyyy** [comment]
更新版本后好啦
