### ISSUE TITLE
🐛[BUG] 搜索栏样式错误，希望小版本更新修改

### ISSUE THREAD

**Issue by Wildlifes** [ant-design/pro-table#17]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
1.0.18 版本开始出现样式错误

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
![image](https://user-images.githubusercontent.com/26505011/71101403-9cd10380-21f1-11ea-8f00-4d50f3816ae1.png)

### 🏞 期望结果 [描述你原本期望看到的结果]
![image](https://user-images.githubusercontent.com/26505011/71101428-a8bcc580-21f1-11ea-964e-83bc63776cc4.png)

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
umi  antd pro 模版 更新 pro-table 到最新版本

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0] 最新
- umi 版本  最新
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
@Wildlifes 已经修了，更新一下就好了

**Comment by Wildlifes** [comment]
thx
