### ISSUE TITLE
🐛[BUG] Columns不支持 JSX风格的API

### ISSUE THREAD

**Issue by Nokecy** [ant-design/pro-table#172]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by BugHiding** [comment]
@Nokecy 我也没找到JSX的写法，请问为什么关闭了这个问题，是有JSX的写法么。谢谢

**Comment by Nokecy** [comment]
@BugHiding  自己封一下~~~

**Comment by BugHiding** [comment]
> @BugHiding 自己封一下~~~

好的，谢谢～
