### ISSUE TITLE
👑 [需求].ant-pro-table-toolbar-item { display: inline-flex; }

### ISSUE THREAD

**Issue by axolo** [ant-design/pro-table#173]
### 🥰 需求描述

当`div.ant-pro-table-toolbar-item`包含行内元素时，外层的flex布局不会影响内部，其会在顶部显示。
最典型的为antd的带按钮输入框：`<Input.Search enterButton />`，因其为span元素，所以不会居中显示。

### 🧐 解决方案

`.ant-pro-table-toolbar-item { display: flex; }`
或
`.ant-pro-table-toolbar-item { display: inline-flex; }`

**Comment by chenshuai2144** [comment]
来个pr？

**Comment by axolo** [comment]
> 来个pr？

就一行，下个版本纳入就好。
