### ISSUE TITLE
🧐[问题] 刷新表格, 如何取消选中的 Item

### ISSUE THREAD

**Issue by maybewaityou** [ant-design/pro-table#176]
### 🧐 问题描述
批量选择几个 Item, 访问接口成功后, 刷新表格, 如何取消选中的 Item ?

**Comment by chenshuai2144** [comment]
可以用受控模式，
https://ant.design/components/table-cn/#rowSelection

刷新表格是不是应该取消一下选择

**Comment by erguotou520** [comment]
@chenshuai2144 使用`selectedRowKeys`和`onChange`维护选中项,但是我要做默认全选,所以在request里又设置里`selectedRowKeys`,这又会触发`request`方法,导致无限循环.
