### ISSUE TITLE
🧐[问题]我使用的2.1.3版本，为啥好多bug fix主要在1.x分支上

### ISSUE THREAD

**Issue by aLIEzsss4** [ant-design/pro-table#178]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
@chenshuai2144 @afc163 
目前遇到的问题：https://github.com/ant-design/pro-table/issues/143
修复pr:https://github.com/ant-design/pro-table/commit/c842c474af2f2b42efc0b64c9e245dd28c0e2b5d
确实已修复在1.0.39版本上，但是2.1.3没有修复
期望：在2.xx做修复

**Comment by qindj** [comment]
2.x依赖antd@4，估计改动比较大，大佬刚发了个新版本 https://github.com/ant-design/pro-table/releases/tag/v2.1.4
