### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by liangjingxian** [ant-design/pro-table#179]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
request在页面初始化查询时，params里设置了与formSearch里相同的字段，触发查询时，params的值会一直覆盖formSearch，导致查询的信息错误，请问才能正确设置formSearch里的初始值作用于request

**Comment by chenshuai2144** [comment]
改成不一样的？params 的优先级是比较高的。
你可以给 form 设置默认值，而不是 params 里面设置
