### ISSUE TITLE
🧐[问题] Pro Table 和 umi/hooks 是否重复工作？

### ISSUE THREAD

**Issue by winter-ice** [ant-design/pro-table#180]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
`pro-table`和`umi/hooks`中的`useFormTable`功能上貌似差不多，两者主要有什么异同？需要弄两种不同的方式？

**Comment by chenshuai2144** [comment]
umi/hooks 负责逻辑，pro table 更多的还是 ui
