### ISSUE TITLE
🐛[BUG]pro-table 固定列的问题

### ISSUE THREAD

**Issue by maochongzi** [ant-design/pro-table#183]
### 🐛 bug 描述

通过脚手架创建出来的项目，查询列表固定列位置功能报错： Index 2 of `columns` missing `fixed='right'` prop.

**Comment by maochongzi** [comment]
ok 那我就等着你们解决了

**Comment by encool** [comment]
同等

**Comment by zhangyu1818** [comment]
同等

**Comment by kuckboy1994** [comment]
@chenshuai2144 还有是有这个问题
使用版本 2..4.2

复现地址：https://codesandbox.io/s/nervous-sky-1s7ns

![image](https://user-images.githubusercontent.com/19633245/87109274-cb4e2300-c296-11ea-88f4-d714a05a694b.png)

**Comment by kuckboy1994** [comment]
我的使用场景是想把表格的设置保存到本地 然后每次进来都是一样的设置
