### ISSUE TITLE
当设置props search.collapsed为false时，隐藏collapse功能👑 [需求]

### ISSUE THREAD

**Issue by FengHuangDong** [ant-design/pro-table#186]
当table props search.collapsed:false,设置为false时，是不需要收起展开功能的，但是那个按钮无法通过props隐藏, 配置collapseRender return null 的话箭头还是会展示出来

![image](https://user-images.githubusercontent.com/16097344/75780157-d3043500-5d95-11ea-8694-45e5c7c13479.png)
![image](https://user-images.githubusercontent.com/16097344/75780195-de576080-5d95-11ea-8aa2-4e8061ea5ed1.png)

**Comment by FengHuangDong** [comment]
@chenshuai2144 这个PR啥时候会更新版本？

**Comment by chenshuai2144** [comment]
今天刚发
