### ISSUE TITLE
🧐[问题]如合结合DVA的Status数据呢

### ISSUE THREAD

**Issue by xiaopanghhh** [ant-design/pro-table#187]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
查询返回的结果，存在 DVA MODEL 的 Status 当中，如何直行绑定呢？

**Comment by qindj** [comment]
跟原先的做法一样，connect过来，然后protable用datasource指定（不用request）

**Comment by Orime112** [comment]
> 跟原先的做法一样，connect过来，然后protable用datasource指定（不用request）

如果这样的话，那渲染出来的form点击查询就会无效，怎样可以继续使用form呢？

**Comment by qindj** [comment]
还是和原来一样，你可以自定义查询按钮，发起请求，更新datasource，参考：https://protable.ant.design/search#%E6%93%8D%E4%BD%9C%E6%A0%8F
