### ISSUE TITLE
🧐[问题]关于工具栏自定义搜索 分页值重置问题

### ISSUE THREAD

**Issue by johnnylc** [ant-design/pro-table#191]
pro-table采用request形式请求分页列表，当从自定义工具栏定义的搜索框进行搜索时采用actionRef reload进行更新，但是请求中的分页信息没有重置。
查看pro-table的源码，在search前会执行页码重置的操作
// back first page
action.resetPageIndex();

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
```

<ProTable
          actionRef={ref => this.actionRef = ref}
          scroll={{ x: 'max-content' }}
          columns={columns}
          request={async (params = {}) => {
            const data = await this.fetchData({
              ..._.omit(params, ['current', 'pageSize']),
              name: this.state.name,
              page: params.current,
              per_page: params.pageSize
            })
            return data
          }}
          rowKey={r => r.id}
          search={false}
          toolBarRender={() => [
            <Input.Search placeholder="请输入名称" onSearch={this.onSearch} />,
          ]}
          pagination={{
            showSizeChanger: true,
            showQuickJumper: true
          }}
 />

  onSearch = value => {
    this.setState({ name: value }, () => {
      this.actionRef.reset()
      this.actionRef.reload()
    })
  }

```
示例说明：当前表格所处数据分页为第100页， 当输入名称后点击搜索后调用actionRef的reset() reload()，request发起请求时params中所携带分页信息仍然是第100页。

希望能够获得页码reset的方法，或者自定义搜索的最佳实践，谢谢

**Comment by axolo** [comment]
request的触发机制和params合并算法存在问题，已知params相对复杂的情况下，不会触发request，我已重构为使用dataSource，仅供参考。 #174

**Comment by johnnylc** [comment]
> request的触发机制和params合并算法存在问题，已知params相对复杂的情况下，不会触发request，我已重构为使用dataSource，仅供参考。 #174

谢谢，可能两个问题还不完全一样，我这边是想通过action直接来实现搜索功能，在搜索的时候需要重置请求的分页为1，但是当前情况是通过action的reset + reload执行请求时request中的分页参数仍然是当前分页值。

**Comment by chenshuai2144** [comment]
reset 然后 setTimeOut 一下试试呢，这个可能不是同步的

**Comment by johnnylc** [comment]
> await reset 然后 reload 一下试试呢，这个可能不是同步的

    this.setState({ name: value }, async () => {
      await this.actionRef.reset()
      await this.actionRef.reload()
    })
问题解决，确实是异步的原因，感谢

**Comment by rule78** [comment]
> > await reset 然后 reload 一下试试呢，这个可能不是同步的
> 
> ```
> this.setState({ name: value }, async () => {
>   await this.actionRef.reset()
>   await this.actionRef.reload()
> })
> ```
> 
> 问题解决，确实是异步的原因，感谢
