### ISSUE TITLE
🐛[BUG]表头筛选框不出现“确认”和“重置”按钮

### ISSUE THREAD

**Issue by AndyKong207** [ant-design/pro-table#193]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
同时在一个页面里面使用Pro-table和antd Table，前者无法出现“确认”和“重置”按钮，后者可以正常显示
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
这是Pro Table
![image](https://user-images.githubusercontent.com/30282220/75942543-9b98a400-5ecd-11ea-8963-ea44445f9b47.png)
这是Antd Table
![image](https://user-images.githubusercontent.com/30282220/75942564-aa7f5680-5ecd-11ea-9694-3b162e993328.png)

### 🏞 期望结果 [描述你原本期望看到的结果]
ProTable和Antd Table保持一致
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
```
import React from 'react'
import { Table } from 'antd'
import { PageHeaderWrapper } from '@ant-design/pro-layout'
import ProTable from '@ant-design/pro-table'

const data = [
  {
    key: '1',
    name: 'John Brown',
    age: 32,
    address: 'New York No. 1 Lake Park'
  },
  {
    key: '2',
    name: 'Jim Green',
    age: 42,
    address: 'London No. 1 Lake Park'
  },
  {
    key: '3',
    name: 'Joe Black',
    age: 32,
    address: 'Sidney No. 1 Lake Park'
  },
  {
    key: '4',
    name: 'Jim Red',
    age: 32,
    address: 'London No. 2 Lake Park'
  }
]

const TableList: React.FC = () => {

  const columns = [
  {
    title: 'Name',
    dataIndex: 'name',
    key: 'name',
    filters: [
      { text: 'Joe', value: 'Joe' },
      { text: 'Jim', value: 'Jim' },
    ],
  },
  {
    title: 'Age',
    dataIndex: 'age',
    key: 'age',
  },
  {
    title: 'Address',
    dataIndex: 'address',
    key: 'address',
    filters: [
      { text: 'London', value: 'London' },
      { text: 'New York', value: 'New York' },
    ],
  },
]

  return (
    <PageHeaderWrapper>
      <ProTable headerTitle="我是Pro Table" rowKey="id" dataSource={data} columns={columns} />
      <Table title={() => '我是Antd Tabble'} columns={columns} dataSource={data} />
    </PageHeaderWrapper>
  )
}

export default TableList
```
### © 版本信息
- "@ant-design/pro-table": "2.1.4",
- "antd": "^4.0.0",
- "react": "^16.13.0",
- umi 版本"umi": "^2.8.7",
- 浏览器环境：chrome
- 开发环境 [ mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
<img width="809" alt="28F9C230-D3E6-4505-8215-F90DB628DE0D" src="https://user-images.githubusercontent.com/30282220/75943090-07c7d780-5ecf-11ea-809b-67daaaaa3330.png">
<img width="807" alt="WX20200305-104730@2x" src="https://user-images.githubusercontent.com/30282220/75942988-ccc5a400-5ece-11ea-8e7d-8666d71d6615.png">

**Comment by iambabewin** [comment]
<ProTable locale={{filterConfirm: '确定', filterReset: '重置'}} />

**Comment by iambabewin** [comment]
<ProTable locale={{filterConfirm: 'OK', filterReset: 'Reset'}} />

**Comment by iambabewin** [comment]
> ### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
> 同时在一个页面里面使用Pro-table和antd Table，前者无法出现“确认”和“重置”按钮，后者可以正常显示
> 
> ### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
> 这是Pro Table
> ![image](https://user-images.githubusercontent.com/30282220/75942543-9b98a400-5ecd-11ea-8963-ea44445f9b47.png)
> 这是Antd Table
> ![image](https://user-images.githubusercontent.com/30282220/75942564-aa7f5680-5ecd-11ea-9694-3b162e993328.png)
> 
> ### 🏞 期望结果 [描述你原本期望看到的结果]
> ProTable和Antd Table保持一致
> 
> ### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
> ```
> import React from 'react'
> import { Table } from 'antd'
> import { PageHeaderWrapper } from '@ant-design/pro-layout'
> import ProTable from '@ant-design/pro-table'
> 
> const data = [
>   {
>     key: '1',
>     name: 'John Brown',
>     age: 32,
>     address: 'New York No. 1 Lake Park'
>   },
>   {
>     key: '2',
>     name: 'Jim Green',
>     age: 42,
>     address: 'London No. 1 Lake Park'
>   },
>   {
>     key: '3',
>     name: 'Joe Black',
>     age: 32,
>     address: 'Sidney No. 1 Lake Park'
>   },
>   {
>     key: '4',
>     name: 'Jim Red',
>     age: 32,
>     address: 'London No. 2 Lake Park'
>   }
> ]
> 
> const TableList: React.FC = () => {
> 
>   const columns = [
>   {
>     title: 'Name',
>     dataIndex: 'name',
>     key: 'name',
>     filters: [
>       { text: 'Joe', value: 'Joe' },
>       { text: 'Jim', value: 'Jim' },
>     ],
>   },
>   {
>     title: 'Age',
>     dataIndex: 'age',
>     key: 'age',
>   },
>   {
>     title: 'Address',
>     dataIndex: 'address',
>     key: 'address',
>     filters: [
>       { text: 'London', value: 'London' },
>       { text: 'New York', value: 'New York' },
>     ],
>   },
> ]
> 
>   return (
>     <PageHeaderWrapper>
>       <ProTable headerTitle="我是Pro Table" rowKey="id" dataSource={data} columns={columns} />
>       <Table title={() => '我是Antd Tabble'} columns={columns} dataSource={data} />
>     </PageHeaderWrapper>
>   )
> }
> 
> export default TableList
> ```
> 
> ### © 版本信息
> * "@ant-design/pro-table": "2.1.4",
> * "antd": "^4.0.0",
> * "react": "^16.13.0",
> * umi 版本"umi": "^2.8.7",
> * 浏览器环境：chrome
> * 开发环境 [ mac OS]
> 
> ### 🚑 其他信息 [如截图等其他信息可以贴在这里]
> <img alt="28F9C230-D3E6-4505-8215-F90DB628DE0D" width="809" src="https://user-images.githubusercontent.com/30282220/75943090-07c7d780-5ecf-11ea-809b-67daaaaa3330.png">
> 
> <img alt="WX20200305-104730@2x" width="807" src="https://user-images.githubusercontent.com/30282220/75942988-ccc5a400-5ece-11ea-8e7d-8666d71d6615.png">

<ProTable locale={{filterConfirm: 'OK', filterReset: 'Reset'}} />

**Comment by iambabewin** [comment]
<ProTable locale={{filterConfirm: 'OK', filterReset: 'Reset'}} />
