### ISSUE TITLE
👑 [需求]搜索表单的排序

### ISSUE THREAD

**Issue by heyepeng** [ant-design/pro-table#195]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
目前搜索表单是根据column的的顺序渲染的，希望在column增加一个排序字段，用户控制搜索表单组件的渲染顺序
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
因为希望有“展开”搜索表单的情况下，常用的搜索项放在靠前的位置，但是不希望与表格中column的位置关联。

**Comment by chenshuai2144** [comment]
可以配置 order 来实现

**Comment by heyepeng** [comment]
> 可以配置 order 来实现



> 可以配置 order 来实现

**Comment by heyepeng** [comment]
> 可以配置 order 来实现

还有这种隐藏技能，感谢。

**Comment by Liu-Ya** [comment]
> 可以配置 order 来实现

更新下Readme吧😂
