### ISSUE TITLE
🐛[BUG] 筛选类型为下拉框多选时报错

### ISSUE THREAD

**Issue by jianglin-wu** [ant-design/pro-table#196]
### 筛选类型为下拉框多选时报错

![image](https://user-images.githubusercontent.com/33707642/75984951-56549080-5f26-11ea-86f8-02f11ed53d0f.png)

### 复现方法

配置为下拉框多选： columns 数组其中一列如下配置。

```
   {
      title: '券类型',
      dataIndex: 'couponType',
      filters: false,
      formItemProps: {
        mode: 'multiple',
      },
      valueEnum: {
        test1: {
          text: '兑换券',
        },
        test2: {
          text: '代金券',
        },
        test3: {
          text: '折扣券',
        },
      },
      width: '8%',
    },
```

选择两项，点击右侧查询按钮。

![image](https://user-images.githubusercontent.com/33707642/75984648-c31b5b00-5f25-11ea-872b-af2b1d9d13dd.png)

### 期望结果

期望能够提交选择的两个选项，结果抛出异常。

### © 版本信息

- Ant Design Pro 版本: v4
- umi 版本: 2.13.0+
- 浏览器环境: chrome  80.0.3987.122
- 开发环境 mac OS

**Comment by chenshuai2144** [comment]
升级一下版本，这个 bug 在修复日期类型的时候被顺便修复了
