### ISSUE TITLE
🧐[问题] 表格的column设置属性ellipsis:true，且有枚举的情况下，鼠标hover，title显示原始值

### ISSUE THREAD

**Issue by heyepeng** [ant-design/pro-table#198]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
情况：表格的column设置属性ellipsis:true，且有枚举的情况下，鼠标hover，title显示原始值
期望：显示表格上的完整显示值。
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
const column = [{
      title: formatMessage({ id: 'LABEL.STATUS' }),
      dataIndex: 'roleStatus',
      initialValue: 'all',
      ellipsis:true,
      valueEnum: active,
}],
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
原值为1：已激活  0：未激活
![image](https://user-images.githubusercontent.com/13937417/76067722-d3d1dc80-5fca-11ea-9a82-60d7291c0fc2.png)

**Comment by chenshuai2144** [comment]
非常感谢你的issue，发现了一种新的用法

**Comment by icyes** [comment]
臣附议

**Comment by rabbitlhf** [comment]
臣附议
暂时加了 renderText 处理了，期待官方发版解决
