### ISSUE TITLE
🧐[问题]  如何控制搜索表单 单个搜索框的样式？

### ISSUE THREAD

**Issue by zxj1hao** [ant-design/pro-table#199]

**Comment by chenshuai2144** [comment]
| formItemProps | 查询表单的 props，会透传给表单项 | `{ [prop: string]: any }` | - |

试试这个api

**Comment by zxj1hao** [comment]
> formItemProps

formItemProps 这个值的属性没有找到在哪里，有api地址吗

**Comment by qindj** [comment]
@zxj1hao 多看文档，多看源码，ref https://protable.ant.design/api#columns
