### ISSUE TITLE
👑 [需求]支持拖拽排序

### ISSUE THREAD

**Issue by Wiolem** [ant-design/pro-table#2]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]

业务中一般会有两种拖拽排序或者上移下移，寻求一种简单配置方式

- 本地排序
- 持久化排序，请求

**Comment by chenshuai2144** [comment]
列拖拽还是行？

**Comment by Wiolem** [comment]
行拖拽比较多

**Comment by chenshuai2144** [comment]
行拖拽太难了，会先做列拖拽

**Comment by Amy-Tan** [comment]
> 列拖拽还是行拖拽？

列拖拽的话能拿到拖拽之后的顺序吗?现在需求把拖拽之后的顺序保存到服务器, 但是我没看到相关的API
