### ISSUE TITLE
🐛[BUG] 分页选择页数，params 拿到的 pageSize 还是10

### ISSUE THREAD

**Issue by BangKk** [ant-design/pro-table#20]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
分页选择页数，在 request 里 params 的 pageSize 还是10

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
在 proTable 加上分页配置，如下
```js
{
    pageSizeOptions: ['10', '20', '50', '100'],
    showSizeChanger: true,
    showTotal(total: number) {
      return `共 ${total} 条`;
    }
  }
```
改变页数拿到的params的pageSize没有变更

### 🏞 期望结果 [描述你原本期望看到的结果]
pageSize变更

### © 版本信息

- Ant Design Pro 版本:
- umi 版本 
- 浏览器环境 chrome
- 开发环境 macOS

**Comment by chenshuai2144** [comment]
这个 pr 解决了问题 
https://github.com/ant-design/pro-table/pull/16

**Comment by BangKk** [comment]
好像不在最新的npm包中...没有发release
