### ISSUE TITLE
🐛[BUG]protable中`pagination={{pageSize: 30}}`api无效，无法设置每页展示数据条数

### ISSUE THREAD

**Issue by aiyuchen** [ant-design/pro-table#200]
演示地址：
https://codesandbox.io/s/pro-table-k8g80?fontsize=14&hidenavigation=1&theme=dark
设置每页数据条数无效
```
      pagination={{
        pageSize: 30,
        defaultCurrent: 2
      }}
```
即便是文档提供的演示，这段代码也是无效的
https://codesandbox.io/embed/dreamy-river-q7v6s?fontsize=14&hidenavigation=1&theme=dark&view=preview
```
      pagination={{
        defaultCurrent: 10
      }}
```

**Comment by chenshuai2144** [comment]
你使用的是1.x 的版本吗？

**Comment by lancelot1025** [comment]
试了一下，request的时候 取值时取了defaultPageSize的值。

**Comment by chenshuai2144** [comment]
应该pageSize  的优先级更高
