### ISSUE TITLE
🐛[BUG] 针对枚举类型，编辑时下拉框显示的是value值

### ISSUE THREAD

**Issue by beeant0512** [ant-design/pro-table#201]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
使用protable，编辑时的模态框中，dropdown select显示的是值 不是对应的valueEnum 的 text
![bug01](https://user-images.githubusercontent.com/6050235/76137800-e526f180-607b-11ea-84e4-67da90430218.png)
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
```
{
      title: '类型',
      dataIndex: 'itemType',
      sorter: true,
      copyable: true,
      valueEnum: {
        0: {
          text: '车系',
        },
        1: {
          text: '车型',
        },
        2: {
          text: '配置',
        },
      },
      rules,
    },

```
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
<UpdateForm
          onSubmit={async value => {
            const success = await handleUpdate(value);

            if (success) {
              handleUpdateModalVisible(false);
              setManageFormValues({});

              if (actionRef.current) {
                actionRef.current.reload();
              }
            }
          }}
          onCancel={() => {
            handleUpdateModalVisible(false);
            setManageFormValues({});
          }}
          updateModalVisible={updateModalVisible}
          values={manageFormValues}
        >
          <ProTable
            onSubmit={async value => {
              const success = await handleUpdate({ ...value, configId: manageFormValues.configId });

              if (success) {
                handleUpdateModalVisible(false);

                if (actionRef.current) {
                  actionRef.current.reload();
                }
              }
            }}
            form={{
              labelCol: { span: 10 },
              initialValues: manageFormValues,
            }}
            rowKey="key"
            type="form"
            columns={columns}
            rowSelection={{}}
          />
        </UpdateForm>
### © 版本信息

- protable  2.1.4

**Comment by chenshuai2144** [comment]
最好是不要用数字当 key， 组件的处理可能会有问题，比如  0 和 "0" 是不同的，如果不特殊转化匹配不上，建议你改成 {"0":"车系"}

**Comment by CGodX** [comment]
遇到的同样的问题
```jsx
export const SEX: valueEnum = {
  '0': '女',
  '1': '男',
};
//
{
  title: '性别',
  dataIndex: 'sex',
  sorter: true,
  valueEnum: SEX,
  renderFormItem: (item, { value, onChange }, form) => (
    <Radio.Group value={value} onChange={onChange}>
      {Object.keys(SEX).map((key) => (
        <Radio key={key} value={key}>
          {SEX[key].text}
        </Radio>
      ))}
    </Radio.Group>
  ),
},
```
```jsx
// 在 renderFormItem 写死了都选不中
renderFormItem: (item, { value, onChange }, form) => (
  <Radio.Group value="1">
    <Radio value="1">男</Radio>
    <Radio value="0">女</Radio>
  </Radio.Group>
),
```

**Comment by AmberJyh** [comment]
如果我显示需要name，但是查询的时候需要取id做查询。以下写法能实现这种操作，但是这样导致的问题就是table做过滤的时候无效。只有valueEnum的key和text一致时，才能过滤。
`{
      title: '所属类目',
      dataIndex: 'CName',
      initialValue: '',
      valueEnum: filterCategory(), 
    },`
`const filterCategory = () => {
    const arrayItem = {};
    for (var i in categoryData) {
      arrayItem[`${categoryData[i].Cid}`] = {
        text: `${categoryData[i].CName}`,
      
      };
    }
    return arrayItem;
  };`

**Comment by ShawLyon** [comment]
```
    {
      title: '状态',
      dataIndex: 'project_status',
      hideInSearch: true,
      rules: [{ required: true }],
      valueEnum: {
        0: { text: '已完成', status: 'Default' },
        1: { text: '进行中', status: 'Processing' },
        2: { text: '已创建', status: 'Success' },
      },
      renderFormItem: (item, { defaultRender, ...rest }, form) => {
        const v_status = modalType === 'add' ? status : editData.project_status;
        if (modalType === 'edit') {
          setStatus(editData.project_status);
        }
        let statusItem;
        switch (v_status) {
          case 0:
            statusItem = '已完成';
            break;
          case 1:
            statusItem = '进行中';
            break;
          case 2:
            statusItem = '已创建';
            break;

          default:
            break;
        }
        // 手动设置校验
        form.setFieldsValue({ project_status: v_status });
        return (
          <Select defaultValue={statusItem} onChange={onStatusChange}>
            <Select.Option value={0}>已完成</Select.Option>
            <Select.Option value={1}>进行中</Select.Option>
            <Select.Option value={2}>已创建</Select.Option>
          </Select>
        );
      },
    },
```
这是我实现的方式，但是很不优雅，希望能修复这个bug

**Comment by rabbitlhf** [comment]
就是 类型不匹配导致，但是另外有个问题就是 列表展示 valueEnum 字段 鼠标放上去 提示文字仍旧是 key 不是 text
