### ISSUE TITLE
🐛[BUG] 国际化问题 分页组件总是英语

### ISSUE THREAD

**Issue by mrzzcn** [ant-design/pro-table#204]
### © 版本信息

- Ant Design Pro 版本: 直接使用 ant-design/pro-table
- umi 版本：无
- 浏览器环境：chrome
- 开发环境 Mac

**Comment by chenshuai2144** [comment]
是因为没有配置，如果你使用的是umi 的插件会自动配置，如果不是就需要你手动配置 ConfigProvider  了

**Comment by mrzzcn** [comment]
> 是因为没有配置，如果你使用的是umi 的插件会自动配置，如果不是就需要你手动配置 ConfigProvider 了

但是我没有使用 umi 啊，直接用就不能配置语言了？

**Comment by chenshuai2144** [comment]
可以用这个 https://ant.design/components/config-provider-cn/

**Comment by darkmice** [comment]
@chenshuai2144 

> 可以用这个 https://ant.design/components/config-provider-cn/

用这个也不能生效，应该是   
https://github.com/ant-design/pro-table/blob/11c3709c7239ad0680537c04f6ff403848587d36/src/Table.tsx#L894-L898
这里定义了，所以外面定义的传不进来
