### ISSUE TITLE
🧐[问题] Columns这个属性可以支持动态渲染吗？

### ISSUE THREAD

**Issue by wscart** [ant-design/pro-table#206]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
在proTable配合DVA的时候请求拿到了后台表格字段再次处理自定义columns动态渲染，但是console还是报错了,好像是只支持静态渲染。

另外有一个现象：
开始刷新页面的时候都会报错，但是在不刷新并且修改代码的时候自动触发更新机制，也没报错，出来动态渲染的结果是没毛病的。

如果你们和我遇到这个问题一样的话，能不能提供这个解决方法给我参考一下，谢谢合作。

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
```javascript
    const { dispatch, location, match, table, loading } = props;
    const { tableData, tableColumn } = table;
    const { query } = location;
    useEffect(() => {
        const { query } = location;
        const { table } = match.params;
        const payload = {
            tableName: table,
            query
        }
        dispatch({
            type: 'table/fetchTable',
            payload
        });
    }, []);
    let columns: ProColumns<TableListItem>[] = [];
    if(tableColumn && tableColumn.field) ... columns =  tableColumn.field.map(...)
```

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![Image of Yaktocat](http://qinin.iut8.cn/1583662261736.jpg)

**Comment by chenshuai2144** [comment]
更新一下版本，这个好像是原来的一个bug

**Comment by wscart** [comment]
> 更新一下版本，这个好像是原来的一个bug

目前版本是2.1.4

**Comment by chenshuai2144** [comment]
能来个重现吗？这个 warning 报错是因为修改了 useEffect 的 effect 数组长度导致的。
 看了一下代码里好像没有相关的错误

**Comment by chenshuai2144** [comment]
重现了，明天会发个新版本。

**Comment by wscart** [comment]
> 重现了，明天会发个新版本。非常感谢你的issue，因为动态的人不多这个bug 一直没被发现

你能发现了这个问题实在太好，非常感谢你

**Comment by wscart** [comment]
> 重现了，明天会发个新版本。非常感谢你的issue，因为动态的人不多这个bug 一直没被发现

升级版本为2.1.5，还是重现了这个问题。
排除问题以下：
1、columns与dataSource指定数量是相同的也会报错
2、函数组件渲染：在类组件层上做columns动态数据处理，再次渲染ProTable函数组件也报错

最后应该是ProTable调用useEffect的问题

**Comment by wscart** [comment]
2.1.6也会重现这个问题，主要问题是useEffect
在函数组件层上采用防止重复渲染的解决方案，但是根据同样的路由规则而且不同数据的情况，还会报错。

**Comment by Gzbox** [comment]
同上2.1.6也会重现这个问题

**Comment by chenshuai2144** [comment]
不只一个地方，我又修了一下

**Comment by wscart** [comment]
@chenshuai2144 辛苦了你 谢谢
