### ISSUE TITLE
🐛[BUG]pro-table 在设置size的情况下，工具栏调整密度失败

### ISSUE THREAD

**Issue by Lanboo** [ant-design/pro-table#207]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
pro-table 的size属性设置small后，工具栏的密度按钮不能调整表格的密度了

### © 版本信息

- Ant Design Pro 版本:4.0.0
- umi 版本 2.13.0
- 浏览器环境 Chrome
- 开发环境 Windows64

**Comment by l745230** [comment]
同样问题+1

**Comment by chenshuai2144** [comment]
size 是受控模式，需要和 onSizeChange 配合使用。

**Comment by Lanboo** [comment]
不行啊
```
// 常量值
const tableState = {
    size: 'small' as SizeType,
    deleteBtnDisabled: true,
};

// ProTable属性设置
size={tableState.size}
onSizeChange={(size) => {
    tableState.size = size;
    console.log(tableState.size);
}}
```

打印是有对应值的，但是表格的密度确实没有变化的

**Comment by kaoding** [comment]
> 不行啊
> 
> ```
> // 常量值
> const tableState = {
>     size: 'small' as SizeType,
>     deleteBtnDisabled: true,
> };
> 
> // ProTable属性设置
> size={tableState.size}
> onSizeChange={(size) => {
>     tableState.size = size;
>     console.log(tableState.size);
> }}
> ```
> 
> 打印是有对应值的，但是表格的密度确实没有变化的
```
// 使用状态值
const [size,setSize]=useState('small');
// ProTable属性设置
size={size}
onSizeChange={size=>setSize(size)}

```

**Comment by Lanboo** [comment]
> ```
> // 使用状态值
> const [size,setSize]=useState('small');
> // ProTable属性设置
> size={size}
> onSizeChange={size=>setSize(size)}
> ```
漂亮！！
```
// 使用状态值
const [size, setSize] = useState<SizeType>('small');

// ProTable属性设置
size={size}
onSizeChange={size=>setSize(size)}
```
