### ISSUE TITLE
🐛[BUG] Passing columns as Boolean causes a react exception 

### ISSUE THREAD

**Issue by maurodelazeri** [ant-design/pro-table#210]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

Passing this columns to a modal for example

```
  const columns: ProColumns<TableListItem>[] = [
    {
      title: 'Currency',
      dataIndex: 'currency',
      valueType: 'text',
      sorter: true,
      rules: [
        {
          required: true,
          message: 'Currency name is required',
        },
      ],
    },
```
```
arning: Received `true` for a non-boolean attribute `sorter`.

If you want to write it to the DOM, pass a string instead: sorter="true" or sorter={value.toString()}.
```

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
It can be tested using https://preview.pro.ant.design/list/table-list adding a `sorter: true` to  `Rule name`

### 🏞 期望结果 [描述你原本期望看到的结果]
no exception 

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0] latest
- umi 版本 latest
- 浏览器环境 latest
- 开发环境 [e.g. mac OS] Linux

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![alt text](http://i.imgur.com/tFXPkQ3.png))

**Comment by chenshuai2144** [comment]
fixed， sorry  i not see this isse

**Comment by caijiang** [comment]
type为form的`ProTable`,应用包含布尔类型的sorter的 column 依然会报警告。

> devScripts.js:5035 Warning: Received `true` for a non-boolean attribute `sorter`.
>
> If you want to write it to the DOM, pass a string instead: sorter="true" or sorter={value.toString()}.

现在用的解决方案是在渲染form`ProTable`的时候，手动调整columns.

### © 版本信息
* Pro-Table: 2.2.5
* umi 版本 3.1.2
* 浏览器环境 Chrome: 81.0.4044.113 (Official Build) (64-bit)
* 开发环境 mac

**Comment by ChenWeihua123** [comment]
同样的问题 type 为 form 删掉所有sorter属性 就不会报错 很头痛
