### ISSUE TITLE
🐛[BUG]request和scroll一起使用时会出现无数据的情况

### ISSUE THREAD

**Issue by johnnylc** [ant-design/pro-table#212]
当table采用request的方式获取数据时，如果配置了scroll属性，则列表出现“暂无数据提示”。

表单过长需要配置scroll属性，采用 https://ant-design.gitee.io/components/table-cn/#components-table-demo-fixed-columns 中的示例，进行测试。
测试分以下三种情况：
1. request传入数据同时设置scroll，显示no data
2. request传入数据不设置scroll，数据可显示但无scroll
3. dataSource传入数据并设置scroll，正确显示数据及scroll

### 🏞 期望结果 
使用request传入数据，并设置scroll属性时能够和antd table一样正常显示。

### 💻 复现代码
以下为代码示例：
https://codesandbox.io/s/dumi-demo-lfw0o

代码示例中包含以上三类情况，以及antd table的正确展示。

### © 版本信息

- Ant Design Pro-Table 版本: 2.1.6
- umi 版本  使用CRA + customize-cra
- 浏览器环境 Chrome 80.0.3987.122
- 开发环境 Mac

![image](https://user-images.githubusercontent.com/12717523/76218251-de040d00-624e-11ea-9bc0-4e305a9a6f69.png)

**Comment by chenshuai2144** [comment]
是 rc-table 的 bug，尝试重新安装一下依赖
