### ISSUE TITLE
🧐[问题]optionRender失效

### ISSUE THREAD

**Issue by 363676727** [ant-design/pro-table#213]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
search参数里的optionRender失效:
1.git clone pro-table2.1.6代码
2.yarn start,并在pro-table/docs/example/dataSource.tsx，
文件加了optionRender
3.本地打开optionRender有效
4.打开左下角codesandbox显示该段dataSource.tsx，optionRender却失效
https://codesandbox.io/s/dumi-demo-365gr
5.Ant Design Pro4.0 升级pro-table2.1.6, 将上面代码拷贝进去，yarn start结果optionRender也是失效
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
https://codesandbox.io/s/dumi-demo-365gr
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
pro-table2.1.6, 请问是我遗漏了什么吗

**Comment by 363676727** [comment]
已经找到问题

**Comment by chenshuai2144** [comment]
什么问题可以说出来让大家都学习一下
