### ISSUE TITLE
👑 [需求]

### ISSUE THREAD

**Issue by 363676727** [ant-design/pro-table#214]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
需求: 希望增加清空FormSeacrh全部formItem里的值的方式，重置按钮并不是我需要的，他只是还原了initialValues, 增加清空全部formItem的回调

场景: 我将search内容拼接到了url上，当用户刷新时, initialValues初始化保留的搜索条件, 但是当我想清空所有条件时，查看源码，并没发现合适回调方法。
而重置的按钮只会还原initialValues的值，并不会清空

### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
1.为了实现清空，我利用optionRender重新定制了搜索，重置 位置的按钮，formRef.current.setFieldsValue方法清空(全部设置成undefined),却发现date类型的输入框异常,formRef.current.getFieldsValue()得到的虽然全部是undefined,但是界面上还是显示之前的日期,
最后发现设置成null才有效。
https://codesandbox.io/s/dumi-demo-0x8l6

2.我将initialValues存与state, 清空时改变state里的initialValues, 然后利用formRef.current.resetFields()去清空，就避免了类似date类型无法清空

3.增加清空按钮。
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
在业务场景了里清空的需求还是蛮多的。如果要自己设置清空，像date类型的组件还需要自己判别是设置成null还是undefined, 还要定制optionRender, 是不是能简化下这个步骤。

**Comment by chenshuai2144** [comment]
使用 `formRef`，然后` form.setFieldValues({})`
