### ISSUE TITLE
🐛[BUG]当ProTable的size设置成small时，固定列的表头的background会变成transparent

### ISSUE THREAD

**Issue by Mu-xue** [ant-design/pro-table#218]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
当ProTable的size设置成small时，固定列的表头background会变成transparent

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
当表格宽度较大时，显示出固定列，切换密度就可以复现

### 🏞 期望结果 [描述你原本期望看到的结果]
不应该透明

### © 版本信息

- Ant Design Pro Table版本: [2.1.6]
- 浏览器环境 [Chrome]
- 开发环境 [mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![image](https://user-images.githubusercontent.com/26177732/76398870-99948080-63b8-11ea-826d-4c9be2f7c0f2.png)
![image](https://user-images.githubusercontent.com/26177732/76398903-a7e29c80-63b8-11ea-818e-7e94a4824f7e.png)

**Comment by chenshuai2144** [comment]
这是 antd 的设计

**Comment by Mu-xue** [comment]
感觉不太合理呀😅
