### ISSUE TITLE
🧐[问题]通过renderFormItem指定输入组件后，点击搜索表单“重置”按钮，不会清空数据

### ISSUE THREAD

**Issue by wital** [ant-design/pro-table#22]
### 🧐 问题描述
搜索框指定了输入组件后，点击搜索框的“重置”按钮，自动生成的输入组件正常清除了数据，通过renderFormItem指定的输入组件数据没有清除。
### 💻 示例代码
{
      title: '上次调用时间',
      dataIndex: 'lastCallTime',
      sorter: true,
      valueType: 'dateTime',
      renderFormItem: (_, props) => &lt;RangePicker onChange={props.onChange}/>,
    },
### 🚑 其他信息 
无

**Comment by BangKk** [comment]
这样：{...props}
你没传value

**Comment by wital** [comment]
> 这样：{...props}
> 你没传value

不好意思能完整的写下正确的方式么，JAVA程序员学习antd pro的第一周，有点不理解

**Comment by fanqisoft** [comment]
{
      
      title: '项目时间',
      dataIndex: 'project_date',
      hideInTable:true,
      valueType:'text',
      renderFormItem:(item,props) => 
        <RangePicker
          defaultValue={[moment(new Date(2020,0), dateFormat), moment(new Date(2020,1), dateFormat)]}
          format={dateFormat} onChange = { (a,b) => {
            props.onChange(b[0]);
          }}
        />
    },
