### ISSUE TITLE
👑 [需求]自定义搜索模块的时候需要重置页码为1，能否暴露action.resetPageIndex Api

### ISSUE THREAD

**Issue by rule78** [ant-design/pro-table#220]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
自定义搜索模块的时候需要重置页码为1，能否暴露action.resetPageIndex Api

### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
1. 页码可控，直接暴露设置页码api
2.actionRef.current.reset 可以重置页码

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/20340590/76481369-4409b380-644c-11ea-962c-396a0c177606.png)

**Comment by rule78** [comment]
![image](https://user-images.githubusercontent.com/20340590/76481475-92b74d80-644c-11ea-9331-86d0e3f51730.png)

**Comment by johnnylc** [comment]
https://github.com/ant-design/pro-table/issues/191

**Comment by chenshuai2144** [comment]
推荐使用受控模式，而不是操作式的 api
