### ISSUE TITLE
🐛[BUG]初次加载表格查询initialValue值的没有应用到request的中

### ISSUE THREAD

**Issue by fisher-zwl** [ant-design/pro-table#221]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
页面第一次进来初次查询的时候，initialValue的值没有应用到request中
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
给某个表单项设置initialValue，然后看初次查询的参数即可
### 🏞 期望结果 [描述你原本期望看到的结果]
如果有initialValue的值，期望初次查询能应用到request
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
columns中的代码：
{
      title: '询价主题',
      dataIndex: 'name',
      initialValue: '4564',
    },
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by qindj** [comment]
#134
