### ISSUE TITLE
👑 [需求] 新建菜单行，能否选择放在search栏的上方？

### ISSUE THREAD

**Issue by fangaofeng** [ant-design/pro-table#225]
### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
![无标题](https://user-images.githubusercontent.com/15919475/76679116-baf3a780-6618-11ea-9f6c-24c2e8da8e40.png)

**Comment by chenshuai2144** [comment]
现在不支持这种行为，你可以隐藏操作栏，然后自己控制样式
