### ISSUE TITLE
👑 [需求] 列展示配置增加disabled属性

### ISSUE THREAD

**Issue by hcxw11** [ant-design/pro-table#226]
### 🥰 需求描述
业务上的需求，部分列必须显示在表格内，但是因为options中的数据源是columnsMap，直接修改show:false配置会影响表格渲染

### 🧐 解决方案
在这里增加一个disabled的配置
https://github.com/ant-design/pro-table/blob/c027fc5e8e90406a3ff5e80353a85ba08758dcd8/src/component/columnSetting/index.tsx#L77

### 🚑 其他信息
<img width="150" src="https://user-images.githubusercontent.com/16369309/76687730-b2738f00-6661-11ea-88e0-b6330fd3edf2.png"/>

**Comment by chenshuai2144** [comment]
https://protable.ant.design/example#%E5%8F%97%E6%8E%A7%E6%A8%A1%E5%BC%8F
试试这个受控模式
