### ISSUE TITLE
🧐[问题]pro-table导致menu中Link包裹的icon与label紧贴

### ISSUE THREAD

**Issue by johnnylc** [ant-design/pro-table#228]
### 🧐 问题描述
之前在pro-layout中提问，关于侧边栏menu使用Link组件导致icon与label之间margin消失的问题。
现在更新antd 4.0.3后页面，直接进入页面时，展示没有问题
![image](https://user-images.githubusercontent.com/12717523/76720469-dfb26100-6777-11ea-9df0-97c7464cc32f.png)

但是当跳转路由后，页面中报含pro-table组件时，问题再次出现
![image](https://user-images.githubusercontent.com/12717523/76720568-24d69300-6778-11ea-9f61-dc61d9f994b0.png)

在未打开包含pro-table组件页面之前，icon的样式为
![image](https://user-images.githubusercontent.com/12717523/76720662-68c99800-6778-11ea-89f6-627dad88b244.png)

当打开包含pro-table组件页面之后，icon的样式为
![image](https://user-images.githubusercontent.com/12717523/76720816-d7a6f100-6778-11ea-8f5c-aa5aef066f01.png)

### 🚑 其他信息
antd 4.0.3
pro-table 2.1.7
pro-layout 5.0.6
Chrome 80.0.3987.132

**Comment by qindj** [comment]
ant-design/ant-design-pro#6106

**Comment by johnnylc** [comment]
> [ant-design/ant-design-pro#6106](https://github.com/ant-design/ant-design-pro/issues/6106)

谢谢，之前有提过这个问题，现在的情况是pro-layout单独使用时问题已修复， 但是当渲染了包含pro-table的页面后问题复现。

**Comment by johnnylc** [comment]
已找到原因，在pro-table内部的的node_module下存在antd 4.0.2，  删除yarn.lock重新安装依赖解决。
