### ISSUE TITLE
👑 [需求]增加搜索模块自定义功能

### ISSUE THREAD

**Issue by s464446877** [ant-design/pro-table#230]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
搜索区域支持自定义，不如是输入框还是时间区间选择器还是多层级选择器等等，现在只是根据表格的列来创建搜索项目及搜索的类型是输入框还是时间，现在有业务需求是时间选择器是区间选择器

**Comment by TuskiEnd** [comment]
我也遇到过这种需求，可以增加columns多配置一个字段，valueType为dateTime，同时hideInTable hideInForm都设置为true就搞定啦

**Comment by s464446877** [comment]
> 配置

那个只是时间选择器，现在需求是时间区间选择，选择的是一段时间，还有就是有些选择框需要多层级的选择

**Comment by ShengGuoZhou** [comment]
请问，搜索里的层级选择解决了吗？select 下拉选层级。
比如：城市联动的选择
