### ISSUE TITLE
使用request请求数据源时，设置某一列的sorter为true，如何触发request携带排序参数，进行服务端排序？

### ISSUE THREAD

**Issue by YIXIANG0234** [ant-design/pro-table#233]
貌似点击设置了排序的那一列的排序按钮之后，不会触发request，只会触发table的onchange事件，如果要使用onchange发请求进行服务端排序的话该怎么坐，或者有什么好的建议吗？

**Comment by chenshuai2144** [comment]
pro 里 提供了一个，你看看
https://github.com/ant-design/ant-design-pro/tree/06dd7fa6216860344e04a02d22af6efe33defa21/src/pages/ListTableList

**Comment by yeluoqiuzhi** [comment]
卧槽，居然藏了一个，demo没演示的

**Comment by wgytcdx** [comment]
chenshuai2144 提供的方案 验证可用，自己实现了个类似的sorter，但会跟分页逻辑冲突...还是直接拿来用吧 /狗头
