### ISSUE TITLE
👑 [需求]fullscreen

### ISSUE THREAD

**Issue by chemieliu** [ant-design/pro-table#234]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
fullscreen可以出个包或者插件吗,你们的方案非常好，没有报错也没有需要点击两次生效。@alitajs/antd-plus用在antdpro中会出现点击两次才生效有时候会出现ResizeObserverContent错误

**Comment by chenshuai2144** [comment]
这个用的原生的 api。
https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API
直接看这个就好了
