### ISSUE TITLE
👑 [需求] 在toolBarRender的Button可以获取到搜索表单的数据，用来在下载表格时筛选

### ISSUE THREAD

**Issue by KoalaHui** [ant-design/pro-table#235]
🥰 需求描述 [详细地描述需求，让大家都能理解]
在toolBarRender的Button可以获取到搜索表单的数据，用来在下载表格时筛选

🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
目前的做法是在需要筛选的数据columns中添加renderFormItem，通过onchange事件将数据放到state中，筛选的功能是实现了，现在就是获取不到onReset事件，在重置的时候不能清空state数据

🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/14347613/76952967-e47a3f00-6948-11ea-993e-a35dd35d72ee.png)
![image](https://user-images.githubusercontent.com/14347613/76953012-f4921e80-6948-11ea-9c73-214968048d0c.png)

**Comment by fangzhengjin** [comment]
ProTable有一个formRef参数，虽然文档上没写~
```js
const formRef = useRef<FormInstance>();
<ProTable<any>
  formRef={formRef}
/>
```

**Comment by KoalaHui** [comment]
https://github.com/ant-design/pro-table/issues/235#issuecomment-601055369

> ProTable有一个formRef参数，虽然文档上没写~
> 
> ```js
> const formRef = useRef<FormInstance>();
> <ProTable<any>
>   formRef={formRef}
> />
> ```

成功解决了，谢谢

**Comment by fangzhengjin** [comment]
@KoalaHui 把这个issues关了吧
