### ISSUE TITLE
🧐[问题]type='form' 的ProTable控件，“编辑”类操作时，如何将选中的记录值填到Modal里面的form表单中?

### ISSUE THREAD

**Issue by fanyawei** [ant-design/pro-table#238]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
管理系统中，经常用到弹窗新增数据和弹窗编辑数据的情况，新建一个Modal对话框，里面放入type='form'  的ProTable控件，当点击“编辑”类的操作按钮时，需要将选中的记录值默认填到对话框里面的form表单中，该如何操作？如何设置某列只读不可更改？
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
            <Modal
                destroyOnClose
                title={formData ? '编辑' : '新增'}
                visible={modalVisible}
                onCancel={() => setModalVisible(false)}
                footer={null}
            >
                <ProTable<DataItem, DataItem>
                    rowKey="id"
                    type="form"
                    columns={columns}
                    onSubmit={async value => {
                        if (await handleAdd(value)) {
                            setModalVisible(false)
                            if (actionRef.current) {
                                actionRef.current.reload()
                            }
                        }
                    }}
                />
            </Modal>

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/8381679/77001808-7c057f00-6995-11ea-8ada-0f60faf5e969.png)
![image](https://user-images.githubusercontent.com/8381679/77002792-0e5a5280-6997-11ea-917c-137cc4c1dbe2.png)

**Comment by chenshuai2144** [comment]
文档没写全，你可以在 `form={{ initialValues:{} }}`来设置默认值，或者用 fromRef 来 setFiled

**Comment by chenchen0501** [comment]
> 文档没写全，你可以在 `form={{ initialValues:{} }}`来设置默认值，或者用 fromRef 来 setFiled

在Modal中，我写了ProTable，且按照上述方法加了默认值，但是在我打开Modal，第一次的request中并没有带这个参数，但是点击查询和重置是可以带的，你看下这是这个bug吗，求回复解决，谢谢啦！

**Comment by chenyu1990** [comment]
> 文档没写全，你可以在 `form={{ initialValues:{} }}`来设置默认值，或者用 fromRef 来 setFiled

```
valueEnum: {
        false: {
          text: '允许',
          status: 'Success',
        },
        true: {
          text: '禁止',
          status: 'Error',
        },
      },
```
选择类型的，无法正常设置默认值

**Comment by thetiss** [comment]
> > 文档没写全，你可以在 `form={{ initialValues:{} }}`来设置默认值，或者用 fromRef 来 setFiled
> 
> 在Modal中，我写了ProTable，且按照上述方法加了默认值，但是在我打开Modal，第一次的request中并没有带这个参数，但是点击查询和重置是可以带的，你看下这是这个bug吗，求回复解决，谢谢啦！
请问这个问题有新的解决方案吗，

> > 文档没写全，你可以在 `form={{ initialValues:{} }}`来设置默认值，或者用 fromRef 来 setFiled
> 
> 在Modal中，我写了ProTable，且按照上述方法加了默认值，但是在我打开Modal，第一次的request中并没有带这个参数，但是点击查询和重置是可以带的，你看下这是这个bug吗，求回复解决，谢谢啦！

请问bug有解决方案吗

**Comment by chenshuai2144** [comment]
object 只能用 stirng 当 key
