### ISSUE TITLE
🐛[BUG]protable好像不支持`filterIcon`

### ISSUE THREAD

**Issue by aiyuchen** [ant-design/pro-table#240]
直接fork官方例子，在`column`中加了一句代码
```
filterIcon: filtered => <SearchOutlined style={{ color: filtered ? '#1890ff' : undefined }} />,
```
https://codesandbox.io/s/dumi-demo-26wij?fontsize=14&hidenavigation=1&theme=dark

### © 版本信息

- Ant Design Protable 版本: [e.g. 2.1.7]
- Ant Design 版本: [e.g. 4.0.3]
- 开发环境 [e.g. mac OS]

**Comment by qindj** [comment]
亲测不是bug，你的demo里只加了filterIcon，是不会显示图标的，好好看看antd的文档
https://ant.design/components/table-cn/#components-table-demo-custom-filter-panel
