### ISSUE TITLE
🧐怎么自主触发request重新请求数据？

### ISSUE THREAD

**Issue by MyPacker** [ant-design/pro-table#243]
### 🧐 问题描述 
怎么自主触发request重新请求数据？我尝试了action.reload()和action. fetchMore()可以触发重新请求，但是不能传参数，应该怎么做呢？还是说这种场景下只能用DataSource模式？

**Comment by qindj** [comment]
类似的问题不少了，issues里搜一下吧。。。

**Comment by chenshuai2144** [comment]
action.reload() 会继续使用原来的参数的。
参数是根据 params 生成的，你应该修改 params 来触发重新查询
