### ISSUE TITLE
🧐[问题] How to change the currency for valueType "money"

### ISSUE THREAD

**Issue by kkcy** [ant-design/pro-table#250]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
May I know if it is possible to change the currency from the default "¥" to other currencies? I've wrapped the table in IntlProvider but only language is changed.

**Comment by qindj** [comment]
try:

`const columns = {
  title: 'Money',
  key: 'money',
  dataIndex: 'money',
  valueType: (item) => ({
    type: 'money',
    locale: 'en-Us'
  }),
};`

**Comment by kkcy** [comment]
It works, thanks!
```
valueType: (item) => ({
    type: 'money',
    locale: 'en_US'
}),
```
However it seems like only a few locales were supported.
Out of the few I've tested, only `en_US` & `ru_RU` changes currency. 
Any idea how to import the currency of the other locales, particularly `ms_MY` for me.

In the meantime I'm using 
```
renderText: text => {
    return `MYR ${text}`
}
```
and it works just fine too.

**Comment by qindj** [comment]
pls send us a pr to add new locale such as https://github.com/ant-design/pro-table/pull/216

@chenshuai2144 越俎代庖了

**Comment by kkcy** [comment]
I see, cool! Thanks!
