### ISSUE TITLE
🧐[问题]  Is it possible to add the locale pt-BR to the pro-table?

### ISSUE THREAD

**Issue by gislenescarvalho** [ant-design/pro-table#251]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

I have an application with many table and filters when the placeholder is in english, but the customer ask about to change for portuguese in pt-BR.
Is it possible to customize the internationalization/locale of the pro-table for pt-BR?

**Comment by qindj** [comment]
You may change the title property of columns from English to Portuguese.

Some examples here: https://protable.ant.design/example#italiano

**Comment by qindj** [comment]
I made a mistake, we didn't have locale for pt-BR yet , PR please~

**Comment by chenshuai2144** [comment]
const enLocale = {
  tableFrom: {
    search: 'Query',
    reset: 'Reset',
    submit: 'Submit',
    collapsed: 'Expand',
    expand: 'Collapse',
    inputPlaceholder: 'Please enter',
    selectPlaceholder: 'Please select',
  },
  alert: {
    clear: 'Clear',
  },
  tableToolBar: {
    leftPin: 'Pin to left',
    rightPin: 'Pin to right',
    noPin: 'Unpinned',
    leftFixedTitle: 'Fixed the left',
    rightFixedTitle: 'Fixed the right',
    noFixedTitle: 'Not Fixed',
    reset: 'Reset',
    columnDisplay: 'Column Display',
    columnSetting: 'Settings',
    fullScreen: 'Full Screen',
    exitFullScreen: 'Exit Full Screen',
    reload: 'Refresh',
    density: 'Density',
    densityDefault: 'Default',
    densityLarger: 'Larger',
    densityMiddle: 'Middle',
    densitySmall: 'Compact',
  },
};

// gen intl
const enUSIntl = createIntl('en_US', enUS);

// Use
<IntlProvider value={enUSIntl}>
  <ProTable />
</IntlProvider>;

**Comment by gislenescarvalho** [comment]
Perfect! Works fine here.
Thanks @chenshuai2144 for the help. :)
