### ISSUE TITLE
筛选表单中如何添加级联选择

### ISSUE THREAD

**Issue by ty888** [ant-design/pro-table#252]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
筛选表单中如何添加级联选择
### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![image](https://user-images.githubusercontent.com/19710589/77606896-b6ea5280-6f53-11ea-9c55-8b5cd2ab9d3a.png)

**Comment by chenshuai2144** [comment]
可以使用 renderItem 来实现

```
 {
      title: '一级类目',
      dataIndex: 'firstCategory',
      renderFormItem: (item, props) => (
        <CategorySelect projectID={projectId} categoryType="0" {...props} />
      ),
    },
```

**Comment by ty888** [comment]
@chenshuai2144 哇哦，还是我文档没看仔细，完美解决了，谢谢谢谢🙏。
