### ISSUE TITLE
🧐[问题] 和DVA结合，刷新按钮如何重写，全屏后 Drawer 弹不出来

### ISSUE THREAD

**Issue by xiaopanghhh** [ant-design/pro-table#253]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

和DVA结合，右边的刷新按钮如何重写。
另外，全屏后 Drawer 弹不出来。

**Comment by qindj** [comment]
ref: https://github.com/ant-design/pro-table/issues/187

**Comment by xiaopanghhh** [comment]
不一样的，是这一块儿的。
![image](https://user-images.githubusercontent.com/24469601/77637944-6560b880-6f91-11ea-9ca5-e3f0c0714da2.png)

**Comment by qindj** [comment]
一样的，仔细看看文档，options里的reload，可以传function
