### ISSUE TITLE
如何去掉复选框🧐[问题]

### ISSUE THREAD

**Issue by s464446877** [ant-design/pro-table#254]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
如何去掉表格前面的复选框

**Comment by PenyWang** [comment]
请问下，这个问题解决了吗，如何解决的？
excuse me? how did you resolve this quesion?

**Comment by PenyWang** [comment]
i know, remove the rowSelection will be ok
我知道了，删除rowSelection就可以了
