### ISSUE TITLE
🐛[BUG] 拼写错误

### ISSUE THREAD

**Issue by keepmood** [ant-design/pro-table#258]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
pro-table/src/Form/index.tsx 多处
pro-table/src/Table.tsx 517行
以上文件中 表单**Form** 错误拼写为**From**

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by keepmood** [comment]
另外此处其实是使用Protable的Form类型时遇到date类型字段错误发现的，所以想问下为什么antd的TimePicker默认赋值date类型时接收参数必须为moment类型？组件内部处理接收参数转换成指定类型是否更合理些，毕竟组件闭环的情况下要求额外都第三方格式体验上来说不是特别好。

**Comment by chenshuai2144** [comment]
来个 pr 吧

**Comment by keepmood** [comment]
> 来个 pr 吧

有个问题想请教下，在我使用protable的form时，如果字段类型是datetime，但值为string，直接设置column的valueType为dateTime，这时候会触发moment的clone错误，所以我使用了renderFormItem方法来自定义：
`renderFormItem: (_, config) => (<DatePicker  value={config.value ? moment(config.value) : undefined} showTime={true} onChange={config.onChange} style={{ width: '100%' }} />)`
这种方式解决了数据绑定问题，但又有另外一个问题，那就是保存表单时如果**没有修改日期**，也就是没有触发**onChange**事件的话，该字段的值在onSubmit中无法获得，所以想请教下这种情况该怎么解决。

**Comment by keepmood** [comment]
> > 来个 pr 吧
> 
> 有个问题想请教下，在我使用protable的form时，如果字段类型是datetime，但值为string，直接设置column的valueType为dateTime，这时候会触发moment的clone错误，所以我使用了renderFormItem方法来自定义：
> `renderFormItem: (_, config) => (<DatePicker value={config.value ? moment(config.value) : undefined} showTime={true} onChange={config.onChange} style={{ width: '100%' }} />)`
> 这种方式解决了数据绑定问题，但又有另外一个问题，那就是保存表单时如果**没有修改日期**，也就是没有触发**onChange**事件的话，该字段的值在onSubmit中无法获得，所以想请教下这种情况该怎么解决。

找到原因了，当指定了valueType为dateTime却又传string类型的值，onSubmit中conversionValue函数校验数据格式不合法因此过滤掉了属性值，但通过DatePicker选择日期后的值已经转换为了moment类型，所以可以通过conversionValue，所以两种方法，要么转换初始化数据日期类型为moment，要么不声明valueType，在renderFormItem中处理。

这块是不是能通过封装FromInputRender函数来主动处理下，当值为字符串类型但valueType指定为时间相关类型时主动转换下传入值？如果思路可行的话我可以在做一个PR。

**Comment by chenshuai2144** [comment]
可以，发个 pr 我们来讨论一下
