### ISSUE TITLE
🧐[问题]Protable request属性返回值的key的说明，在哪个文档里可以找到

### ISSUE THREAD

**Issue by abcnny** [ant-design/pro-table#260]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
请问一下，protable的异步请求返回的key值是在哪个文档里有说明，像图里的data,page,success在哪能找到，找了半天没发现在哪

`return {
              data,
              page: params.current,
              success: true,
              total: ((totalObj[0] || { number: 0 }).number - 56) as number,
            };`

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/7876570/77745386-1df03000-7056-11ea-8351-a32516a34319.png)

**Comment by chenshuai2144** [comment]
这个是 github 的 api，去看看 github 的文档就好了。

或者直接看控制台
