### ISSUE TITLE
怎么删除工具类上面选择表格密度（行高）的按钮？🧐[问题]

### ISSUE THREAD

**Issue by fengnex** [ant-design/pro-table#264]
![YKDMCEAZ{G0_VC8H TNCSCV](https://user-images.githubusercontent.com/26297547/77817186-fb1c5500-7103-11ea-9165-737e91409127.png)
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
如上图所示，选择行高的表格工具栏按钮（点击后有个下拉菜单，能有默认、中等、紧凑3个菜单项），如果要去掉，该怎么操作？

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![YKDMCEAZ{G0_VC8H TNCSCV](https://user-images.githubusercontent.com/26297547/77817226-51899380-7104-11ea-8db4-8910cd6145d6.png)

**Comment by chenshuai2144** [comment]
`options={{ density: false}}`
这样配置

**Comment by zlyyyy** [comment]
@chenshuai2144 options={{ density: false}}这么写就全部消失了

**Comment by zlyyyy** [comment]
这样写才可以
```
options={{
   density: false,
   fullScreen: true,
   reload:true,
   setting: true
}}
```

**Comment by chenshuai2144** [comment]
应该默认为true，我卡卡那款能不能支持
