### ISSUE TITLE
👑 [需求]提供DataSource操作的api

### ISSUE THREAD

**Issue by cuihq2005** [ant-design/pro-table#266]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
传统的Table页面大多包含增删改查操作，增、删、改操作一般会要求反馈在当前页面上。从官网示例上，基本是通过前端调用action.reload来重新加载数据，这在高并发的系统上会增加一次后台操作，影响效率。能否提供操作DataSource的api，结合rowKey，直接变更本地的DataSource，省去重新加载的过程

**Comment by chenshuai2144** [comment]
与 antd 的 api 相同，你可以直接使用。

**Comment by wenxiayili** [comment]
> 与 antd 的 api 相同，你可以直接使用。

@chenshuai2144  有这么一种情况：我使用request的方式取得数据，我想在页面获取table的dataSource，这个现有的API是否支持？

**Comment by chenyu1990** [comment]
这个API并不能使用。protable官方文档也没有 setDataSource的操作， value和onChange没有。如何操作？通过 useState获取 dataSource也是空的
