### ISSUE TITLE
需求: pro-table的type为form时, 配置的valueType为option时，render函数能够展示自定义的组件

### ISSUE THREAD

**Issue by stack-wuh** [ant-design/pro-table#267]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
在columns中配置同一字段在表格与表单中的不同实现，配置如下： 
![image](https://user-images.githubusercontent.com/34117238/77840610-f4511900-71bb-11ea-9074-c0789ed0fe6c.png)

在配置了option后，表单的渲染为Input输入框，而不是由render函数渲染的jsx
![image](https://user-images.githubusercontent.com/34117238/77840645-35492d80-71bc-11ea-97ed-c839dd543135.png)

### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]

添加一个可以自定义的属性compoents, 做成一个函数，返回一个jsx

**Comment by 1995lk** [comment]
一样的问题  求解

**Comment by stack-wuh** [comment]
https://github.com/ant-design/pro-table/blob/master/src/Form/index.tsx
源码里面没实现，valueType没有为option的处理

**Comment by 1995lk** [comment]
有什么好的办法  给个建议

**Comment by wangwanli24** [comment]
同问，如何加个Cascader级联选择器，可以选择地区

**Comment by chenshuai2144** [comment]
正在开发，很快就要有了

**Comment by wangwanli24** [comment]
下次更新大概什么时候啊
