### ISSUE TITLE
👑 [需求]

### ISSUE THREAD

**Issue by liuyun521** [ant-design/pro-table#268]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
在表格带的修改窗口里面，不能将row-key带过去，导致在修改提交时，没有row-key
![image](https://user-images.githubusercontent.com/9554224/77845695-76a10380-71e3-11ea-876a-1868479813f2.png)
![image](https://user-images.githubusercontent.com/9554224/77845706-83bdf280-71e3-11ea-828c-dad6c4e1c65a.png)
但是在修改提交时，row-key就没有带了
![image](https://user-images.githubusercontent.com/9554224/77845726-a0f2c100-71e3-11ea-95ab-1800f5725ea0.png)
![image](https://user-images.githubusercontent.com/9554224/77845759-faf38680-71e3-11ea-8181-43344dac30b8.png)

除非你把所有的控件一个个重写，但这样{props.children}简写的意义就没有了

### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
可以的话，还是在form表单提交时，还是要带上row-key吧，这样新增/修改可以同一个页面，不用那么多重复的

**Comment by chenshuai2144** [comment]
rowKey 是什么字段？

**Comment by liuyun521** [comment]
> row�Key 是什么字段？

empId,第一个图里的一样:empId

**Comment by chenshuai2144** [comment]
empId 这个在 form 中没有用吧，
你是希望拿到具体哪一行的key，然后和后端进行通信吗？

**Comment by liuyun521** [comment]
> empId 这个在 form 中没有用吧，
> 你是希望拿到具体哪一行的key，然后和后端进行通信吗？

![image](https://user-images.githubusercontent.com/9554224/77889593-ae21b580-72a0-11ea-9ae1-59542b5341b3.png)
