### ISSUE TITLE
🐛[BUG] 查询表格的“状态”列的filter无效，以及响应式样式问题

### ISSUE THREAD

**Issue by ousing9** [ant-design/pro-table#27]
### 🐛 bug 描述

[查询表格](https://preview.pro.ant.design/list/table-list)页面，“状态”列的**filter**无效。
![image](https://user-images.githubusercontent.com/32257773/71083789-cc224900-21ce-11ea-992f-52a0474e5e87.png)

另外还有响应式的样式问题。
![image](https://user-images.githubusercontent.com/32257773/71083922-11df1180-21cf-11ea-90b8-fdcb8d35888e.png)

### © 版本信息

- 浏览器环境: Chrome 79

**Comment by ousing9** [comment]
更新到了1.0.21，filter这个问题就差数字**0**了
![image](https://user-images.githubusercontent.com/32257773/71316183-c49cc180-24a6-11ea-9b96-674274770a56.png)
![image](https://user-images.githubusercontent.com/32257773/71316189-df6f3600-24a6-11ea-8498-f858d66f3909.png)

**Comment by chenshuai2144** [comment]
fixed
