### ISSUE TITLE
🐛[BUG]valueEnum在搜索表单和增加表单不同时怎么处理

### ISSUE THREAD

**Issue by abcnny** [ant-design/pro-table#273]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
`
title: '性别',
      dataIndex: 'gender',
      valueEnum: {
        all: { text: '所有' },
        male: { text: '男' },
        female: { text: '女' },
        unknow: { text: '未知' },
      }
`
对于valueEnum，在搜索表单显示所有，而在增加表单把所有去掉，这种该怎么弄

**Comment by chenshuai2144** [comment]
valueEnum 支持传入一个 fucntion 的

**Comment by victorli** [comment]
如何传一个function? 是否可以通过传入record然后生成valueEnum?

**Comment by qindj** [comment]
https://protable.ant.design/value-type#valueenum @victorli  文档上有
