### ISSUE TITLE
在columns中配如何做文字输入限制

### ISSUE THREAD

**Issue by 1995lk** [ant-design/pro-table#278]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
在columns中配如何做文字输入限制
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/48973261/77988726-9e14df00-734f-11ea-96c8-0b761da99355.png)

**Comment by chenshuai2144** [comment]
只是 antd 的任何配置的
antd 的 from 支持 min 和 max 规则
