### ISSUE TITLE
🐛[BUG]分页大小下拉框没有国际化

### ISSUE THREAD

**Issue by heyepeng** [ant-design/pro-table#280]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
分页大小下拉框处没有国际化，所有语言都是 xx/page
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.1.0]
- umi 版本 3.0.6
- 浏览器环境
- 开发环境 [e.g. windows7]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/13937417/78018333-480c5f80-7380-11ea-9dc5-9726f20cc831.png)

**Comment by chenshuai2144** [comment]
这个时antd的设置，引入到项目中会自动设置的。
https://umijs.org/plugins/plugin-locale
https://ant.design/components/config-provider-cn/
