### ISSUE TITLE
🐛[BUG] React does not recognize the `formItemProps` prop on a DOM element

### ISSUE THREAD

**Issue by HelloSetsuna** [ant-design/pro-table#285]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
当使用 Columns的 formItemProps 属性时, 在 ProTable 的 type 是 form的时候会显示如下警告信息:
Warning: React does not recognize the `formItemProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `formitemprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by Context.Consumer)
    in Row (created by Field)
    in Field (created by WrapperField)
    in WrapperField (created by FormItem)
    in FormItem (created by FormSearch)
    in div (created by Context.Consumer)
    in Col (created by FormSearch)
    in div (created by Context.Consumer)
    in Row (created by Context.Consumer)
    in form (created by ForwardRef(Form))
    in ForwardRef(Form) (created by ForwardRef(InternalForm))
    in SizeContextProvider (created by ForwardRef(InternalForm))
    in ForwardRef(InternalForm) (created by Context.Consumer)
    in div (created by ResizeObserver)
    in ResizeObserver (created by Context.Consumer)
    in div (created by Context.Consumer)
    in FormSearch (created by ProTable)
    in div (created by ProTable)
    in LocaleProvider (created by Context.Consumer)
    in SizeContextProvider (created by Context.Consumer)
    in LocaleReceiver (created by ConfigProvider)
    in ConfigProvider (created by ProTable)
    in ProTable (created by Context.Consumer)
    in Provider (created by ProviderWarp)
    ... (部分不相关异常栈信息我省略了)
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
columns = [
    {
      title: '编号',
      dataIndex: 'scenarioNumber',
      sorter: "true",
      align: 'center',
      width: 120,
      valueType: "digit",
      formItemProps: {
        min: 100,
        max: 999
      }
    },
]
### 🏞 期望结果 [描述你原本期望看到的结果]
使用 formItemProps 且在 ProTable 的 type 是 form的时候不再显示此警告信息, 或者考虑更换此参数的名称, (Search那里渲染显示的时候并没有警告)

### © 版本信息

  "dependencies": {
    "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-layout": "^5.0.8",
    "@ant-design/pro-table": "^2.1.11",
    "antd": "^4.0.0",
    "classnames": "^2.2.6",
    "lodash": "^4.17.11",
    "moment": "^2.24.0",
    "omit.js": "^1.0.2",
    "path-to-regexp": "2.4.0",
    "qs": "^6.9.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-helmet-async": "^1.0.4",
    "umi": "^3.0.14",
    "umi-request": "^1.0.8",
    "use-merge-value": "^1.0.1"
  },

**Comment by chenshuai2144** [comment]
已经 fixed，但是还没发版本 可以先等等
