### ISSUE TITLE
🧐[问题]列如何设置默认不展示，但依然可以通过列设置来进行勾选 显示

### ISSUE THREAD

**Issue by zhuhangan** [ant-design/pro-table#286]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
在table中列比较多的情况下，想默认只显示其他的几列，现在columns 只有hideInTable来设置，但是如果设置了这个参数，在列设置里面就不会显示这一列了，没法做勾选显示了。请问是我使用方式不对还是本身不支持这个功能呀？

**Comment by chenshuai2144** [comment]
https://protable.ant.design/example#%E5%8F%97%E6%8E%A7%E6%A8%A1%E5%BC%8F
可以看看这个demo

**Comment by zhuhangan** [comment]
> https://protable.ant.design/example#%E5%8F%97%E6%8E%A7%E6%A8%A1%E5%BC%8F
> 可以看看这个demo

感谢！之前看文档没明白这个配置是干啥的，所以忽略了。

**Comment by somerchen** [comment]
> https://protable.ant.design/example#%E5%8F%97%E6%8E%A7%E6%A8%A1%E5%BC%8F
> 可以看看这个demo

我按照这个来不生效

**Comment by sunsmeil** [comment]
没懂

**Comment by trlanfeng** [comment]
> > https://protable.ant.design/example#%E5%8F%97%E6%8E%A7%E6%A8%A1%E5%BC%8F
> > 可以看看这个demo
> 
> 我按照这个来不生效

最新的例子：https://procomponents.ant.design/components/table#%E5%8F%97%E6%8E%A7%E7%9A%84%E8%A1%A8%E6%A0%BC%E8%AE%BE%E7%BD%AE%E6%A0%8F

columnsStateMap中对应的是`key`，而不是`dateIndex`，加上`key`后有效果
