### ISSUE TITLE
支持文件上传👑 [需求]

### ISSUE THREAD

**Issue by tianyunperfect** [ant-design/pro-table#287]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
如果表格的某个字段存储的是文件或者图片的地址，我想着新建或者更新页面修改当前字段（支持上传并返回url），目前没有发现支持file类型，请问我应该怎么实现这个功能？

**Comment by qindj** [comment]
可以自定义render实现

**Comment by tianyunperfect** [comment]
> 可以自定义render实现

有具体的例子吗？请原谅我是个菜鸟。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/pull/6287

看这个里面的 diff

**Comment by tianyunperfect** [comment]
> [ant-design/ant-design-pro#6287](https://github.com/ant-design/ant-design-pro/pull/6287)
> 
> 看这个里面的 diff

非常感谢

**Comment by tianyunperfect** [comment]
> [ant-design/ant-design-pro#6287](https://github.com/ant-design/ant-design-pro/pull/6287)
> 
> 看这个里面的 diff

您好，upload没有value属性，请问怎么操作呢？你看我的截图，没办法通过onchange事件给form赋值，求大神指点一下：
![image](https://user-images.githubusercontent.com/23491291/78364519-29ac9b00-75f0-11ea-8c22-1b125e8b2916.png)
![image](https://user-images.githubusercontent.com/23491291/78364552-38934d80-75f0-11ea-94b8-aa6985f4d6b4.png)

**Comment by tianyunperfect** [comment]
已经搞定了，谢谢，下面是我的实现方法，必须2.2.0才行
![image](https://user-images.githubusercontent.com/23491291/78366176-b5bfc200-75f2-11ea-99e8-3cff8b42f490.png)
