### ISSUE TITLE
🐛[BUG] 序号列的序号显示问题

### ISSUE THREAD

**Issue by fangzhengjin** [ant-design/pro-table#294]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

当前将valueType设置为index或indexBorder时, 如果表格数据有多页那么每页的序号都是从1开始
预期的结果应该是按照分页的情况自动计算当前序号, 现在这个情况是有意这么设计的吗?

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
是的，是这一页的序号，不是整体的序号。

**Comment by fangzhengjin** [comment]
> 是的，是这一页的序号，不是整体的序号。

是不是可以加一个按分页显示的序号呢 只是这一页的序号不是很常用
另外...如果序号的样式可以自定义就更好了 内置的有点丑~

**Comment by chenshuai2144** [comment]
emmm 序号的样式是我们的设计，你需要自定义可以自己用 render 实现一下。我们做这个就是为了统一设计

**Comment by phoema** [comment]
如何将序号调整为按页计算后的序号呢？
