### ISSUE TITLE
🐛[BUG] IntlProvider not respected in the pagination

### ISSUE THREAD

**Issue by maurodelazeri** [ant-design/pro-table#295]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
After updating to the latest version 2.2.0 the table is not using `IntlProvider` to keep the pagination in English. The version I was running before was `2.1.11` and I did not have this drop-down neither this part that is not translated.

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

![example](http://i.imgur.com/q9s294z.png)

### 🏞 期望结果 [描述你原本期望看到的结果]
respect the `IntlProvider` language

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
I'm already wrapping the table with `      <IntlProvider value={enUSIntl}>`
 
### © 版本信息

- Ant Design Pro 版本: [latest]
- umi 版本 latest
- 浏览器环境 latest
- 开发环境 [linux]

**Comment by tharindu991** [comment]
is there a fix for this?

**Comment by chenshuai2144** [comment]
you can config showTotal  in pagination
```
showTotal: (all, range) => `第 ${range[0]}-${range[1]} 条/总共 ${all} 条`,
```
