### ISSUE TITLE
🧐[问题] tableAlertRender 报错  Cannot read property 'reduce' of undefined

### ISSUE THREAD

**Issue by chenshuai2144** [ant-design/pro-table#296]
新版本中 tableAlertRender 的第一个参数从数组变成 对象，造成了一个不兼容的改动

## 表现

![image](https://user-images.githubusercontent.com/8186664/78323188-aa917580-75a3-11ea-978c-15743c485b15.png)

## 改动方式

```
- tableAlertRender={(selectedRowKeys, selectedRows) => (
+ tableAlertRender={({ selectedRowKeys, selectedRows }) => (
```

非常抱歉造成了影响。

**Comment by nameJw** [comment]
请问这个tableAlertRender在哪能找到说明？ProTable的很多属性我看文档都没写到啊。比如onSubmit等等

**Comment by BoBoooooo** [comment]
> 请问这个tableAlertRender在哪能找到说明？ProTable的很多属性我看文档都没写到啊。比如onSubmit等等

你好 我这里也没找到onSubmit的文档...

**Comment by chenshuai2144** [comment]
在这里 https://protable.ant.design/select

**Comment by xingpengfan** [comment]
多选翻页是不是会丢失呀？我看官网例子翻页多选之前选中的也没有了？ @chenshuai2144
