### ISSUE TITLE
👑 [需求]

### ISSUE THREAD

**Issue by 569202812** [ant-design/pro-table#298]
### 🥰 需求描述
1. 搜索希望可以支持lable不展示 可以在placeholder展示
2. 希望提供自定义的搜索更高级的功能
### 🧐 解决方案
1.{label: false, placeholder: '巴拉巴拉'}
### 🚑 其他信息
![image](https://user-images.githubusercontent.com/34082148/78338662-c1e15a80-75c5-11ea-8792-745093d9215b.png)

**Comment by chenshuai2144** [comment]
这样不规范，protable 想要统一设计。就是为防止这种奇怪的设计

**Comment by 569202812** [comment]
> 这样不规范，protable 想要统一设计。就是为防止这种奇怪的设计
是的感觉自定义需求大的就不适合这个了

**Comment by chenshuai2144** [comment]
我们的设计不一定好，但是没有错。这时我们的目的
