### ISSUE TITLE
🐛[BUG] 远程加载数据，多页返回第1页，无法刷新数据

### ISSUE THREAD

**Issue by myonlylonely** [ant-design/pro-table#3]
将官方的远程加载Ajax数据的示例，从Table修改为ProTable。初始无法加载数据，并且点击翻页翻到第2页可以加载第2页的数据，再点击返回第1页，也无法加载第1页数据。

示例：https://codesandbox.io/s/reverent-worker-v4oc6

**Comment by yunuo-tech** [comment]
同样的问题

**Comment by chenshuai2144** [comment]
我可以使用你的数据吗？

**Comment by myonlylonely** [comment]
请问这个修复什么时候能够在NPM上更新呢？

**Comment by chenshuai2144** [comment]
已经发布了
https://github.com/ant-design/pro-table/releases
