### ISSUE TITLE
👑 [需求] 是否可以支持将分页参数拼在url

### ISSUE THREAD

**Issue by liujiayii** [ant-design/pro-table#306]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
从table进入详情页再回来会回到第一页，umi好像没有类似keep-alive的功能，希望table能停留在当前页
### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
是否可以提供将分页参数拼在url，

**Comment by chenshuai2144** [comment]
umi 在 3.1 中会提供 keep-alive，所以这个问题等等就不需要解决了。


你可以在request中劫持到 pageSize 等信息
