### ISSUE TITLE
🐛[BUG]当从antd 3.x升级到4.1时，pro-table报错了

### ISSUE THREAD

**Issue by effapp** [ant-design/pro-table#307]
### 🏞 期望结果 [描述你原本期望看到的结果]
希望能不报错。

### © 版本信息

- Ant Design Pro 版本: [ 4.0.0]
- umi 版本  umi@2.13.11
- 浏览器环境 chrome 版本 73.0.3683.103（正式版本） （32 位）
- 开发环境 [win10]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![image](https://user-images.githubusercontent.com/51013754/78466303-2f11fe80-7732-11ea-8ca5-f404abc22ed4.png)
![image](https://user-images.githubusercontent.com/51013754/78466310-418c3800-7732-11ea-91da-bf8550dd54d3.png)
![image](https://user-images.githubusercontent.com/51013754/78466313-5cf74300-7732-11ea-96b5-7933cbbcb8ec.png)

**Comment by effapp** [comment]
useContainer
../src/unstated-next.tsx:24
  21 | }
  22 | 
  23 | function useContainer(): Value {
> 24 | 	let value = React.useContext(Context)
     | ^  25 | 	if (value === null) {
  26 | 		throw new Error("Component must be wrapped with <Container.Provider>")
  27 | 	}
View compiled
columRender
node_modules/@ant-design/pro-table/es/Table.js:166
  163 |     text = _ref.text,
  164 |     row = _ref.row,
  165 |     index = _ref.index;
> 166 | var counter = Container.useContainer();
      | ^  167 | var action = counter.action;
  168 | var _item$renderText = item.renderText,
  169 |     renderText = _item$renderText === void 0 ? function (val) {
View compiled
render
node_modules/@ant-design/pro-table/es/Table.js:242
  239 | // @ts-ignore
  240 | children: item.children ? genColumnList(item.children, map) : undefined,
  241 | render: function render(text, row, index) {
> 242 |   return columRender({
      | ^  243 |     item: item,
  244 |     text: text,
  245 |     row: row,
View compiled
TableCell.render
node_modules/antd/node_modules/rc-table/es/TableCell.js:115
finishClassComponent
node_modules/react-dom/cjs/react-dom.development.js:17160
  17157 | } else {
  17158 |   {
  17159 |     setIsRendering(true);
> 17160 |     nextChildren = instance.render();
        | ^  17161 | 
  17162 |     if ( workInProgress.mode & StrictMode) {
  17163 |       instance.render();
View compiled
updateClassComponent

**Comment by effapp** [comment]
是在数据渲染时出错，在antd 3.x时是正常的，升级到antd 4.1后，渲染报错了。

**Comment by chenshuai2144** [comment]
pro-table 升级到 2.0 试试
