### ISSUE TITLE
🧐[问题]ProTable没有使用内置查询Form， 如何回到第一页？

### ISSUE THREAD

**Issue by pengshaomin** [ant-design/pro-table#308]
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/17870116/78467459-b0bc5900-773f-11ea-82d9-f001c9dfd224.png)

**Comment by chenshuai2144** [comment]
可以用受控模式的。与 antd 的 api 相同。


pagination | 分页器，参考配置项或 pagination 文档，设为 false 时不展示和进行分页
-- | --
