### ISSUE TITLE
dateFormatterMap 缺少dateRange、dateTimeRange

### ISSUE THREAD

**Issue by snice** [ant-design/pro-table#313]
https://github.com/ant-design/pro-table/blob/c9a109f28daf1cb8ac55c7c5ed71e99e7f304502/src/Form/index.tsx#L361

dateFormatterMap 缺少dateRange、dateTimeRange，导致返回的数据是YYYY-MM-DD HH:mm:ss

**Comment by chenshuai2144** [comment]
有兴趣来个 pr 吗

**Comment by snice** [comment]
已提交，https://github.com/ant-design/pro-table/pull/330
