### ISSUE TITLE
🐛[BUG]valueEnum 的 key为false时，表格以此过滤失败

### ISSUE THREAD

**Issue by abcnny** [ant-design/pro-table#314]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
`valueEnum: {
        true: { text: '启用' },
        false: { text: '禁用' },
      }`
当设置column的valueEnum如上所示，在表格中筛选此列为"启用"时，过滤不到数据，无报错，筛选为"禁用"时，可以正常过滤到数据。

**Comment by chenshuai2144** [comment]
额，能不用 false 吗，false 有自己的 行为，用起来有点那首

**Comment by yyhuaisha** [comment]
本身valueEnum 就是支持string，你传其他的都没用。还是会强制转成string。而且传flase可能会有默认的行为，建议转string，请求的时候再转回来
