### ISSUE TITLE
🧐[问题] ProTable数据列顺序错位

### ISSUE THREAD

**Issue by fangzhengjin** [ant-design/pro-table#315]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
在使用ProTable时, 添加无dataIndex的操作列或其他展示列时会导致无dataIndex的列展示顺序错位, 这个操作列应该是固定显示在最后一列的
![image](https://user-images.githubusercontent.com/12680972/78764895-c8067b00-79b9-11ea-9e03-7d14412d2945.png)
跟踪源代码时发现Table.tsx中662行, 对可视化数据进行了排序
```tsx
  /**
   * 这里主要是为了排序，为了保证更新及时，每次都重新计算
   */
  useDeepCompareEffect(() => {
    const keys = counter.sortKeyColumns.join(',');
    let tableColumn = genColumnList<T>(propsColumns, counter.columnsMap);
    if (keys.length > 0) {
      // 用于可视化的排序
      tableColumn = tableColumn.sort((a, b) => {
        // 如果没有index，在 dataIndex 或者 key 不存在的时候他会报错
        const aKey = `${genColumnKey(a.key, (a as ProColumnType).dataIndex) || a.index}_${a.index}`;
        const bKey = `${genColumnKey(b.key, (b as ProColumnType).dataIndex) || b.index}_${b.index}`;
        return keys.indexOf(aKey) - keys.indexOf(bKey);
      });
    }
    if (tableColumn && tableColumn.length > 0) {
      counter.setColumns(tableColumn);
    }
  }, [counter.columnsMap, counter.sortKeyColumns.join('-')]);
```
参与排序的keys, 给没有dataIndex的列使用了元素的下标
![image](https://user-images.githubusercontent.com/12680972/78766170-81b21b80-79bb-11ea-8d65-12ad21d1e065.png)

经过排序后, 将没有dataIndex的操作列排序到了第一位
![image](https://user-images.githubusercontent.com/12680972/78765704-f2a50380-79ba-11ea-8fc8-1474226bd41c.png)
将排序操作 `tableColumn.sort` 注释后可正常使用, 暂时没有发现这个排序的作用, 为什么不直接使用传入columns的顺序呢? 这个问题有没有什么比较好的解决方法 @chenshuai2144 

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
[![Edit protable-issues-315](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/protable-issues-315-7i0eg?fontsize=14&hidenavigation=1&module=%2Fdemo.tsx&theme=dark)

**Comment by chenshuai2144** [comment]
😯，that's so bad
