### ISSUE TITLE
🧐[问题]无搜索及toolBar时如何去掉空白部分

### ISSUE THREAD

**Issue by Totti0135** [ant-design/pro-table#318]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
options和search都设置为false后，页面上方会有个class为ant-pro-table-toolbar的空白的div，请问要如何去掉？
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![图片](https://user-images.githubusercontent.com/9415240/78771413-b2e21a00-79c2-11ea-9bd0-d7ca7995f345.png)

**Comment by chenshuai2144** [comment]
toolBarRender={false} 先手动一下，有好几个人碰到了我改成自动
