### ISSUE TITLE
🐛action.reload() 不附带搜索条件

### ISSUE THREAD

**Issue by hnsylitao** [ant-design/pro-table#32]
当搜索完数据结果，然后在触发action.reload() 这里的数据查询 没有附带上次搜索结果

**Comment by hnsylitao** [comment]
又发现一个问题，当我翻页之后在触发action.reload() 获取的还是上一页的数据

**Comment by hnsylitao** [comment]
#26 和这个问题其实是相同的～

**Comment by lg970044** [comment]
我也碰到同样的问题，在第3页删除或编辑一个数据后，调用reload，翻页显示在当前第3页，重新加载的页面数据是却是第一页的数据。

**Comment by hnsylitao** [comment]
@lg970044  我现在还没解决，是直接把代码clone 下来然后自己直接把action 对象暴露在window 上来解决

**Comment by cocowhr4545** [comment]
同样问题
版本:1.0.21
action.reload()不附带搜索条件

**Comment by arvinxx** [comment]
这个问题修复了吗？我 1.0.24 还是会有这个问题

**Comment by chenshuai2144** [comment]
@arvinxx  来个重现？
