### ISSUE TITLE
🐛[BUG] renderFormItem -> form 

### ISSUE THREAD

**Issue by kaoding** [ant-design/pro-table#321]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

and pro ListTableList 里的代码
```
      renderFormItem: (item, { defaultRender, ...rest }, form) => {
        const status = form.getFieldValue('status');
        if (`${status}` === '0') {
          return false;
        }
        if (`${status}` === '3') {
          return <Input {...rest} placeholder="请输入异常原因！" />;
        }
        return defaultRender(item);
      },
```

console 报错

![image](https://user-images.githubusercontent.com/18542211/78883534-361b7280-7a8c-11ea-8754-566b0b992c68.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by ZhouYiJun173** [comment]
renderFormItem: (item,props) => {
        return (
          <div id="personImage" value="helloworld">
            <Upload
              listType="picture-card"
              showUploadList={false}
              action={upLoadUrl}
              onChange={(info)=> props.onChange(handleChange(info))}
            >
              {props.value ? <img  src={props.value} alt="avatar" style={{ width: '100%' }}/> : uploadButton}
            </Upload>
          </div>
        )

      }


//配置数据的时候用props.onChange() 方法去设定，不用getFieldValue了

**Comment by kaoding** [comment]
> ```
> renderFormItem: (item,props) => {
>         return (
>           <div id="personImage" value="helloworld">
>             <Upload
>               listType="picture-card"
>               showUploadList={false}
>               action={upLoadUrl}
>               onChange={(info)=> props.onChange(handleChange(info))}
>             >
>               {props.value ? <img  src={props.value} alt="avatar" style={{ width: '100%' }}/> : uploadButton}
>             </Upload>
>           </div>
>         )
> 
>       }
> ```
> 
> //配置数据的时候用props.onChange() 方法去设定，不用getFieldValue了

不是这个错误，是因为
```
renderFormItem: (item, { defaultRender, ...rest }, form) => {
 const status = form.getFieldValue('status');
...
}
```

**Comment by chenshuai2144** [comment]
加了个黑科技来解决这个问题，form 接下来会 py 给我一个api 来完美解决
