### ISSUE TITLE
使用hideInTable选项之后 table列顺序改变🐛[BUG]

### ISSUE THREAD

**Issue by djif007** [ant-design/pro-table#329]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
在某个column设置了hideInTable之后，原本应该在最后一列展示的项出现在第一列
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
![image](https://user-images.githubusercontent.com/45057015/78979711-fa95ac80-7b4e-11ea-8eb8-77481edd9042.png)
![image](https://user-images.githubusercontent.com/45057015/78979719-fe293380-7b4e-11ea-8419-c698727aab3e.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
都设置一下dataIndex 或者key就可以了
