### ISSUE TITLE
🐛[BUG] 当元素值为 0 时，不会显示该项值

### ISSUE THREAD

**Issue by arvinxx** [ant-design/pro-table#33]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
当某项类型为 number，且值为 0 时，不会显示该项值

### © 版本信息

- Pro-Table 1.0.21

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/28616219/71339275-005e8680-258e-11ea-9ad4-242a164c6f7d.png)
如图，直接渲染时课程数量一列为空，而用空尖括号包裹或者转成字符时，均能正常显示

**Comment by hnsylitao** [comment]
https://github.com/ant-design/pro-table/blob/master/src/Table.tsx#L381
这里得判断问题

**Comment by hnsylitao** [comment]
可以加一个renderText 自己做一个前置判断

**Comment by chenshuai2144** [comment]
fixed
