### ISSUE TITLE
🐛[BUG] dataIndex: 'depart.name'   对象属性。为啥不显示

### ISSUE THREAD

**Issue by 693614965** [ant-design/pro-table#332]
{
      title: '申请部门',
      dataIndex: 'depart.name',
    },
    {
      title: '申请员工',
      dataIndex: 'emp.realName'
    },
类似以前的对象属性。为啥在 表格 不显示呢？ 
还有就是 新增 编辑的时候  select  怎么处理。新增时选择部门，部门连带出员工选择，

**Comment by chenshuai2144** [comment]
新版本需要  dataIndex: ["emp","realName"]

**Comment by 693614965** [comment]
请教怎么修改菜单字体大小啊？



---原始邮件---
发件人: "陈帅"<notifications@github.com&gt;
发送时间: 2020年5月26日(周二) 下午3:19
收件人: "ant-design/pro-table"<pro-table@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"693614965"<693614965@qq.com&gt;;
主题: Re: [ant-design/pro-table] [BUG] dataIndex: 'depart.name'   对象属性。为啥不显示 (#332)




 
Closed #332.
