### ISSUE TITLE
🐛[BUG]最新版本分页的Total没有国际化

### ISSUE THREAD

**Issue by xiaopanghhh** [ant-design/pro-table#333]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

![image](https://user-images.githubusercontent.com/24469601/79066291-67dd4500-7ce9-11ea-9b84-c20294e9c16d.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
umi 的 bug，已经修复

**Comment by gaoweijun2018** [comment]
这个bug还有，umi的版本是3.1.2，pro-table的版本为2.3.4。
做过的操作，删除了src下的locale目录，
config目录下的locale配置为
    locale: {
       default: 'zh-CN',
        antd: true,
        baseNavigator: false,
    }
