### ISSUE TITLE
👑 [需求]  测试下来发现，默认的查询表单配置改一下更合适。

### ISSUE THREAD

**Issue by xiaopanghhh** [ant-design/pro-table#335]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
测试下来发现，默认的查询表单配置改一下更合适。
由于网络原因，就不发 PR 了。
span: {
        xs: 24,
        sm: 24,
        md: 12,
        lg: 8,
        xl: 8,
        xxl: 6,
      }

const defaultColConfig = {
        xs: 24,
        sm: 24,
        md: 12,
        lg: 8,
        xl: 8,
        xxl: 6,
};

**Comment by chenshuai2144** [comment]
直接来pr
