### ISSUE TITLE
👑 [需求] 增加固定表头按钮 

### ISSUE THREAD

**Issue by Sean1514** [ant-design/pro-table#337]
🥰 需求描述 [详细地描述需求，让大家都能理解]
是否可以在配置按钮上加一个固定表头的按钮，让用户自己选择是否固定表头 

🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
🚑 其他信息 [如截图等其他信息可以贴在这里]

**Comment by chenshuai2144** [comment]
暂时没有这样的设计，现在也只需要一个参数，还好
