### ISSUE TITLE
🐛[BUG]ProTable 请求不存在的服务，或服务返回 404 或500，出现空白页，控制台有错误信

### ISSUE THREAD

**Issue by Leeshy-star** [ant-design/pro-table#340]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
 运行官方样例，修改mock中的请求路径，比如：
   'GET /api/rule': getRule,
  'POST /api/rule': postRule,
分别修改为
   'GET /api/v1/rule': getRule,
  'POST /api/v1/rule': postRule,
访问查询表格，弹出错误提示后，页面空白。
控制台错误信息如下： （其实就是datasource 为 undefine）

![image](https://user-images.githubusercontent.com/11751893/79123705-52d9e200-7dcd-11ea-92e2-a30186bcd5f4.png)

![image](https://user-images.githubusercontent.com/11751893/79123755-6ab16600-7dcd-11ea-8e5c-f373cd0d3e45.png)

1个月前的版本，具体版本号不清楚了，并不会出现这个错误。
### © 版本信息
    "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-layout": "^5.0.8",
    "@ant-design/pro-table": "^2.2.0",
    "antd": "^4.0.0",

**Comment by chenshuai2144** [comment]
dup of https://github.com/ant-design/pro-table/issues/339
