### ISSUE TITLE
🐛[BUG]pro-table options 位置

### ISSUE THREAD

**Issue by SantySun** [ant-design/pro-table#342]
### 🐛 bug 描述 

在表格顶端的【行距，全屏，刷新，设置】四个按键位置与间距存在布局问题
![image](https://user-images.githubusercontent.com/45656727/79198200-73aa4200-7e76-11ea-93e3-f86128c0dfaf.png)

### 💻 复现代码
```jsx
 <ProTable
        rowKey="uid"
        columns={columns}
        bordered
        pagination={{ showTotal: (total) => { return total > 1 ? `${total} Records.` : '1 Record.' } }}
        request={async (params) => {
          ...
        }}
      >
      </ProTable>
```
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- 浏览器环境: Chrome Version 81.0.4044.92 (Official Build) (64-bit)
- 开发环境 [Ubuntu19.10]

### 🚑 其他信息 
- 尝试过Firefox和Safari打开，所遇问题一致

**Comment by chenshuai2144** [comment]
less loader 没有配置吧，增加一下
