### ISSUE TITLE
🐛[BUG]pro-table列的fixed不生效

### ISSUE THREAD

**Issue by fanyawei** [ant-design/pro-table#345]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
在列中配置配置了fixed属性，不能实现固定列
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
当表格中有很多列时，需要配置fixed属性，实现固定操作列和重要的列。
### 🏞 期望结果 [描述你原本期望看到的结果]
配置fixed: 'left'时，列固定在左边，fixed: 'right'时固定要右边
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
![image](https://user-images.githubusercontent.com/8381679/79303001-66499200-7f20-11ea-88d3-6694a002eae6.png)
![image](https://user-images.githubusercontent.com/8381679/79303026-75304480-7f20-11ea-9059-5bf4e5c98f7c.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- "@ant-design/pro-layout": "^5.0.8"
- "@ant-design/pro-table": "^2.2.1"
- umi 版本:3.1.1
- 浏览器环境:Google Chrome 81.x
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
示例代码在此:
https://codesandbox.io/s/awesome-field-vuypd?file=/demo.tsx
在代码中，操作列设置了fixed:'right'，但是如果列数过多还是被挤。
另外，在代码中，使用了树表格，在只选中子项目不选中父项的时候，“批量操作”按钮不显示，证明"selectedRows"的数目仍然是0

**Comment by fangzhengjin** [comment]
你好像并没有提供任何有用的信息....  看你的截图没问题啊

**Comment by chenshuai2144** [comment]
无法重现呀，是不是没有配置 dataindex
