### ISSUE TITLE
🐛[BUG]使用valueEnum,当key为数字时，列中不显示数据

### ISSUE THREAD

**Issue by fanyawei** [ant-design/pro-table#346]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
使用valueEnum,当key为数字时，点击过滤表头，有过滤选项，search表单中，有过滤选项，但列中不显示
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
为表格列配置valueEnum属性，key为数字
### 🏞 期望结果 [描述你原本期望看到的结果]
表头有过滤选项，search表单有过滤选项，列中正常显示
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
![image](https://user-images.githubusercontent.com/8381679/79303513-a78e7180-7f21-11ea-8b1c-799681553de3.png)
![image](https://user-images.githubusercontent.com/8381679/79303555-becd5f00-7f21-11ea-9bd2-aadb7c329761.png)
![image](https://user-images.githubusercontent.com/8381679/79303576-cdb41180-7f21-11ea-986a-b240a3a3a61d.png)
![image](https://user-images.githubusercontent.com/8381679/79303594-d99fd380-7f21-11ea-851e-645cdb8c31fd.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- "@ant-design/pro-layout": "^5.0.8"
- "@ant-design/pro-table": "^2.2.1"
- umi 版本:3.1.1
- 浏览器环境:Google Chrome 81.x
- 开发环境 [e.g. mac OS]

**Comment by zhangbc** [comment]
pro-table 怎么转换显示呀。比如字段status 当为1显示正常，为0显示异常，后台传来的是number，用enum会报错，如何实现呢？
