### ISSUE TITLE
🧐[问题]pro-table配置查询表单时，如何配置区间查询

### ISSUE THREAD

**Issue by fanyawei** [ant-design/pro-table#347]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
比如，一个订单列表查询，有下单时间:createTime,有订单金额: orderAmount，现在，我的查询界面需要配置区间查询，比如，查询本月1号至本月10号所下单的数据，查询订单金额为 100元到1000元之间的订单数据。应该如何配置搜索表单
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
![image](https://user-images.githubusercontent.com/8381679/79304149-32bc3700-7f23-11ea-8506-c040609dd1ac.png)

**Comment by fangzhengjin** [comment]
https://protable.ant.design/api#valuetype

**Comment by fanyawei** [comment]
假设需要查询的区间非是时间，查询订单金额为 100元到1000元之间的订单数据，这样的如何配置

**Comment by fangzhengjin** [comment]
> 假设需要查询的区间非是时间，查询订单金额为 100元到1000元之间的订单数据，这样的如何配置

自己定义查询项的输入组件咯, valueType只是提供一些基础预置的, 个性化需求的话就需要自己写具体的表单项了
https://protable.ant.design/api#columns => renderFormItem
