### ISSUE TITLE
🐛[BUG] 在全屏模式下，Model 和 Drawer 都无法显示了。

### ISSUE THREAD

**Issue by xiaopanghhh** [ant-design/pro-table#348]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
在全屏模式下，基于 Model 和 Drawer 写的增加和修改都无法显示了。
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
https://preview.pro.ant.design/list/table-list
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/API/Fullscreen_API
我们使用了这个api，你需要将  dom 绑定到 table 的 dom 中
