### ISSUE TITLE
🐛[BUG] ProTable 2.2.0 版本开始renderFormItem无法获取到value和onChange

### ISSUE THREAD

**Issue by fangzhengjin** [ant-design/pro-table#349]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
renderFormItem传入的config对象中value和onChange始终为undefined
2.1.11      版本正常
2.2.0 和 2.2.1 均出现此问题 @chenshuai2144 

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
![image](https://user-images.githubusercontent.com/12680972/79326442-6e67f880-7f45-11ea-805e-cd47dc03f852.png)

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
[![Edit protable-issues-349](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/protable-issues-349-fmnti?fontsize=14&hidenavigation=1&module=%2Fdemo.tsx&theme=dark)
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
换了新的实现方式，不需要使用 value 和 onchange 了，你需要这个有什么需求吗？

**Comment by fangzhengjin** [comment]
> 换了新的实现方式，不需要使用 value 和 onchange 了，你需要这个有什么需求吗？

项目里的Table上表单搜索项里面有些用了自定义组件(比如搜索选择), 需要做一些处理后才通过onChange将值传到表单中, 如果去掉了onChange的话有什么替代的实现方法么? 还是只能扎堆写在request里面处理了

**Comment by fangzhengjin** [comment]
或者能否兼容原有的写法 用的地方还不少 忽然删了感觉有点那啥

**Comment by chenshuai2144** [comment]
这个是使用了antd的新方法导致的 我如果要实现就需要封装一下组件了

**Comment by fangzhengjin** [comment]
> 这个是使用了antd的新方法导致的 我如果要实现就需要封装一下组件了

个人感觉这种场景在搜索项高度定制下还是比较常见的, 比如下拉框, 虽然查询的时候展示了很多数据, 但是实际存储到表单中的肯定是要经过处理的, 或者其他对返回值有特殊处理的, 还是希望能够以较小的改动来升级到新版~

**Comment by infinityboy** [comment]
@fangzhengjin fangzhengjin 扎推写在request怎么扎推啊，怎么解决目前的问题

**Comment by fangzhengjin** [comment]
> @fangzhengjin fangzhengjin 扎推写在request怎么扎推啊，怎么解决目前的问题

我想的是所有特殊处理都写在request里面在向后台请求之前吧数据处理完, 但是感觉很臃肿...
你是啥场景?

**Comment by infinityboy** [comment]
@fangzhengjin 我也是一样的场景，我还有多条件查询，去掉了onChange 之前自定义的那些全都坏了，我想单独写请求，不用request，但是绑定的关系就也得单独重做了，仔细一想 这样的话 就没有必要用这个proTable组件了，要是全写request里 怎么写 还能触发查询，我还不知道怎么写。。

**Comment by fangzhengjin** [comment]
> @fangzhengjin 我也是一样的场景，我还有多条件查询，去掉了onChange 之前自定义的那些全都坏了，我想单独写请求，不用request，但是绑定的关系就也得单独重做了，仔细一想 这样的话 就没有必要用这个proTable组件了，要是全写request里 怎么写 还能触发查询，我还不知道怎么写。。

多条件查询? 类似级联那种么? 我这边暂时没有这种操作, 我从request里拿到搜索表单的数据后再重新处理数据, 就是那麻烦了点

**Comment by infinityboy** [comment]
那你这个改动的还不大，之前那个onChange 真的还挺好用的，处理完值 直接重新调用一次就好了

**Comment by infinityboy** [comment]
@fangzhengjin 那你这个改动的还不大，之前那个onChange 真的还挺好用的，处理完值 直接重新调用一次就好了，我这边自定义日期和区间那种也比较多，现在没有onChange 就有些头疼了

**Comment by infinityboy** [comment]
@chenshuai2144  有没有什么好的解决办法？？ 或者是允许重写onChange 方法 但是又能 触发查询的

**Comment by fangzhengjin** [comment]
降级坐等兼容方案 要改的地方太多了~

**Comment by infinityboy** [comment]
@fangzhengjin 那岂不是所有相关的依赖都要降级么？？

**Comment by fangzhengjin** [comment]
> @fangzhengjin 那岂不是所有相关的依赖都要降级么？？

那倒不会, 吧ProTable降级到2.1.11版本就行

**Comment by infinityboy** [comment]
@fangzhengjin 🆗 这也是不是办法的办法了

**Comment by chenshuai2144** [comment]
@fangzhengjin  可以直接用 form.getFliedValue 来实现你们的需求吧

**Comment by fangzhengjin** [comment]
> @fangzhengjin 可以直接用 form.getFliedValue 来实现你们的需求吧

怎么说呢? 搭配Form的onValuesChange使用, 单独维护一个变量存储表单信息吗?

**Comment by xclw2000** [comment]
真的是乱改一通，改了也不说明，首页帮助里面还是
(item,props:{value,onChange}) => React.ReactNode
这么写的呢。郁闷了半天，一升级，全是问题

**Comment by xclw2000** [comment]
我想到了一个办法，自己用form参数构建出value和onChange出来
`        renderFormItem: (item, _, form) => {
          const rest = {
            value: form.getFieldValue(item.key),
            onChange: (value) => {
              const newValues = {};
              newValues[`${item.key}`] = value;
              form.setFieldsValue(newValues);
            },
          };
          return <YourCustomComponent {...rest}/>;
        }`

目前没发现问题，可以正常使用。这样就不用降级了

**Comment by fangzhengjin** [comment]
> renderFormItem

nice 虽然麻烦点 自己写个函数 应该没问题

**Comment by vuvivian** [comment]
{
      title: '元素',
      dataIndex: 'elementTypeList',
      renderFormItem: (item, props, form) => {
        return <SelectCustom  // 自定义组件
          url="/findTypeList"  
          mode = 'multiple' 
          placeholder="请选择管控元素类别" 
          value = {form.getFieldValue(item.dataIndex)} // 手动赋值
          onChange = { (value) => {
            setSearchElementType(value);  // 自己的处理
            const newValues = {};
            newValues[item.dataIndex] = value;
            form.setFieldsValue(newValues); // 手动给form赋值
          }}
          />
      },
      render: (text, record) => {
        return record['elementType']
      }
    }

**Comment by MaskHao** [comment]
> 我想到了一个办法，自己用form参数构建出value和onChange出来
> 
> renderFormItem: (item, _, form) => {
> const rest = {
> value: form.getFieldValue(item.key),
> onChange: (value) => {
> const newValues = {};
> newValues[`${item.key}`] = value;
> form.setFieldsValue(newValues);
> },
> };
> return <YourCustomComponent {...rest}/>;
> }
> 
> 目前没发现问题，可以正常使用。这样就不用降级了

^2.7.2版本貌似没有效果，form.setFieldsValue，头大啊这

**Comment by MaskHao** [comment]
> 我想到了一个办法，自己用form参数构建出value和onChange出来
> 
> renderFormItem: (item, _, form) => {
> const rest = {
> value: form.getFieldValue(item.key),
> onChange: (value) => {
> const newValues = {};
> newValues[`${item.key}`] = value;
> form.setFieldsValue(newValues);
> },
> };
> return <YourCustomComponent {...rest}/>;
> }
> 
> 目前没发现问题，可以正常使用。这样就不用降级了

@fangzhengjin  form.setFieldsValue貌似在^2.7.2版本中也没得效果，头大啊这

**Comment by liuchuangjun321** [comment]
> onchange



> 换了新的实现方式，不需要使用 value 和 onchange 了，你需要这个有什么需求吗？

新的实现方式是什么呢？2.7.x版本也没有value和onchange了，如果需要做表单联动怎么处理呢？目前我看[官方文档](https://protable.ant.design/getting-started#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A1%A8%E5%8D%95%E9%A1%B9)还是采用的这种方式。@chenshuai2144

**Comment by danieldai** [comment]
> > 我想到了一个办法，自己用form参数构建出value和onChange出来
> > renderFormItem: (item, _, form) => {
> > const rest = {
> > value: form.getFieldValue(item.key),
> > onChange: (value) => {
> > const newValues = {};
> > newValues[`${item.key}`] = value;
> > form.setFieldsValue(newValues);
> > },
> > };
> > return <YourCustomComponent {...rest}/>;
> > }
> > 目前没发现问题，可以正常使用。这样就不用降级了
> 
> @fangzhengjin form.setFieldsValue貌似在^2.7.2版本中也没得效果，头大啊这

我试了试 在 2.43.1 中这个方法还是能用的。

```
renderFormItem: (item, _, form) => {
        const rest = {
          value: form.getFieldValue(`${item.dataIndex}`),
          onChange: (value) => {
            const newValues = {};
            newValues[`${item.dataIndex}`] = value;
            form.setFieldsValue(newValues);
          },
        };
        // @ts-ignore
        return <YourCustomComponent {...rest}/>
}
```
