### ISSUE TITLE
🧐[问题]pro-table样式能否不影响render函数渲染

### ISSUE THREAD

**Issue by Liu-Ya** [ant-design/pro-table#351]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
https://github.com/ant-design/pro-table/blob/5d90ba0161e318ac6a074f3d65219e340a21e4b2/src/index.less#L38-L42
此处代码会影响所有td内的<a>标签，希望能只影响valueType为option的col而不是所有

**Comment by chenshuai2144** [comment]
这个是设计师希望将 a 标签的点击面基变大才这么做的
