### ISSUE TITLE
🐛[BUG] 最新版的ProTable还是会出现列排序错位问题

### ISSUE THREAD

**Issue by fangzhengjin** [ant-design/pro-table#352]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
与问题 #315 相似
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
![image](https://user-images.githubusercontent.com/12680972/79420690-04eef500-7fec-11ea-9234-1c8889c06962.png)
### 🏞 期望结果 [描述你原本期望看到的结果]
无论列是否固定 都应该按顺序排列 如果固定 则按声明顺序固定排序
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
[![Edit protable-issues-352](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/protable-issues-352-wfvwi?fontsize=14&hidenavigation=1&module=%2Fdemo.tsx&theme=dark)
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by fangzhengjin** [comment]
因为直接使用antd的Table组件是没问题的, 能不能考虑加一个参数配置, 直接使用传入的定义数据不再进行单独的处理, 代价可以是舍弃右上角的列设置操作 @chenshuai2144

**Comment by mushroomlb** [comment]
`dataIndex: 'option,
valueType:  'option''`
这样就没有问题了

**Comment by fangzhengjin** [comment]
> `dataIndex: 'option, valueType: 'option''`
> 这样就没有问题了

就是所有计算出来的值都必须设置dataIndex呗

**Comment by chenshuai2144** [comment]
加一个key也可以，不然可能计算出问题
