### ISSUE TITLE
🐛[BUG]ProTable@2.2.1版本表头filter筛选查询控件查询不生效

### ISSUE THREAD

**Issue by longeweiyi** [ant-design/pro-table#353]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
ProTable@2.2.1版本表头filter筛选查询控件，点击确定时不能触发request（获得 dataSource 的方法）查询回调方法
### 🏞 期望结果 [描述你原本期望看到的结果]
ProTable的columns表头的filter删选功能点击确定后能触发request（获得 dataSource 的方法）查询回调方法
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- ProTable@2.2.1
- 浏览器环境 Chrome
- 开发环境 windows

**Comment by chenshuai2144** [comment]
这个需要自己去实现了，table 的 onchange 中会有 filter，你可以将其填充到 params 中
