### ISSUE TITLE
🐛[BUG]pro-table@2.2.1表头filter点击重置按钮不能触发onChange回调

### ISSUE THREAD

**Issue by longeweiyi** [ant-design/pro-table#357]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
pro-table@2.2.1版本表头filter筛选控件点击重置按钮不能触发onChange回调
### 🏞 期望结果 [描述你原本期望看到的结果]
pro-table@2.2.1版本表头filter筛选控件点击重置按钮能够触发onChange回调

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境 Chrome
- 开发环境windows10

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/40137747/79535554-62e51080-80b0-11ea-817b-b3a27ce29338.png)

**Comment by chenshuai2144** [comment]
这个的确是不触发的，需要自己用 onchange 来实现一下，暂时还没有最佳实践

**Comment by longeweiyi** [comment]
> 这个的确是不触发的，需要自己用 onchange 来实现一下，暂时还没有最佳实践

但是Table组件是可以触发的，ProTable点击重置如果不能触发onChange回调，那就没办法进行组件的dataSource更新了对不，我根本都没办法感知点击了重置按钮。而且@2.2.1版本选中过滤项后表头小漏斗也没点亮。在同时选中多个表头都过滤字段是，onChange回调中只能包含当前点击都那个过滤项的字段，不过这个可以自己处理。感觉这个块还是最好能处理一下，最起码和Table组件的处理保持一致
