### ISSUE TITLE
🧐[问题] 为什么 valueEnum的 key 只能是string

### ISSUE THREAD

**Issue by CGodX** [ant-design/pro-table#366]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
antd 组件select/radio这些主键的value都是any，为什么protable的valueEnum的 key 只能是string，number 都不能用，太难受了

**Comment by ghostg00** [comment]
+1

**Comment by mushroomlb** [comment]
可以在向服务器提交前做数据强制转换
```
await addMenu({
  ...fields,
  type:Number(fields.type),
})
```

**Comment by heyepeng** [comment]
你可以用number，但是最后也会转成string，因为对象的key本质是string

**Comment by zhangbc** [comment]
pro-table 怎么转换显示呀？比如字段status 当为1显示正常，为0显示异常，后台传来的是number，用valueEnum会报错。

**Comment by mushroomlb** [comment]
在protable的request中做转换
`request= { async(params) => {
  let dataList = await query(params);
  const data = dataList.data.map(item) => {
     return {
         ...item,
         type: String(item.type),
     }
  }
  dataList = {
    ...dataList,
   data,
  } 
  return dataList;
}}`

**Comment by chenshuai2144** [comment]
这是js object 的特性，除非使用 map，不然还是只能支持 string
