### ISSUE TITLE
使用了国际化组件 时间筛选依旧是英文的🐛[BUG]

### ISSUE THREAD

**Issue by lancelot1025** [ant-design/pro-table#367]
### 🏞 期望结果 [描述你原本期望看到的结果]
使用国际化组件后，搜索框时间搜索组件为中文显示

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
umi 的bug，已经修复了
