### ISSUE TITLE
🐛[BUG]moment.js:93 Uncaught TypeError: date.clone is not a function

### ISSUE THREAD

**Issue by abcnny** [ant-design/pro-table#368]
当protable 的columns含有valueType: 'date'的字段，字段类型为string，比如值为2020-04-08，当protable的type="form"时，表单出不来，报以下错误:
![image](https://user-images.githubusercontent.com/7876570/79850078-fa6e9a00-83f5-11ea-8f87-fefa09a36eaf.png)

**Comment by chenshuai2144** [comment]
看看的依赖安装把，是不是装了多个版本

**Comment by liangxp** [comment]
这个最后怎么解决的呢？我也遇到相同问题了，是装了多个版本？我查看我并没有多个版本

**Comment by AdamDocherty** [comment]
I have this issue as well :(

**Comment by abcnny** [comment]
<code>
import moment from 'moment';
const dateValue =moment(dateValue );

</code>
时间长了，我记得应该是在protable 的request里面
对请求返回后的日期数据再进行上面的加工，最后返回tabledata

**Comment by waylon-gmail** [comment]
https://github.com/ant-design/pro-table/issues/279#issuecomment-706567626

**Comment by ChestnutNeko** [comment]
string类型转为moment类型
