### ISSUE TITLE
🐛[BUG]设定表格密度后，无法使用toolbar中密度控件再次调节

### ISSUE THREAD

**Issue by IIIThSoul** [ant-design/pro-table#369]
[使用文档示例](https://protable.ant.design/example)，如代码所示，在组件初始化时设定好表格密码后，使用toolbar中的密度条件控件，表格将无法调节密度

![image](https://user-images.githubusercontent.com/10285557/79934166-79aaaf00-8484-11ea-80b7-13f591b8b0e9.png)

- Ant Design Pro 版本: 4.1.0
- umi 版本：3.1.1
- 浏览器环境：Chrome
- 开发环境 ： Windows

**Comment by chenshuai2144** [comment]
他是受控的，需要配合 onSizeChange 设置
