### ISSUE TITLE
🧐[问题]request失败返回无data字段时渲染报错

### ISSUE THREAD

**Issue by zlyyyy** [ant-design/pro-table#370]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
request失败返回无data字段时表格无法渲染报错，在request返回data设置默认值可以解决，但多个页面要重复写多次，这是bug还是原本就这样考虑的
```javascript
{
 "code":401,
 "message":"token失效，请重新登录"
}
```
![image](https://user-images.githubusercontent.com/22760932/79936153-3e5eaf00-8489-11ea-92eb-427396a42b3f.png)
![image](https://user-images.githubusercontent.com/22760932/79936384-e7a5a500-8489-11ea-9edd-91b560d78216.png)

### © 版本信息

- @ant-design/pro-table: 2.1.11
- 开发环境 [e.g. mac OS]

**Comment by WuJiY** [comment]
需要默认个空数组

**Comment by zlyyyy** [comment]
@WuJiY 是的，但多个地方用的话不通过后台给的话，前台就要每个地方都要写一遍，封装函数统一处理的话可以，但是我想protable内部设置默认值是否可以解决这个问题

**Comment by zhangbc** [comment]
对request={(params) => query()}如何改装？

**Comment by zlyyyy** [comment]
@zhangbc 我是这么处理的
```javascript
request={async (params = {}) => {
 const res = await query(params);
 const { data = [], total = 0, current = 1, pageSize = 10 } = res || {};
 return {
   data,
   current,
   pageSize,
   success: true,
   total,
 };
}}
```

**Comment by heyepeng** [comment]
貌似原来的版本没有这个问题，我是更新了以后才出现的

**Comment by mushroomlb** [comment]
直接改后端吧，按照新的格式返回数据

**Comment by zhangbc** [comment]
> @zhangbc 我是这么处理的
> 
> ```js
> request={async (params = {}) => {
>  const res = await query(params);
>  const { data = [], total = 0, current = 1, pageSize = 10 } = res || {};
>  return {
>    data,
>    current,
>    pageSize,
>    success: true,
>    total,
>  };
> }}
> ```

我修改修改返回成：
```typescript
current: 1
data: [,…]
pageSize: 10
total: 4
```

看了https://preview.pro.ant.design/list/table-list 数据格式一样，还是不行。

**Comment by zlyyyy** [comment]
> > @zhangbc我是这么处理的
> > ```js
> > request = { async（params  = {}）=> {
> >   const  res  =  等待 查询（参数）；
> >  const { 数据 = []，总计=  0，当前=  1，pageSize =  10 } = res || {};
> >  返回 {
> >    数据，
> >    当前，
> >    页面大小，
> >    成功： 对，
> >    总，
> >  };
> > }}
> > ```
> 
> 我修改修改返回成：
> 
> ```ts
> 电流：1个
> 资料：[，...]
>  的pageSize：10 
> 总：4
> ```
> 
> 看了https://preview.pro.ant.design/list/table-list数据格式一样，还是不行。

[https://github.com/ant-design/pro-table/issues/69](url)

**Comment by zlyyyy** [comment]
> > @zhangbc 我是这么处理的
> > ```js
> > request={async (params = {}) => {
> >  const res = await query(params);
> >  const { data = [], total = 0, current = 1, pageSize = 10 } = res || {};
> >  return {
> >    data,
> >    current,
> >    pageSize,
> >    success: true,
> >    total,
> >  };
> > }}
> > ```
> 
> 我修改修改返回成：
> 
> ```ts
> current: 1
> data: [,…]
> pageSize: 10
> total: 4
> ```
> 
> 看了https://preview.pro.ant.design/list/table-list 数据格式一样，还是不行。

[https://github.com/ant-design/pro-table/issues/69](url) 我之前参考这个写的，你可以看看有帮助不

**Comment by chenshuai2144** [comment]
现在已经好了，默认加了一个
