### ISSUE TITLE
🐛[BUG] Switch 控件警告

### ISSUE THREAD

**Issue by hanxinimm** [ant-design/pro-table#371]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

index.js:1 Warning: [antd: Switch] `value` is not a valid prop, do you mean `checked`? 
    in Switch (created by FormSearch)
    in FormSearch (created by ProTable)
    in ProTable (created by Context.Consumer)

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

表格列表包含 Switch 控件

### 🏞 期望结果 [描述你原本期望看到的结果]

valuePropName 已经添加正常不会提示警告

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

    {
      title: '状态',
      dataIndex: 'isEnable',
      valuePropName: 'checked',
      formItemProps: {
        valuePropName: 'checked',
      },
      render: (_text, record) => <Switch checked={record.isEnable} />,
      renderFormItem: item => <Switch />,
    },

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.1.4]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

hideInSearch: true, 增加这个属性后警告消失

**Comment by chenshuai2144** [comment]
` renderFormItem: item => <Switch checked={item.value} {...item}/>,`
这样写

**Comment by caijiang** [comment]
参数 item 没有携带onChange, 结果就是控件状态无法变化。

**Comment by hanxinimm** [comment]
@chenshuai2144 

这样写能行就见鬼了 

![image](https://user-images.githubusercontent.com/13499426/80445005-c9d2b700-8945-11ea-8b75-77ea5b18e280.png)

这样不行
     `renderFormItem: (item, config: { onChange?: (value: any) => void }) => <Switch {...config} />, `
这样也不行

`      renderFormItem: (item, config: { value?: any; onChange?: (value: any) => void }) => (
        <Switch {...config} />
      ),`

![image](https://user-images.githubusercontent.com/13499426/80445176-2e8e1180-8946-11ea-8efa-52ed7d39c145.png)

![image](https://user-images.githubusercontent.com/13499426/80445250-5c735600-8946-11ea-9af1-c852e311c66e.png)


而且如果 搜索表单用的是 Checkbox.Group

![image](https://user-images.githubusercontent.com/13499426/80445295-7b71e800-8946-11ea-876d-3f1c300b8ec1.png)

也会报这个错误

![image](https://user-images.githubusercontent.com/13499426/80445331-93496c00-8946-11ea-8567-7b9b7d5ce635.png)

**Comment by hanxinimm** [comment]
之前的版本都没有这个问题，升级以后，这个问题就爆发了
