### ISSUE TITLE
ProTable与Tabs结合使用，如何在切换Tabs时，重置PaoTable, request的current为1(即,请求数据为第一页的数据)🧐[问题]

### ISSUE THREAD

**Issue by wangwanli24** [ant-design/pro-table#372]

**Comment by chenshuai2144** [comment]
action.reset  可以重置table

**Comment by wangwanli24** [comment]
你们现在好像更新了，当业务场景是tabs与proTable结合使用时，切换tab状态，会自动重置protable--request的pageNum


| |
123
|
|
lakers34wwl@163.com
|
签名由网易邮箱大师定制


在2020年04月28日 10:26，陈帅<notifications@github.com> 写道：

action.reset 可以重置table

**Comment by qiansimin88** [comment]
@wangwanli24 怎么和tabs结合的啊 有没有代码 我被卡主了 哭
