### ISSUE TITLE
👑 [需求]

### ISSUE THREAD

**Issue by hanxinimm** [ant-design/pro-table#373]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]

renderFormItem 参数增加当前 render的类型，是 搜索框 render 还是 普通的表单 render

弹出的普通表单 是这样的
![image](https://user-images.githubusercontent.com/13499426/80054342-906b0780-8551-11ea-8238-7036ed9c509c.png)

目前搜索表单是 

![image](https://user-images.githubusercontent.com/13499426/80054466-ea6bcd00-8551-11ea-962a-c5d2d4ce9d7e.png)

但是我希望的搜索的表单是

![image](https://user-images.githubusercontent.com/13499426/80054434-d3c57600-8551-11ea-8c12-2b865077053a.png)

### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]

增加当前render对象类型的参数，以便用户区别对待

**Comment by chenshuai2144** [comment]
可以利用第二个参数中 的 type 来进行判断

```
renderFormItem?: (
    item: ProColumns<T>,
    config: {
      value?: any;
      onChange?: (value: any) => void;
      type: ProTableTypes;
      defaultRender: (newItem: ProColumns<any>) => JSX.Element | null;
    },
    form: Omit<FormInstance, 'scrollToField' | '__INTERNAL__'>,
  ) => JSX.Element | false | null;
```
