### ISSUE TITLE
table表格溢出，css样式覆盖了都不生效。

### ISSUE THREAD

**Issue by yyhuaisha** [ant-design/pro-table#374]
![image](https://user-images.githubusercontent.com/13938131/80057977-84377800-855a-11ea-9bce-039c27fcd1ce.png)

表格内容溢出，td里面的内容不会自动换行。现在的自动换行是我设置了td的最大宽度，但是整个table不能自动适应页面，这是怎么回事呢？我还设置了table的max 为100%，table外层的div也就和页面一样宽。
我看官网缩放页面的时候是可以自动适应的，但是我的项目缩放页面的时候，td宽度一直固定不变。官方图如下。
![image](https://user-images.githubusercontent.com/13938131/80058108-f90ab200-855a-11ea-9ffd-3b20fedb67dc.png)

**Comment by chenshuai2144** [comment]
需要修改display，你可以审查元素看看官网的样式。
```

@media (max-width: @screen-xs) {
  .ant-table {
    width: 100%;
    overflow-x: auto;
    &-thead > tr,
    &-tbody > tr {
      > th,
      > td {
        white-space: pre;
        > span {
          display: block;
        }
      }
    }
  }
}

```
