### ISSUE TITLE
2.2.1版本pageSize从默认的20切换到10的时候会报警告🧐[问题]

### ISSUE THREAD

**Issue by ray1347227** [ant-design/pro-table#379]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
官方示例如果从默认pageSize为20的时候切换到其他页码，再把pageSize切换到10，然后切换其他页码，就会导致不触发request

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/21354564/80173799-78fc4f00-8623-11ea-946b-a38ddbaacf14.png)

**Comment by ray1347227** [comment]
官方示例如果从默认pageSize为20的时候切换到其他页码，再把pageSize切换到10，然后切换其他页码，就会导致不触发request

**Comment by dream-approaching** [comment]
同遇到 请问解决了吗
