### ISSUE TITLE
🐛[BUG]在Redux中拿数据，UI界面卡顿，无法接受

### ISSUE THREAD

**Issue by shengyiHuang** [ant-design/pro-table#381]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
在Redux中拿数据，UI界面卡顿，无法接受
const { dataObj } = this.props;
<ProTable
       .....
        dataSource={dataObj instanceof Array ? dataObj : []}
        tableAlertRender={false}
        columns={columns}
        rowSelection={{}}
      />
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0] "antd": "^4.1.1",
- umi 版本: "umi": "^3.1.0",
- 浏览器环境:Google Chrome
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
`dataSource={dataObj instanceof Array ? dataObj : []}`
你是不是数据量太大了，最好使用分页的方式
