### ISSUE TITLE
🐛[BUG]页面的标题一直是个url地址

### ISSUE THREAD

**Issue by abcnny** [ant-design/pro-table#382]
点击左侧菜单时，页面的标题一直是个url地址，需要在config.ts里写死title，不能自动生成

- 开发环境 [e.g. mac OS]
"@ant-design/icons": "^4.0.0",
    "@ant-design/pro-layout": "^5.0.8",
    "@ant-design/pro-table": "^2.2.0",
    "antd": "^4.0.0",
    "classnames": "^2.2.6",
    "lodash": "^4.17.11",
    "moment": "^2.24.0",
    "omit.js": "^1.0.2",
    "path-to-regexp": "2.4.0",
    "qs": "^6.9.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-helmet-async": "^1.0.4",
    "umi": "3.1.1",
    "umi-request": "^1.0.8",
    "use-merge-value": "^1.0.1"

**Comment by chenshuai2144** [comment]
title只支持string，你可以在layout中配置
将title变为string
