### ISSUE TITLE
🧐[问题]请问如何自定义查询表单的输入框宽度

### ISSUE THREAD

**Issue by w809694546** [ant-design/pro-table#385]
默认不设置的话所有input的宽度都是一定的，请问怎么设置每一个input或者时间查询，select的宽度呢

**Comment by chenshuai2144** [comment]
不建议设置宽度，统一的宽度更加美观

**Comment by chenshuai2144** [comment]
不支持设置的，是为了样式上的统一。

**Comment by x1nGoo** [comment]
@chenshuai2144 那所有查询条件的栅格也是不支持自定义吗?  
现在时间范围 和 输入数字所占的栅格一样, 时间范围的输入框值会显示不全

**Comment by zhoubaibai** [comment]
正常的搜索框一个格式没问题 像时间范围搜索框还是需要有自定义的功能吧，不然分辨率稍微低一点就遮住了。这样就不是美观的问题了，可以认为这就是个半成品...

**Comment by juxuny** [comment]
我在笔记本上操作，一行只能显示2个输入框，筛选条件多起来就有一大版输入框了
