### ISSUE TITLE
👑 [需求]希望增加手动运行request

### ISSUE THREAD

**Issue by xiashu421** [ant-design/pro-table#386]
### 🥰 需求描述 
  有时候，我们的table加载可能取决于某些先决条件。
  场景： 左侧有一颗部门树，右侧有一个部门人员列表（protable），需要在选中部门树后再执行部门人员列表的查询。

**Comment by abcnny** [comment]
这种应该自己可以判断，点击后，设置选中树的代码，列表查询的时候，如果选中树的代码不为空就查询，反之就不用查询

**Comment by qindj** [comment]
可以不用request，直接用datasource绑定，在部门切换的时候更新datasource

**Comment by chenshuai2144** [comment]
这种情况不需要request了用datesorce
