### ISSUE TITLE
在class  中使用actionRef  ts 提示错误怎么解决

### ISSUE THREAD

**Issue by zlfgege** [ant-design/pro-table#387]
actionRef={(e: any) => this.ref = e} 

使用 this.ref.reload()  
1.编辑器会标红提示 This expression is not callable.  No constituent of type 'ReactInstance' is callable.ts
2.但是代码运行正常 请问怎么定义去掉这个提示错误
[dictionary.zip](https://github.com/ant-design/pro-table/files/4536770/dictionary.zip)

**Comment by chenshuai2144** [comment]
简单一点的办法，是 as ActionType

麻烦一点是的使用 `React.createRef<ActionType>`

**Comment by zlfgege** [comment]
> 简单一点的办法，是 as ActionType
> 
> 麻烦一点是的使用 `React.createRef<ActionType>`

可以麻烦你贴段代码看看吗
