### ISSUE TITLE
🐛[BUG]Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by abcnny** [ant-design/pro-table#389]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
![image](https://user-images.githubusercontent.com/7876570/80343668-e06f0480-8898-11ea-8418-dde30adc5181.png)

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
protable 点击新建，弹出的form表单出，在自定义输入控件select中，输入任意字符，出现下拉菜单，报错
### 🏞 期望结果 [描述你原本期望看到的结果]
无报错
### 💻 复现代码 [部分代码片段如下]
<pre>

//HdmcSelect
import { Select, Spin, message } from 'antd';
// import debounce from 'lodash/debounce';
import React from 'react';
import { queryHddaInfo } from '@/pages/hdda/service';

const { Option } = Select;

interface Props {
  setValue: (value: any) => void;
  initValue: any;
}

export default class HdmcSelect extends React.Component<Props, any> {
  state = {
    data: [],
    value: /* this.props.initValue ? [this.props.initValue] : */ [],
    fetching: false,
  };

  fetchHdmc = async (value: any) => {
    let params: any = {
      pageSize: 10,
    };

    if (value) {
      params = { ...params, hdmc: value };
    }
    this.setState({ data: [], fetching: true });
    const result = await queryHddaInfo(params);
    if (result.code === 200) {
      const data = result.content.map((item: any) => ({
        text: `${item.hdmc}`,
        value: `${item.hdbh}`,
      }));
      this.setState({ data, fetching: false });
    } else {
      this.setState({ data: [], fetching: false });
    }
  };

  handleChange = (value: any) => {
    this.setState({
      value: [value],
      data: [],
      fetching: false,
    });

    this.props.setValue(value);
  };

  render() {
    const { fetching, data, value } = this.state;
    return (
      <Select
        showSearch
        labelInValue
        key="hdmc"
        value={value}
        placeholder="请输入并选择名称"
        notFoundContent={fetching ? <Spin size="small" /> : null}
        filterOption={false}
        /* onClick={(e) => {
          e.persist();
          this.fetchHdmc(null);
        }} */
        onSearch={this.fetchHdmc}
        onChange={this.handleChange}
        style={{ width: '100%' }}
      >
        {data.map((d: any) => (
          <Option value={d.value}>{d.text}</Option>
        ))}
      </Select>
    );
  }
}

</pre>
### © 版本信息
"@ant-design/icons": "^4.0.0",
    "@ant-design/pro-layout": "^5.0.8",
    "@ant-design/pro-table": "^2.2.2",
    "antd": "^4.0.0",
    "classnames": "^2.2.6",
    "lodash": "^4.17.11",
    "moment": "^2.24.0",
    "omit.js": "^1.0.2",
    "path-to-regexp": "2.4.0",
    "qs": "^6.9.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-helmet-async": "^1.0.4",
    "umi": "3.1.1",
    "umi-request": "^1.0.8",
    "use-merge-value": "^1.0.1"

**Comment by chenshuai2144** [comment]
看起来你的select 写的有问题，根据报错解决一下把
