### ISSUE TITLE
👑 [需求]支持分页参数名称自定义

### ISSUE THREAD

**Issue by duanshanchong** [ant-design/pro-table#39]
### 🥰 需求描述 [支持分页参数名称自定义]
建议支持对请求参数例如current的自定义，例如接口的请求参数为pageNum, 需要请求时手动讲current改为pageNum

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/71412450-a098d600-2688-11ea-8e76-801201130c91.png)
你是需要这个吗？

**Comment by duanshanchong** [comment]
目前我是这么做的，因为要多个列表查询，所以需要每个都这么过滤下，或者单独做个工具类来处理

**Comment by chenshuai2144** [comment]
功能是一样的，你可以做成一个 util 方法， 我这边要是支持这个 api，也是通过加一层过滤的方式来实现的

**Comment by keke122765** [comment]
返回的分页参数改怎么处理呢
![image](https://user-images.githubusercontent.com/44694221/71559286-37a1cb80-2a97-11ea-8725-b6b7a5f22557.png)

**Comment by chenshuai2144** [comment]
@keke122765  request 方法是你自己传入的，包装一下就好了

```
request={async params => {
  const data = await getData(params);
  return { list: data.data, ...data };
};}
```
