### ISSUE TITLE
👑 [需求] 为什么空的时候给用户默认加“-”，默认应该不要加“-”

### ISSUE THREAD

**Issue by kaoding** [ant-design/pro-table#394]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]

用户已经在使用了，为了和以前用户体验一致，我要在每个protable是，删除加“-”，
加这个功能需求是可以的，但不要默认加上，让用户自己来决定要不要加“-”

@chenshuai2144

**Comment by kaoding** [comment]
如果我有需要，我自己会加的，默认不要加了。

**Comment by chenshuai2144** [comment]
这个是设计师决定的，你可以来个pr，提供一个关闭的功能

**Comment by kaoding** [comment]
不做修改啊？
应该在 ProTableProps 里定义

**Comment by chenshuai2144** [comment]
传进去就好了
