### ISSUE TITLE
列拖拽排序之后有事件吗?怎么拿到拖拽之后的顺序保存到服务器

### ISSUE THREAD

**Issue by Amy-Tan** [ant-design/pro-table#398]
![image](https://user-images.githubusercontent.com/49202591/80552196-6d7c9f80-89f8-11ea-917d-dc30aebc3466.png)

**Comment by chenshuai2144** [comment]
https://protable.ant.design/example#%E5%8F%97%E6%8E%A7%E6%A8%A1%E5%BC%8F
看看这个

**Comment by supercat55** [comment]
例子中好像是之有固定列会有onColumnsStateChange的回调，拖拽排序不会有触发

**Comment by zhouyalongs** [comment]
> 例子中好像是只有固定列会有onColumnsStateChange的，拖曳排序不会有触发

有解决方案吗 难道要重写列设置?
