### ISSUE TITLE
🧐[问题] type为from类型时怎么传入默认数据？

### ISSUE THREAD

**Issue by likejie9502** [ant-design/pro-table#399]

**Comment by lpgph** [comment]
通过  form={{ initialValues: stepFormValues }}   
或fromRef

**Comment by likejie9502** [comment]
多谢

**Comment by gaohongwei** [comment]
能贴一下代码吗？文档里没看见initialValues啊。

**Comment by likejie9502** [comment]
@gaohongwei 代码就是上面那个
`form={{ initialValues: stepFormValues }}`

**Comment by gaohongwei** [comment]
> @gaohongwei 代码就是上面那个
> `form={{ initialValues: stepFormValues }}`

likejie9502， 你这是在自己建form， 不是使用pro-table的功能吧？

**Comment by likejie9502** [comment]
@gaohongwei 具体可以参考ant-design-pro table的新建功能，我这边是这么用的
```
 <ProTable<TableListItem, TableListItem>
      ...
      type="form"
      form={{ initialValues: stepFormValues(自己设置的初始值) }}
      ...
 />
```
