### ISSUE TITLE
🐛[BUG]数字类型为空时列无法识别

### ISSUE THREAD

**Issue by gguan** [ant-design/pro-table#401]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

之前用这种逻辑渲染一些列的内容
```
{
title: '状态',
dataIndex: 'soldAt',
align: 'center',
render: val => (val ? <Tag color="green"> 已售</Tag> : <Tag color="orange">待售</Tag>)`
}
```
现在soldAt表单永不视为空
这种重要逻辑修改请在change log提请用户 谢谢

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
可以用renderText 来判断一下
