### ISSUE TITLE
👑 [需求] 耦合太重了  建议拆分

### ISSUE THREAD

**Issue by lpgph** [ant-design/pro-table#402]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
将表格 搜索表单 编辑表单三者的数据全部放到一个columns中太重了 建议分离
对于一般来情况来说可以满足使用 但是改动 以及拓展太麻烦了
### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
搜索表单和表格整合在一起  参数分离 搜索表单查询条件和表单columns传递一样 ，参数中可以设置验证，错误信息等，可以将部分表单的属性放到整合属性中

编辑表单可做可不做，如果做也是类似表格方式 通过类似columns的参数传递  可以设置验证 允许选择表单组件排列方式（紧凑或整行）

**Comment by FinchJohnRen** [comment]
赞同 搜索表单仅仅是列表中的搜索条件是不够的

**Comment by johnnylc** [comment]
同意 特别是搜索表单经常会出现表单项之间的联动、验证等需求，导致搜索表单的页面逻辑与展示内容与table的column中差异较大且不存在强关联。
当前使用中，我是将table中展示的column与search中的column分开定义，比如table中的column会设置hideInSearch, search中单独设置hideInTable，最后动态拼接作为column传入。这块内容单独作为一个模块配置操作可能更加灵活方便。
编辑表单对排版布局往往有更高的要求，当前方案很难做到全面，也无需做到全面。基础的antd form以及表单库formily，form-render可能会是更好编辑表单解决方案。

**Comment by chenshuai2144** [comment]
这个本来就不是为了满足所有的需求，他只能满足很窄的 中后台用户，你们的需求应该使用 antd  的table

**Comment by lpgph** [comment]
那么为什么不能做的更好,更通用一点呢?   而且,从设计的角度上讲，将三个模块放到一个columns中去处理确实是很麻烦的

**Comment by chenshuai2144** [comment]
不打算做通用的 你有兴趣可以自己搞一个 开源的东西 直接copy 都没事的

**Comment by lpgph** [comment]
恩 好吧 目前使用的是已经在此思路上实现的组件  开源考虑吧  前端的这块接触的不多

**Comment by lirenhao** [comment]
我觉的可以抛弃这个项目了，要么就大而全要么就小而精，摇摆不定只会走向消亡，再说了国内大都996了谁还有精力去维护开源都项目，建议关闭这个项目吧，不要误导新手了
