### ISSUE TITLE
🧐[问题] 如何不使用 request 属性，使 ProTable 变成一个受控组件？

### ISSUE THREAD

**Issue by Calerme** [ant-design/pro-table#405]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

请求表格数据的方法被我封装成了一个 hooks，通过设置 dataSource 、pagination 确实可以控制 ProTable 的数据显示和页码切换工作，**但是查询和 toolBarRender 的刷新操作都不知道对应的触发事件是什么。**

**Comment by Calerme** [comment]
找到方法了：
1. 查询操作通过 onSubmit 来实现
2. toolBarRender 的 reload 操作通过 option 属性来实现。

**Comment by aaronxdd** [comment]
大佬，toolBarRender里面的怎么重新发起请求？带参数的那种，不是reload

**Comment by gh-xj** [comment]
> 大佬，toolBarRender 里面的怎么重新发起请求？带参数的那种，不是 reload

传函数给 Reload  就好
