### ISSUE TITLE
search 配置不生效

### ISSUE THREAD

**Issue by bowen-wu** [ant-design/pro-table#41]
` search ` 属性是否支持对象？传入对象不生效
![image](https://user-images.githubusercontent.com/33862944/71429923-08d8cd80-2704-11ea-9c68-86964d990ff9.png)
![image](https://user-images.githubusercontent.com/33862944/71429937-1d1cca80-2704-11ea-892d-5b52006ec07a.png)
上面两个图片存在歧义

**Comment by xiyionxiong** [comment]
true false 控制显示与否

**Comment by chenshuai2144** [comment]
还没发版本，但是已经合并进来了

**Comment by chenshuai2144** [comment]
版本已发布
