### ISSUE TITLE
🐛[BUG]升级新版本以后 renderFormItem 返回Select，onSubmit 的时候取不到值

### ISSUE THREAD

**Issue by xiaopanghhh** [ant-design/pro-table#417]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
  
 renderFormItem  返回 Select 返回不了值

  onSubmit: (params: Q) => {
      debugger;
      if (setQuery) {
        setQuery(params);
      }
    },

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

renderFormItem: () =>
        <Select
          placeholder={formatMessage({id: `${MESSAGE_ID}.edit.resource-id.label`})}
          allowClear
        >
          {resourceDictionary?.map((value) => (
            <Select.Option key={value.key} value={value.key}>
              {value.label}
            </Select.Option>
          ))}
        </Select>

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by duwei54** [comment]
升级之后我也遇到这个问题
不知道是不是https://github.com/ant-design/pro-table/pull/393 这个pr导致
最后我的解决办法是:
```js
 renderFormItem: (item, {value, onChange}) => <Select value={value} onChange={onChange}allowClear />
```
期待官方给出兼容方案

**Comment by bianrenwei** [comment]
renderFormItem: (_, props) => {
        return (
          <Select {...props}>
          </Select>
        );
      },

**Comment by bianrenwei** [comment]
renderFormItem: (_, props) => {
return (
<Select {...props}>

);
},

**Comment by bianrenwei** [comment]
renderFormItem: (_, props) => {
return (
<Select {...props}>

);
},

加上  {...props} 试试

**Comment by chenshuai2144** [comment]
![Uploading image.png…]()

**Comment by duwei54** [comment]
> 升级之后我也遇到这个问题
> 不知道是不是#393 这个pr导致
> 最后我的解决办法是:
> 
> ```js
>  renderFormItem: (item, {value, onChange}) => <Select value={value} onChange={onChange}allowClear />
> ```
> 
> 期待官方给出兼容方案
官方已解决:
https://github.com/ant-design/pro-components/issues/409
