### ISSUE TITLE
form 是否能增加一行展示几个的配置，同时可以设置form默认是展示状态👑 [需求]

### ISSUE THREAD

**Issue by H5futurehreohanshuo** [ant-design/pro-table#42]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
1、现在form是一行三个，比如”名称“的筛选框并不需要那么宽，是否可以支持设置每行展示多少个搜索项，或者可以自定义设置每一个搜索项的宽度？
2、form 是否可以支持默认自动展开？

**Comment by chenshuai2144** [comment]
配置和 antd 的 col 是相同的

**Comment by Mu-xue** [comment]
请问具体是怎么配置的？

**Comment by vuvivian** [comment]
> col
在哪配置col

**Comment by liuhong1happy** [comment]
在哪配置col
