### ISSUE TITLE
🐛[BUG] 改变每页显示条数之后，翻页不走后台请求

### ISSUE THREAD

**Issue by majinkai** [ant-design/pro-table#420]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

切换页数之后更改每页单据数，数据展现有问题

PS：官方首页的demo就有这个问题

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

1. 先翻页到第二页
2. 切换每页显示条数为10条
3. 多翻几页，没有数据展示了
4. 也不再发起后端请求了

### 🏞 期望结果 [描述你原本期望看到的结果]

正常显示数据

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

官方首页demo就有这个问题

### © 版本信息

- Ant Design Pro Table 版本: 2.2.7
- umi 版本 3.1.1
- 浏览器环境 chrome
- 开发环境 mac OS

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![image](https://user-images.githubusercontent.com/3540799/81388483-eee7d680-914a-11ea-8d8a-4db480c64857.png)

![image](https://user-images.githubusercontent.com/3540799/81388503-f4ddb780-914a-11ea-9ddd-eedce5bd654a.png)

![image](https://user-images.githubusercontent.com/3540799/81388770-59007b80-914b-11ea-9407-985af560b9b7.png)

![image](https://user-images.githubusercontent.com/3540799/81388788-6289e380-914b-11ea-8c20-6f81e840a90a.png)

**Comment by ray1347227** [comment]
终于又有人提这个问题了

**Comment by majinkai** [comment]
在群里@了，不知道啥时候能解决呀

**Comment by majinkai** [comment]
> 终于又有人提这个问题了

又的意思是一直存在这个问题吗

**Comment by azx1985** [comment]
我也碰到了这个问题

**Comment by gameruleCEO** [comment]
> 在群里@了，不知道啥时候能解决呀

什么群，拉我
