### ISSUE TITLE
🧐[问题]想做到点击下一页就调用后台接口？如何后台分页？后台返回的总条数如何使用呢？

### ISSUE THREAD

**Issue by azx1985** [ant-design/pro-table#424]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
现在我用request调用了后台接口，返回了10条数据，和总数据条数，不知道如何设置，是不是pagination自己来重写呢？

**Comment by xiaopanghhh** [comment]
返回数据的结构是 
export interface RequestData<T> {
  data: T[];
  success?: boolean;
  total?: number;
}
将你的  10条数据放到  data 里面， 将总记录数放到  total  就好。
