### ISSUE TITLE
👑 [需求] 能否添加多语言

### ISSUE THREAD

**Issue by xiyionxiong** [ant-design/pro-table#43]
### 🥰 需求描述  

希望添加多语言，如搜索，重置，展开，收起 文案配置多语言，

### 🧐 解决方案  

开放对应的语言ID，例如 protable seach ='搜索'， 那么添加其他语言的时候，例如en， 则 protable seach = 'Search'.即可配置多语言效果

**Comment by xiyionxiong** [comment]
我看下到下个版本处理了 
`const defaultSearch: Required<SearchConfig> = {
  searchText: '查询',
  resetText: '重置',
  span: defaultColConfig,
  collapseRender: (collapsed: boolean) => (collapsed ? '展开' : '收起'),
};`
 但是 formitem的 placeholder的文案，希望能在ProColumns 添加自定义设置。例如 
`
 {
        title: trans('schooland schNo', 'School Code'),
        dataIndex: 'schCode',
        align: 'center',
        hideInSearch: true,
       placeHolder:xxx, // xxx 这里即可自定义配置多语言
      },
`
当然其他方案亦可。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-table/pull/45
https://github.com/ant-design/pro-table/pull/38

看两个 pr。应该可以满足你的需求了

**Comment by xiyionxiong** [comment]
> #45
> #38
> 
> 看两个 pr。应该可以满足你的需求了

可以 了，多谢。🙏
