### ISSUE TITLE
🐛[BUG]renderFormItem在request的params里面没办法获取值

### ISSUE THREAD

**Issue by azx1985** [ant-design/pro-table#430]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
renderFormItem在request的params里面没有获取搜索的值，重置可以清除值
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by Emmeet** [comment]
我今天遇到同样的问题

**Comment by ShawDanon** [comment]
renderFormItem自定的组件需要添加onchang事件才能取到值

**Comment by zhou-ting** [comment]
请问解决没有?遇到了同样的问题。如果解决了，麻烦回复一声，怎么结局的。谢谢了

**Comment by chenshuai2144** [comment]
你的 onchange 是不是没有附加上去？

**Comment by Emmeet** [comment]
> 请问解决没有?遇到了同样的问题。如果解决了，麻烦回复一声，怎么结局的。谢谢了
需要加onchange

**Comment by Emmeet** [comment]
> 你的 onchange 是不是没有附加上去
嗯，附加之后可以了

**Comment by sunsmeil** [comment]
什么叫onchange 没有附加上去

**Comment by xiejun** [comment]
> 什么叫onchange 没有附加上去

应该是在返回的element里添加onChange={config.onChange}吧
