### ISSUE TITLE
🐛[BUG]  翻页后 选中的rowSelection会丢失，官网多选例子也会出现这个问题

### ISSUE THREAD

**Issue by chenpeitao** [ant-design/pro-table#433]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
官方的多选操作也会有这个问题

地址：https://protable.ant.design/select

**Comment by taixw2** [comment]
数据更新时会调用 onChange([], [])，希望能够解决这个问题
https://github.com/ant-design/pro-table/blob/master/src/Table.tsx#L581

@chenshuai2144

**Comment by chenpeitao** [comment]
@chenshuai2144 能解决一下这个问题么，翻页selectedRows会清空

**Comment by chenpeitao** [comment]
@chenshuai2144 貌似还是有问题，我选择了第一页的数据，翻第二页后，变成了选择第二页的数据了

**Comment by chenshuai2144** [comment]
还没发版本吧

**Comment by chenpeitao** [comment]
那如果我现在需要修复，能自己修复么



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 陈帅 <notifications@github.com&gt;
发送时间: 2020年5月27日 10:48
收件人: ant-design/pro-table <pro-table@noreply.github.com&gt;
抄送: chenpeitao <844952631@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[ant-design/pro-table] [BUG]  翻页后 选中的rowSelection会丢失，官网多选例子也会出现这个问题 (#433)





 
还没发版本吧

**Comment by Liu-Ya** [comment]
@chenshuai2144 这个问题好像没有解决，示例中使用了本地分页，当使用后端分页时，翻页后change会清空之前的选择

**Comment by Liu-Ya** [comment]
![a](https://user-images.githubusercontent.com/23520283/82976239-2098e280-a011-11ea-896a-879c0db7fdd8.gif)
```tsx
<ProTable<ItemType>
          request={async (params = {}) => fetchImportLog(params)}
          rowKey="id"
          search={false}
          columns={columns}
          rowSelection={{ fixed: true }}
          toolBarRender={(_, { selectedRowKeys }) => [
            <Popconfirm
              title={`确定删除选中的${selectedRowKeys?.length}条记录吗？导入成功的订单将一并删除`}
              placement="topRight"
              onConfirm={() => {
                console.log(selectedRowKeys);
              }}
            >
              <Button disabled={!selectedRowKeys?.length}>删除</Button>
            </Popconfirm>,
          ]}
        />
```

**Comment by BigFaceMaster** [comment]
所以 大家的这个问题解决了吗？

**Comment by sunsmeil** [comment]
遇到一样问题 估计需要自己记录一下选中数组

**Comment by willdreame** [comment]
我也碰到这个问题了  请求后的数据 每次分页后 会丢失

**Comment by sillinbaby** [comment]
今天也遇到这个问题，如果antd的版本大于4.40，可以设置preserveSelectedRowKeys 这个属性，会保留之前的keys。

**Comment by luoxuemei123** [comment]
这个问题大家解决了吗，怎么处理的，我用preserveSelectedRowKeys 这个属性还是拿不到翻页前选择的数据
