### ISSUE TITLE
🧐[问题] ProTable type为form 日期设置初始值 不会正确渲染成date输入框 

### ISSUE THREAD

**Issue by ChenWeihua123** [ant-design/pro-table#434]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
使用ProTable 创建更新表单
通过form initialValues 初始值 其中传入了一个日期
但是 这样 表单只会渲染 成 input
传的日期需要什么特殊格式嘛
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
不赋初始值的话  正常渲染成 datePicker

**Comment by ChenWeihua123** [comment]
columns 的 valueType是 dateTime

**Comment by lizzie** [comment]
为啥关了，同遇到类似问题
