### ISSUE TITLE
🐛[BUG]查询条件的select加了onChange事件后，request拿不到参数

### ISSUE THREAD

**Issue by ray1347227** [ant-design/pro-table#441]
### © 版本信息

- pro-table版本 2.2.7
- umi 版本 3.1.1
- 浏览器环境 chrome
- 开发环境 [mac OS]

**Comment by chenshuai2144** [comment]
| renderFormItem | 渲染查询表单的输入组件 | `(item,props:{value,onChange}) => React.ReactNode` | - |
你要调用一下 props 里面的 onchange，组件才能知道你有值
