### ISSUE TITLE
🐛[BUG] 全屏按钮再 chrome  70版本无反应

### ISSUE THREAD

**Issue by zhangjianlin77** [ant-design/pro-table#444]
### 🏞 期望结果 [描述你原本期望看到的结果]
全屏按钮在 chrome  70版本有效，看源码 requestFullscreen 和 exitFullscreen没做浏览器兼容

- Ant Design Pro 版本: [4.0.0]
- umi 版本
- 浏览器环境 chrome 70版本
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
requestFullscreen 在 ie11 都支持的。70 也是支持的。应该是别的问题，比如你设置浏览器不让全屏什么的
