### ISSUE TITLE
分页的总结条不受国际化的控制

### ISSUE THREAD

**Issue by liny01-nbsa** [ant-design/pro-table#446]
https://github.com/ant-design/pro-table/blob/8284800c70b9930086eed53a95058f352fa1cd2b/src/Table.tsx#L303

**Comment by Emmeet** [comment]
![image](https://user-images.githubusercontent.com/27850090/82112918-5376e700-9784-11ea-8174-4b5339c39161.png)
![image](https://user-images.githubusercontent.com/27850090/82112929-65f12080-9784-11ea-9178-f5cc2ffa4606.png)

我选择自己定义一个配置

**Comment by liny01-nbsa** [comment]
多谢！我自己也写了个：
```typescript
const showTotal = (all, range) => {
  return [
    `${formatMessage({id: `page.range_prefix`})}`,
    range[0],
    '-',
    range[1],
    `${formatMessage({id: `page.range_suffix`})}`,
    '/',
    `${formatMessage({id: `page.total_prefix`})}`,
    all,
    `${formatMessage({id: `page.total_suffix`})}`,
  ].join(' ');
}
```
```typescript
...
  'page.range_prefix': 'Range',
  'page.range_suffix': ' ',
  'page.total_prefix': 'Total',
  'page.total_suffix': ' ',
...
```
中文也可以完美支持。
