### ISSUE TITLE
如何实现一个通用的表单（修改）组件？

### ISSUE THREAD

**Issue by gaohongwei** [ant-design/pro-table#448]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
ProTable作为通用表格很好用。
作为通用的增加表单， 也不错。

问题是它能不能用于修改表单？
如何传入原值？ 试了， 好像不行。

如果不行，能否提供一个通用表单方法？

其实，增加表单，修改表单， 他们应该是同一组代码，
区别只是，有没有缺省值。

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
这样试过，原值没有传入。
  const update_columns = [
    {
      title: '项目名称',
      dataIndex: 'name',
      form_type: 'text_input',
    },
    {
      title: '项目描述',
      dataIndex: 'desc',
      form_type: 'text_input',
    },    
  ];

const defaultData = [
  {name: 'project01'},
  {desc: 'project01 desc'},  
]

      <ProTable
        onSubmit={onSubmit}
        rowKey="key"
        type="form"
        columns={columns}
        defaultData={defaultData}
      />

**Comment by chenshuai2144** [comment]
你说的是默认值吗？

**Comment by gaohongwei** [comment]
我说的是原来的值，表单修改前各个列的值。

**Comment by chenpeitao** [comment]
我也想问这个

**Comment by chenpeitao** [comment]
这里解决了
https://github.com/ant-design/pro-table/issues/238

**Comment by gaohongwei** [comment]
谢谢 chenpeitao， chenshuai2144 。
