### ISSUE TITLE
🐛[BUG]引入pro-table会报错

### ISSUE THREAD

**Issue by aiyuchen** [ant-design/pro-table#450]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
版本号：2.2.8，目前最新版本，引入`pro-table`后会直接报错
>Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
直接引入，就可以在调试窗口看到错误

### 🏞 期望结果 [描述你原本期望看到的结果]
不报错

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
演示地址：
https://codesandbox.io/s/dreamy-jang-5wh7h?fontsize=14&hidenavigation=1&theme=dark
```
      <ProTable
        headerTitle="测试"
        pagination={false}
        dataSource={[]}
        columns={columns}
      />
```

### © 版本信息

- @ant-design/pro-table 版本: 2.2.8
- umi 版本 无
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS] codesandbox

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
<img width="1822" alt="C8856755-7BAE-45A4-AC80-BB227261580E" src="https://user-images.githubusercontent.com/578141/82201747-68de4380-9933-11ea-92ac-8618a1132fef.png">

**Comment by aikin-vip** [comment]
同样的问题

**Comment by HappyManYun** [comment]
https://github.com/ant-design/pro-table/issues/87

**Comment by nivin-studio** [comment]
同样的问题

**Comment by chenshuai2144** [comment]
fixed
