### ISSUE TITLE
👑 [需求] 对于Column的valueEnum，可以支持number作为key

### ISSUE THREAD

**Issue by icoderspace** [ant-design/pro-table#451]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
后端的valueEnum的Key是int型的，但是到绑定Column之后key只能是string类型。
带来的问题是在带filter请求request的时候是发回服务端的请求变成了，{"valueId":"1"}
这样服务端无法解析，因为后端的valueId类型是int，期望前端可以返回{"valueId":1}

### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
希望在valueEumn字段不要限制key的类型。

**Comment by heyepeng** [comment]
这个问题貌似前面的Issue已经解释过了，Enum是一个对象映射，对象的key为String类型，这个可以去看js对对象解释

**Comment by chenshuai2144** [comment]
有兴趣可以来个 pr，支持一下 Map
