### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by xliyq** [ant-design/pro-table#452]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
valueType: 'money'时表格中是人民币符号¥，搜索的地方却是美元符号$

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
![7](https://user-images.githubusercontent.com/5515880/82277533-b3ef6980-99ba-11ea-8403-5775857c359e.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
fix 非常好的issue
