### ISSUE TITLE
求助：pro-table 修改表单中动态dropdown 例子

### ISSUE THREAD

**Issue by gaohongwei** [ant-design/pro-table#455]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
求助：pro-table 修改表单中dropdown/radio 例子
1. 如何动态指定选项
3. 如何处理多个dropdown的相关性，比如，先选择国家，再选城市
2. 如何给dropdown/radio指定格式，比如，横向排列，纵向排列

**Comment by chenshuai2144** [comment]
https://protable.ant.design/search#%E8%A1%A8%E5%8D%95%E8%81%94%E5%8A%A8
看看这个demo
