### ISSUE TITLE
🐛[BUG]列设置的“固定到左边”和“固定到右边”有BUG，设置后多出空白列

### ISSUE THREAD

**Issue by ssyangtian** [ant-design/pro-table#457]
### 🐛 bug 描述 
pro-table的列设置的“固定到左边”和“固定到右边”有BUG，设置后多出空白列。

### 📷 复现步骤 
pro-table的列设置的“固定到左边”和“固定到右边”有BUG，设置后多出空白列，请看截图所示和版本信息。

### 🏞 期望结果
解决这个BUG；或者提供隐藏“固定到左边”和“固定到右边”这2个功能的方法。

### 💻 复现代码 
非TypeScript：
```<ProTable
              bordered={true}
              search={false}
              rowKey={record => record.id}
              loading={loading}
              dataSource={data ? data.list : []}
              pagination={data ? data.pagination : {}}
              columns={this.columns}
              onChange={this.handleBasicTableChange}
              options={{
                density: true,
                reload: () => {
                  this.handleSearch();
                },
                fullScreen: true,
                setting: true,
              }}
            />
```

### © 版本信息
- Ant Design Pro 版本:   2.0
- pro-table 版本：1.0.48
- antd 版本：3.26.17
- react 版本：16.8.6
- umi 版本： 2.8.20
- 浏览器环境：Chrome
- 开发环境：Windows

### 🚑 其他信息 
![image](https://user-images.githubusercontent.com/3403476/82438954-6e22c600-9acc-11ea-9015-2cbbd32f4f66.png)

**Comment by chenshuai2144** [comment]
来个重现的地址？
antd@4 换了实现方式几乎不可能出现这个问题

**Comment by ssyangtian** [comment]
> 来个重现的地址？
> antd@4 换了实现方式几乎不可能出现这个问题

看版本信息详细描述，antd 版本是 3.26.17，不是4

Ant Design Pro 版本: 2.0
pro-table 版本：1.0.48
antd 版本：3.26.17
react 版本：16.8.6
umi 版本： 2.8.20
浏览器环境：Chrome
开发环境：Windows

**Comment by chenshuai2144** [comment]
antd@3 你需要自己手动设置所有列的宽度，不然总是有问题的
