### ISSUE TITLE
🐛[BUG] 函数组件是不能获取refs

### ISSUE THREAD

**Issue by kaoding** [ant-design/pro-table#459]
**console.log 下报错误：大概的意思就是函数组件是不能获取refs**

![image](https://user-images.githubusercontent.com/18542211/82534977-b7c8ea80-9b78-11ea-9072-0c48fe3ebf7d.png)

**Comment by Sivan-Wu** [comment]
遇到了同样的问题，请问解决了吗

**Comment by ReliaMM** [comment]
遇到了同样的问题，请问解决了吗

**Comment by kaoding** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
升级到最新版本就好了，类型写错了一次
