### ISSUE TITLE
🐛[BUG] 使用 render 的 action 时会无法触发 action.reload

### ISSUE THREAD

**Issue by arvinxx** [ant-design/pro-table#46]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

在 Pro-Table 中使用 render 的 action 时会无法触发 action.reload，热更新一下才能够触发

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

1. 直接打开页面，此时点击删除按钮无法触发action.reload；
2. 修改源代码，比如加一行空格之后，umi 进行热更新，页面热重载。再次点击删除按钮，此时将可以触发action.reload。

### 🏞 期望结果 [描述你原本期望看到的结果]

使用 render 的 action 任何时候均可正常触发。

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
```jsx
 {
      title: '操作',
      dataIndex: 'option',
      valueType: 'option',
      render: (_, record, index, action) => [
        <TableDropdown
          onSelect={async key => {
            if (key === 'delete') {
              const res = await remove(record._id);
              if (res) {
                action.reload();
              }
            }
          }}
          menus={[
            {
              name: '删除',
              key: 'delete',
            },
          ]}
        />,
      ],
    }
```
### © 版本信息

-  pro-table  1.0.24
- umi 版本 2.12.6
- 开发环境mac OS

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/c19e0b4f15ca57ffa516fe8f077f5d77c2aaf0b4/src/pages/ListTableList/index.tsx#L139

看看这里的写法
