### ISSUE TITLE
protablle里面的select如何实现多选的功能？

### ISSUE THREAD

**Issue by CodingZJ** [ant-design/pro-table#460]

**Comment by CodingZJ** [comment]
{
      title: '角色',
      dataIndex: 'roleIdList',
      hideInTable: true,
      hideInSearch:true,
      rules: [
        {
          required: true,
          message: '角色必填项',
        },
      ],
      renderFormItem: (item,props:{value,onChange}) => {
        console.log(item,'------1');
        console.log(props,'-----2');
        return <Select
        mode="multiple"
        style={{ width: '100%' }}
        placeholder="请选择"
        optionLabelProp="label"
        options={[
          {label:'1',value:'aa'},
          {label:'2',value:'bb'},
          {label:'3',value:'cc'},
        ]}
        // onChange={v=>{
        // console.log(rest,form,item)
        // console.log(v) 
        //     setRoleIdList(v)
        // }}
      />
      }
    },
通过renderFormItem | 渲染查询表单的输入组件 | (item,props:{value,onChange}) => React.ReactNode。
已经实现了多选，但是构建出来的from.但是这个roleIdList值无法绑定到from上，不知道如何操作,折腾了好久，求大佬指点
@chenshuai2144

**Comment by bambookai** [comment]
有实现吗

**Comment by VingoChen** [comment]
请问实现了吗

**Comment by chenshuai2144** [comment]
你们不看demo吗？
```tsx
 fieldProps={{
          mode: 'multiple',
        }}
```
![image](https://user-images.githubusercontent.com/8186664/101314412-72a9a300-3893-11eb-97aa-33945f999ac1.png)

**Comment by t880216t** [comment]
> 你们不看demo吗？
> 
> ```tsx
>  fieldProps={{
>           mode: 'multiple',
>         }}
> ```
> 
> ![image](https://user-images.githubusercontent.com/8186664/101314412-72a9a300-3893-11eb-97aa-33945f999ac1.png)

啊，真香！
