### ISSUE TITLE
🐛[BUG]request初次执行时，没有带form表单的initialValue

### ISSUE THREAD

**Issue by AproC0der** [ant-design/pro-table#461]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
 {
    title: '状态',
    dataIndex: 'state',
    initialValue: 'open',
    valueEnum: {
      all: { text: '全部', status: 'Default' },
      open: {
        text: '未解决',
        status: 'Error',
      },
      closed: {
        text: '已解决',
        status: 'Success',
      },
    },
请求只有只有分页参数
https://proapi.azurewebsites.net/github/issues?current=1&pageSize=20
### 🏞 期望结果 [描述你原本期望看到的结果]
https://proapi.azurewebsites.net/github/issues?current=1&pageSize=20&state=open
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by fujinjun** [comment]
@chenshuai2144  并不行，现在只是带form.initialValues，并没有带Column配置的 initialValue

**Comment by fandepeng1993** [comment]
all 是关键字  我也发现这个问题，valueEnum: {
        // 'Success' | 'Error' | 'Processing' | 'Warning' | 'Default';
        'no': {text: '全部', status: 'Default'},
        'on': {text: '上线', status: 'Success'},
        'off': {text: '下线', status: 'Error'}
      }
不能有all关键字的
