### ISSUE TITLE
🧐[问题] 2.2.1 及之后版本用create-react-app创建的应用里出现TS1128错误

### ISSUE THREAD

**Issue by krypton100** [ant-design/pro-table#463]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
2.2.1 及之后版本在create-react-app创建的应用里出现TS1128错误，而在用umi创建的应用里则不会出现该错误
将```export type { ProTableProps, IntlType, ColumnsState, ProColumnsValueType, ProColumns, ActionType, RequestData, };```
中的`type`关键字删除后，错误消失，`export type {}`的语法是否有问题？

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/55964976/82771943-34591300-9e70-11ea-9268-ed37a0059078.png)

**Comment by chenshuai2144** [comment]
升级一下 babel 的版本呢？
https://github.com/babel/babel/issues/10981
已经支持了
