### ISSUE TITLE
🐛[BUG] Incorrect localization string for pagination

### ISSUE THREAD

**Issue by rchavik** [ant-design/pro-table#464]
Table shows Chinese localization strings even though we have changed the setting.

The demo page https://protable.ant.design/intl shows the same issue: 

![image](https://user-images.githubusercontent.com/39490/82788651-05a06400-9e93-11ea-9d3b-d140ae3c544c.png)

### Versions

- Ant Design Pro: none (using create-react-app)
- umi: none
- Firefox, Ubuntu 20.04 [e.g. mac OS]

**Comment by rchavik** [comment]
Seems that this issue is solved recently. Probably by 0debd5b99f1a334cc04684d41ce0f6aea00913a9.

I'll wait for 2.2.10

Thanks.

**Comment by chenshuai2144** [comment]
published
