### ISSUE TITLE
🧐[问题] How to use pro-table in a standard CRA project?

### ISSUE THREAD

**Issue by rchavik** [ant-design/pro-table#469]
### 🧐 I have add pro-table in a project, but the toolbar is missing any styles.

Is it possible to distribute the compiled CSS styles?

I prefer not to have to add ant-design-pro itself as I will not be using most of its features.  Also, I'd like to minimize the size of my work area. A brand new project started using pro-design complete template is a whopping 1.2G.

### 🚑 

![image](https://user-images.githubusercontent.com/39490/82808806-eb777d80-9eb4-11ea-88ef-0509d4e96aea.png)

**Comment by rchavik** [comment]
Seems solved by da6cbd53b2f5841332c62cb88363ef3f05f0b8eb. 

Amazing. First 2 issues created by me are actually solved in master branch.

**Comment by chenshuai2144** [comment]
published
