### ISSUE TITLE
👑 [需求] renderFormItem渲染的组件没有加入FormSearch

### ISSUE THREAD

**Issue by enrinku** [ant-design/pro-table#47]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]

我想替换掉默认的DatePicker，使用RangePicker，调试发现没有反应。debug查看一下form.getFieldsValue()获取到了Field但是value并没有值。

`{
      title: '上次调度时间',`
      `dataIndex: 'updatedAt',`
      `sorter: true,`
      `valueType: 'dateTime',`
      `renderFormItem: (text, props) => <RangePicker format='YYYY-MM-DD'/>
    },`

### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]

现在的解决方案是暂时用一个state传递数组到beforeSearchSubmit，想寻找更好的解决方案。

`renderFormItem: (text, props) => `
          `<RangePicker format='YYYY-MM-DD' locale={locale} `
          `onChange={(data, dateString) => this.getSearchRange(dateString)}/>`

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

本来考虑着用getFieldDecorator渲染组件，但是不知道怎么获取_ref3.form对象。

`renderFormItem: (text, props) => {form.getFieldDecorator(text.dataIndex, {})()}`

**Comment by chenshuai2144** [comment]
你的props 要 传给 RangePicker  不然 value 和 onChange 不存在。
