### ISSUE TITLE
🧐[问题]如何获取 form 值呢

### ISSUE THREAD

**Issue by ZengTianShengZ** [ant-design/pro-table#474]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
formSearch 做了一些查询，怎么手动获取这些 params 
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

![image](https://user-images.githubusercontent.com/15622519/82869248-82e5da80-9f60-11ea-9cca-4dc4a8d73175.png)

比如我填写了一些表单，环境， example_id ，我在弹窗要用这些表单值作为入参，但我没法手动获取到这些表单值

**Comment by chenshuai2144** [comment]
https://protable.ant.design/example#form-%E6%93%8D%E4%BD%9C
看这个
