### ISSUE TITLE
🐛[BUG]  pro-table表格用到ellipsis: true时，打开会卡顿

### ISSUE THREAD

**Issue by ssyangtian** [ant-design/pro-table#479]
### 🐛 bug 描述 
pro-table表格用到ellipsis: true时，打开会卡顿。

### 📷 复现步骤 
pro-table表格用到ellipsis: true时，打开会卡顿。

### 🏞 期望结果 
**提供优化方法，解决卡顿问题。**

### 💻 复现代码 
`
{
      title: formatMessage({ id: 'app.sysuser.email' }),
      copyable: true,
      ellipsis: true,
      dataIndex: 'email'
    },
`

### © 版本信息

Ant Design Pro 版本: 2.0
pro-table 版本：1.0.48
antd 版本：3.26.17
react 版本：16.8.6
umi 版本： 2.8.20
浏览器环境：Chrome
开发环境：Windows

### 🚑 其他信息 
![image](https://user-images.githubusercontent.com/3403476/82893401-82127000-9f83-11ea-90c8-374158922fdf.png)

**Comment by chenshuai2144** [comment]
ellipsis 设计到复杂浏览器 box 的计算，是会有一些卡顿，但是如果不频繁刷新帧率可以维持在60s左右。

如果对性能要求比较搞，可能需要搞搞虚拟化什么的

**Comment by shenjo** [comment]
@chenshuai2144 可以稍微具体讲讲怎么虚拟化吗，我也遇到了，只有十行数据，但是有三十多列，用了这个属性选中一条数据卡的不行
