### ISSUE TITLE
🐛[BUG] 固定到侧边（左边或者右边）出现在重叠（覆盖了不固定的列）和空白（固定的列原来地方出现）

### ISSUE THREAD

**Issue by kaoding** [ant-design/pro-table#48]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

![image](https://user-images.githubusercontent.com/18542211/71497901-32752e80-2895-11ea-85d9-cf1c3a3ce280.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
antd@3 的 固定列用起来有很多问题，在 4.0 的时候重构掉了。
如果你想使用这个功能，建议给所有的列都设置宽度

**Comment by Liu-Ya** [comment]
> 如果你想使用这个功能，建议给所有的列都设置宽度
> 
> antd@3 的 固定列用起来有很多问题，在 4.0 的时候重构掉了。期待 4.0

所有列都设置宽度时也会有问题，隐藏列比较多的时候撑不满屏幕还会有空白
4.0什么时候发release啊，第四季度马上过完啦

**Comment by chenshuai2144** [comment]
@Liu-Ya  beta 已经上线，可以用了

**Comment by Liu-Ya** [comment]
> @Liu-Ya beta 已经上线，可以用了

前天看next文档还没跟新，等会试试
