### ISSUE TITLE
🐛[BUG]通过columnsStateMap字段配置表格列固定定位在两侧，在组件刷新时固定列会回到原来列的位置

### ISSUE THREAD

**Issue by yjhtry** [ant-design/pro-table#483]
### 使用columnsStateMap字段配置表格列的显示和固定。显示隐藏正常。但是列的固定会在表格所在父组件刷新后回到未固定时的位置。(这里固定的列未在columns字段中配置fixed属性。经测试在columns中配置固定的列不会有这个bug
)
#### 1. `columnsStateMap={stateMap}`配置表格，stateMap是从接口拿过来的数据。初始化表格正常显示。如图：客户这一列被定位在左侧
![image](https://user-images.githubusercontent.com/39440537/82901702-e7b92900-9f90-11ea-8579-b277d28aa32f.png)

#### 2.进行页面中有setState的操作后定位失效并弹出警告，如下图
![image](https://user-images.githubusercontent.com/39440537/82902012-61511700-9f91-11ea-9a77-e9aab03a7cc7.png)

### © 版本信息

- @ant-design/pro-table: "2.2.1",
- Ant Design Pro 版本: ^4.0.0
- umi 版本 3.1.1
- 浏览器环境 chrome 81.0.4044.138（正式版本)
- 开发环境 win10

**Comment by yjhtry** [comment]
刚才测试发现是因为初始化columns写在了函数组件内部。
![image](https://user-images.githubusercontent.com/39440537/82904163-aa569a80-9f94-11ea-90b1-b089e46083ef.png)
但是如果不把columns的初始化方法写在内部，函数中的useState方法没办法使用

**Comment by chenshuai2144** [comment]
来个重新的 demo 吧，你这个可能比较复杂

**Comment by yjhtry** [comment]
@chenshuai2144 
`import React, { useState } from 'react';
import { Button } from 'antd'
import { PageHeaderWrapper } from '@ant-design/pro-layout';
import ProTable from '@ant-design/pro-table';

const state = {
  name:{ show: true },
  desc:{ show: true },
  callNo:{ show: true, fixed: 'left' }, // 默认调用次数固定在左边
  status:{ show: true },
  updatedAt:{ show: true },
  option:{ show: true },
}

const data = [
    {
      key: 1,
      name: `TradeCode1TradeCode1TradeCode1TradeCode1TradeCode1TradeCode1TradeCode1TradeCode1`,
      desc: '这是一段描述这是一段描述这是一段描述这是一段描述这是一段描述这是一段描述这是一段描述',
      callNo: Math.floor(Math.random() * 1000),
      status: Math.floor(Math.random() * 10) % 4,
      updatedAt: new Date(),
      createdAt: new Date(),
  }
]

// const columns = [...]
// 如果columns放在函数组件外部，组件刷新时，columns未重写，就不会出现下述情况

const TableList = () => {
  const [stateMap, setStateMap] = useState(state);
  const [refresh, setRefresh] = useState(undefined);

  // colums的初始化放在函数内部
  // 点击 刷新按钮，固定定位的列会回到原来位置
  const columns = [
    {
      title: '规则名称',
      dataIndex: 'name',
      width: 500,
    },
    {
      title: '描述',
      dataIndex: 'desc',
      width: 500,
      valueType: 'textarea',
    },
    {
      title: '服务调用次数',
      dataIndex: 'callNo',
      sorter: true,
      width: 200,
      hideInForm: true,
      renderText: val => `${val} 万`,
    },
    {
      title: '状态',
      dataIndex: 'status',
      hideInForm: true,
      width: 300,
      valueEnum: {
        0: {
          text: '关闭',
          status: 'Default',
        },
        1: {
          text: '运行中',
          status: 'Processing',
        },
        2: {
          text: '已上线',
          status: 'Success',
        },
        3: {
          text: '异常',
          status: 'Error',
        },
      },
    },
    {
      title: '上次调度时间',
      dataIndex: 'updatedAt',
      sorter: true,
      width: 300,
      valueType: 'dateTime',
      hideInForm: true,

    },
    {
      title: '操作',
      dataIndex: 'option',
      width: 300,
      valueType: 'option',
    },
  ];

  return (
    <PageHeaderWrapper>
      <Button onClick={() => setRefresh(!refresh)}>更新组件</Button>
      <ProTable
        headerTitle="查询表格"
        rowKey="key"
        scroll={{ x: 'max-content' }}
        columnsStateMap={stateMap}
        onColumnsStateChange={(map) => {
          setStateMap(map);
          return map;
        }}
        dataSource={data}
        columns={columns}
      />
    </PageHeaderWrapper>
  );
};

export default TableList;
`

**Comment by yjhtry** [comment]
> 来个重新的 demo 吧，你这个可能比较复杂


`import React, { useState } from 'react';
import { Button } from 'antd'
import { PageHeaderWrapper } from '@ant-design/pro-layout';
import ProTable from '@ant-design/pro-table';

const state = {
name:{ show: true },
desc:{ show: true },
callNo:{ show: true, fixed: 'left' }, // 默认调用次数固定在左边
status:{ show: true },
updatedAt:{ show: true },
option:{ show: true },
}

const data = [
{
key: 1,
name: TradeCode1TradeCode1TradeCode1TradeCode1TradeCode1TradeCode1TradeCode1TradeCode1,
desc: '这是一段描述这是一段描述这是一段描述这是一段描述这是一段描述这是一段描述这是一段描述',
callNo: Math.floor(Math.random() * 1000),
status: Math.floor(Math.random() * 10) % 4,
updatedAt: new Date(),
createdAt: new Date(),
}
]

// const columns = [...]
// 如果columns放在函数组件外部，组件刷新时，columns未重写，就不会出现下述情况

const TableList = () => {
const [stateMap, setStateMap] = useState(state);
const [refresh, setRefresh] = useState(undefined);

// colums的初始化放在函数内部
// 点击 刷新按钮，固定定位的列会回到原来位置
const columns = [
{
title: '规则名称',
dataIndex: 'name',
width: 500,
},
{
title: '描述',
dataIndex: 'desc',
width: 500,
valueType: 'textarea',
},
{
title: '服务调用次数',
dataIndex: 'callNo',
sorter: true,
width: 200,
hideInForm: true,
renderText: val => ${val} 万,
},
{
title: '状态',
dataIndex: 'status',
hideInForm: true,
width: 300,
valueEnum: {
0: {
text: '关闭',
status: 'Default',
},
1: {
text: '运行中',
status: 'Processing',
},
2: {
text: '已上线',
status: 'Success',
},
3: {
text: '异常',
status: 'Error',
},
},
},
{
title: '上次调度时间',
dataIndex: 'updatedAt',
sorter: true,
width: 300,
valueType: 'dateTime',
hideInForm: true,

},
{
  title: '操作',
  dataIndex: 'option',
  width: 300,
  valueType: 'option',
},
];

return (

<Button onClick={() => setRefresh(!refresh)}>更新组件
<ProTable
headerTitle="查询表格"
rowKey="key"
scroll={{ x: 'max-content' }}
columnsStateMap={stateMap}
onColumnsStateChange={(map) => {
setStateMap(map);
return map;
}}
dataSource={data}
columns={columns}
/>

);
};

export default TableList;
`

**Comment by weiTimes** [comment]
我也遇到了这个问题，移到外面确实可以，不过如果columns中有用到组件中定义的Hooks等方法呢，这个怎么传递过去呢
