### ISSUE TITLE
不知道里面的params是否可以动态改变不🧐[问题]

### ISSUE THREAD

**Issue by liuxuean** [ant-design/pro-table#491]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
我在开始时就设置了params 后，发现后面的请求参数都带上此初始化的数据，
不知道可以动态改变这个不
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
<ProTable<TableListItem>
  headerTitle="列表"
  actionRef={actionRef}
  rowKey="id"
  params={params}
  tableAlertRender={false}
  request={params => queryRule(params)}
  columns={columns}
  rowSelection={{}}
  pagination={{
    current: 2,
  }}
/>

**Comment by chenshuai2144** [comment]
可以的，params 改变还会触发 relaod

**Comment by liuxuean** [comment]
不行哦，一开始设置了params 的指定值后，后面的搜索就失效了，无法清除开始设置的params条件
