### ISSUE TITLE
🧐[问题]表单里是否可以定义可读列(不可修改)？

### ISSUE THREAD

**Issue by gaohongwei** [ant-design/pro-table#492]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

表单里是否可以定义可读列。
也许可以 在renderFormItem里面定义。但没找到文档。

**Comment by chenshuai2144** [comment]
可读列是什么意思？

**Comment by gaohongwei** [comment]
可读列是 指可读不可改， read only

**Comment by chenshuai2144** [comment]
https://ant.design/components/descriptions-cn/
我猜你要的是这个

**Comment by gaohongwei** [comment]
chenshuai2144  谢谢你回答我的问题。descriptions也可以。如果是能在From定义 Read Only field, Edit Record和 Show Record 则可使用同一组代码。

**Comment by chenshuai2144** [comment]
需要一个ProDescriptions

已从 Outlook Mobile<https://aka.ms/blhgte> 发送

________________________________
