### ISSUE TITLE
🧐[问题]columns中使用valueEnum,该项会自动生成filter?如何让filter不可见

### ISSUE THREAD

**Issue by beijibeijing** [ant-design/pro-table#497]
### 🧐 问题描述 
在columns中使用valueEnum，该项会自动生成filter?
如果不想要该怎么设置呢？
设置filterDropdownVisible为false时，点击那个漏斗图标确实不会出现弹窗。但是连漏斗都不想要该怎么处理呢？

### 💻 示例代码
 columns = [
    {
        title: '用户姓名',
        dataIndex: 'userName',
    },
    {
        title: '穷人',
        dataIndex: 'poor',
        filterDropdownVisible: false,
        valueEnum: {
            0: {
                text: '不是',
                status: 'Default',
            },
            1: {
                text: '是',
                status: 'Warning',
            },
        },
    },
]

**Comment by chenshuai2144** [comment]
`filter:undefined`

**Comment by beijibeijing** [comment]
filters:undefined
感谢~
