### ISSUE TITLE
🐛[BUG] toolBarRender function param: selectedRows incorrecttly superimposed on 2.2.9~ 2.3.1;

### ISSUE THREAD

**Issue by Nosnickers** [ant-design/pro-table#502]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
toolBarRender中selectedRows字段值,在已选中多行时,取值错误!
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
1. protable使用antd自带的rowSelection,并在toolBarRender中使用selectedRows
2. 逐个点击,只要超过两条,selectedRows会一直叠加!
### 🏞 期望结果 [描述你原本期望看到的结果]
在2.2.8版本是正常的
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
[重现地址](https://codesandbox.io/s/dumi-demo-5fzf6?file=/demo.tsx)
### © 版本信息
2.2.9里 这里不知为何要这么改
https://github.com/ant-design/pro-table/blob/9c7c4915ae4b77706a861334a0cc439f671342aa/src/Table.tsx#L773

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/8192906/83388221-a9a08700-a420-11ea-9212-8bc5735577cc.png)

**Comment by zhouzongren** [comment]
附议，toolBarRender属性 row参数中的selectedRows，每选择一次，都会把原来的值concat进数组。
可以用 Array.from(new Set(row.selectedRows)) 暂时修复

**Comment by chenshuai2144** [comment]
@zhouzongren  来个 pr？

**Comment by zhouzongren** [comment]
submitted


发自：周宗仁
On 6/5/2020 09:50，陈帅<notifications@github.com> wrote：

@zhouzongren 来个 pr？
