### ISSUE TITLE
👑 [需求]

### ISSUE THREAD

**Issue by lzbabd** [ant-design/pro-table#507]
### 🥰 需求描述 
能否提供一个字段(直接传入 ReactNode)可实现定制化的 search 表单? 

### 🧐 解决方案 
例如search 直接传入 ReactNode

### 🚑 其他信息
目前通过这样的方式实现了但全屏还是有点问题
![image](https://user-images.githubusercontent.com/15899833/83477582-2b96bb80-a4c6-11ea-870d-d7d061911efe.png)

![image](https://user-images.githubusercontent.com/15899833/83477382-b32ffa80-a4c5-11ea-8cb1-94fe2459c52f.png)
![image](https://user-images.githubusercontent.com/15899833/83477434-d0fd5f80-a4c5-11ea-8357-1b1a43285559.png)

**Comment by lzbabd** [comment]
#145

**Comment by chenshuai2144** [comment]
renderFromItem 这个api 可以解决这个问题
