### ISSUE TITLE
🧐[问题] 下拉选择后怎么触发查询

### ISSUE THREAD

**Issue by ZengTianShengZ** [ant-design/pro-table#510]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
下拉选择后还需要点击查询按钮才能触发查询，怎么在下拉选择后就出发table查询呢？
再顺带一个问题，怎么隐藏过滤功能

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
![image](https://user-images.githubusercontent.com/15622519/83706951-5f4f1e00-a64b-11ea-947c-ab5f334c969d.png)

**Comment by chenshuai2144** [comment]
https://protable.ant.design/example#form-%E6%93%8D%E4%BD%9C
看看这个例子
```tsx
const ref = useRef<FormInstance>();

ref.current.submit()

<ProTable<TableListItem>  formRef={ref} />
```

**Comment by ZengTianShengZ** [comment]
> https://protable.ant.design/example#form-%E6%93%8D%E4%BD%9C
> 看看这个例子
> 
> ```tsx
> const ref = useRef<FormInstance>();
> 
> ref.current.submit()
> 
> <ProTable<TableListItem>  formRef={ref} />
> ```

不太理解，而且例子也没效果

**Comment by ZengTianShengZ** [comment]
> https://protable.ant.design/example#form-%E6%93%8D%E4%BD%9C
> 看看这个例子
> 
> ```tsx
> const ref = useRef<FormInstance>();
> 
> ref.current.submit()
> 
> <ProTable<TableListItem>  formRef={ref} />
> ```

哦哦，了解了，对应的就是一个 form 表单，可以监听 form 事件

```
<ProTable<ITableListItem>
          formRef={this.refProTableForm as any}
          form={{ initialValues: formInitialValues, onFieldsChange: this.onFormFieldsChange }}
          rowKey="id"
          request={(params) => this.getData(params)}
          columns={this.columns}
          pagination={false}
        />
```
