### ISSUE TITLE
👑 [需求] request 的返回的params是乎不合理

### ISSUE THREAD

**Issue by okool** [ant-design/pro-table#511]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
之前写过类似GRUD的表格组件,升级后发现官方也了pro-table大致和我之前的组件一样.
有个疑问. params 实际由 search+filter+sorter+page+fields
pro-table把这几个属性都组合,通过'-',','等规则,合并成一个字段.
那么问题来了.
如果我的数据有一个叫"sorter","current","pageSize"字段就傻傻分不清除了.
### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
我的解决方案,前端组件是个中立的组件,不能要求后端接口,不能随意定些数据规范,比如用"-"来拼接.
不能限制用户使用字段,如我就喜欢在search定义一个"page"的字段.
组件返回标准的数组结构,开发人员自由组合传给后端服务.
如:我的设计.
params={
 search:{name:'张三',pageSize:[1,2,3]},
 filter:['status':[1,2,3],"sex":[1]],
 sorter:['created':'desc','name':'asc'],
 current:1,
 pageSize:20,
 field:['name','sex','created_at','updated_at','status']
}
 前端只需要重定义一下request方法就能自己给后端数据,如Post的Raw的json数据,GET方式的拼接querys.
无论后端使用什么规范都能适配.
### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![image](https://user-images.githubusercontent.com/9847324/83750504-f772f480-a697-11ea-8206-93ffe295cb74.png)

### 另外建议:
* 中立的组件,应该把常用的事件抛出来.
如: onSearch(onSubmit),onSorter,onFilter,onPageChage.
* FormField 使用反向,而不是使用hide用renderForm来或单独定义那searchFormFields.
建议,单独定义search:{fields:[{name:'username',roles:[],render()=>{return <Input />}}]}
由开发自己通过columns来生成searchFields或自己爱怎么定就怎么定.
* 同样CreateForm 和 UpdateForm 很鸡肋,实际项目都需要重写定义.
这个建议单独提供一个 EditForm 和 EditFormModal 组件来了来组合着用.
比如:
```jsx
<EditFormModal
    title="创建用户"
    fields={[{name:'username',default:'李四',rules:[],render()=>{return <input />}}]}
    data={{"name":"张三"}}
    onSubmit={(formData)=>{console.log('提交数据')}}
    onChange={(formItem,value,formData)=>{console.log('变化')}}
    onReset={(refForm)=>{console.log('重置');refForm.reset();}}
    onClose={()=>{console.log('关闭')}}
    extendRender={()=>{
       return <div>操作说明</div>
     }}
    submitBtn="保存"
    resetBtn="清空"
/>   
```
![image](https://user-images.githubusercontent.com/9847324/83753565-1b850480-a69d-11ea-8356-1c2416284a46.png)

**Comment by chenshuai2144** [comment]
你可以在 request 中自己做筛选的，这也是为什么放到第二个 第三个参数的原因
