### ISSUE TITLE
👑 [需求] search框valueEnum自动生成的Select， 可否加上可输入过滤下拉数据、multiple模式、联动功能

### ISSUE THREAD

**Issue by zhusongwen** [ant-design/pro-table#514]

**Comment by chenshuai2144** [comment]
在列配置中配置 formItemProps 来进行自定义，属性会透传到 select 上，只是没 ts 的支持了

**Comment by zhusongwen** [comment]
已测试可以了，谢谢

**Comment by CodingZJ** [comment]
{
      title: '库存状态',
      dataIndex: 'status',
      width:100,
      hideInTable:true,
      valueEnum: statusList,// 后端渲染的options
      formItemProps:{
        mode:"multiple"
      }
    },

**Comment by hedy2009c** [comment]
> 已测试可以了，谢谢

联动怎么实现，可以参考一下吗

**Comment by dream-approaching** [comment]
valueEnum自动生成的`Select`，如果想给`Option`设置`label` ，这样可以实现吗
