### ISSUE TITLE
👑 [需求] 如何让分页一直存在

### ISSUE THREAD

**Issue by leesama** [ant-design/pro-table#515]
@chenshuai2144 
帅哥，请问下如何让分页一直存在，现在发现就算total有值，如果没有数据，还是会隐藏分页

**Comment by leesama** [comment]
现在期望的是只要total的值正常，就能显示分页，而不是data没有数据就不显示

**Comment by leesama** [comment]
protable非常好用，现在就这个问题有点棘手

**Comment by chenshuai2144** [comment]
https://ant.design/components/table-cn/#%E5%A6%82%E4%BD%95%E5%9C%A8%E6%B2%A1%E6%9C%89%E6%95%B0%E6%8D%AE%E6%88%96%E5%8F%AA%E6%9C%89%E4%B8%80%E9%A1%B5%E6%95%B0%E6%8D%AE%E6%97%B6%E9%9A%90%E8%97%8F%E5%88%86%E9%A1%B5%E6%A0%8F

**Comment by leesama** [comment]
@chenshuai2144  已尝试过 无效

**Comment by leesama** [comment]
![image](https://user-images.githubusercontent.com/16167426/83863312-c0fbaf00-a755-11ea-8be8-413b5b785079.png)

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design/blob/4af818ca8e858375e37a7afc38bd0bf41b5b7af9/components/table/Table.tsx#L473

看来做不到的，antd 不支持
