### ISSUE TITLE
🐛[BUG]Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

### ISSUE THREAD

**Issue by zhusongwen** [ant-design/pro-table#517]
在开发模式下，ProTable 总是报错如下警告
devScripts.js:5035 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `ForwardRef(DensityIcon)`.
    in Dropdown (created by ForwardRef(DensityIcon))
    in ForwardRef(DensityIcon) (created by Trigger)
    in Trigger (created by ForwardRef(Tooltip))
    in ForwardRef(Tooltip) (created by Tooltip)
    in Tooltip (created by ToolBar)
    in span (created by ToolBar)
    in div (created by Space)
    in div (created by Space)
    in Space (created by ToolBar)
    in div (created by ToolBar)
    in div (created by ToolBar)
    in div (created by ToolBar)
    in ToolBar (created by Context.Consumer)
    in WarpToolBar (created by ProTable)
    in div (created by Card)
    in div (created by Card)
    in Card (created by ProTable)
    in div (created by ProTable)
    in LocaleProvider (created by Context.Consumer)
    in SizeContextProvider (created by Context.Consumer)
    in LocaleReceiver (created by ConfigProvider)
    in ConfigProvider (created by ProTable)
    in ProTable (created by Context.Consumer)
    in ErrorBoundary (created by Context.Consumer)
    in Provider (created by ProviderWarp)
    in ProviderWarp (at WorkPlan/index.tsx:258)
    in div (created by PageHeaderWrapper)
    in div (created by GridContent)
    in GridContent (created by PageHeaderWr

**Comment by chenshuai2144** [comment]
升级最新的版本就好了，这个已经修掉了

**Comment by calmcatcc** [comment]
最新版5.2.0开发模式下依然有这个问题
devScripts.js:6523 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
