### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by scootcho** [ant-design/pro-table#519]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
Language is set to `enUSIntl` but pagination is still in Chinese.

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
![image](https://user-images.githubusercontent.com/4122040/83938053-2e661900-a804-11ea-92d2-9bb3e0462f57.png)

### 🏞 期望结果 [描述你原本期望看到的结果]
desire result:
"records 1-7/ total 7 records"
better if customizable.

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

```
import ProTable, { ProColumns, IntlProvider, enUSIntl } from '@ant-design/pro-table';

const ExampleList: React.FC<{}> = () => {
  return (
    <PageHeaderWrapper>
      <ProTable<TableListItem>
        headerTitle="Example List"
        actionRef={actionRef}
        rowKey="key"
        ...
      />
      ...
    </PageHeaderWrapper>
  )
}

export default () => (
  <IntlProvider value={enUSIntl}>
    <TableList />
  </IntlProvider>
)
```

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

```
...
  "dependencies": {
    "@ant-design/pro-layout": "^5.0.8",
    "@ant-design/pro-table": "2.2.9",
    "antd": "4.2.5",
    "umi": "^3.1.2",
  }
...
```

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

Please enable i18n or change text in table footer.

**Comment by chenshuai2144** [comment]
look here https://github.com/ant-design/pro-table/pull/454
