### ISSUE TITLE
🧐[问题] form的时候，是否支持吧几个input 排成一排

### ISSUE THREAD

**Issue by zhangjunhou** [ant-design/pro-table#521]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
form的时候，是否支持几个input 几个input 排成一排
因为有些小的 没有必要一行
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
![image](https://user-images.githubusercontent.com/17563418/83947583-7871ed80-a84a-11ea-8b7a-22504d535e4a.png)

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/17563418/83947570-6b54fe80-a84a-11ea-9921-7b939979243e.png)

**Comment by Niofh** [comment]
@zhangjunhou zhangjunhou    这个怎么解决，找了很久没有找到
