### ISSUE TITLE
🐛[BUG] v2.3.2 中 valueEnum support map 导致过滤选项失效

### ISSUE THREAD

**Issue by kaoding** [ant-design/pro-table#522]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

表头过滤选项失效，search表单有过滤选项也失效。

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by kaoding** [comment]
https://github.com/ant-design/pro-table/pull/498

**Comment by kaoding** [comment]
经测试 map 支持也还是不行。

**Comment by blueandhack** [comment]
官方例子中的EnumType全部失效，目前都变成了空的
具体可见

https://codesandbox.io/s/gfybd?module=/demo.tsx&file=/demo.tsx
