### ISSUE TITLE
🧐[问题]pro table request 返回的格式要求是什么，哪里可以看到

### ISSUE THREAD

**Issue by xgj1988** [ant-design/pro-table#523]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
pro table request 返回的格式要求是什么，哪里可以看到，虽然查看mock 可以看到一些，但是是不是全部，不知道是否有文档，反正在官网找遍了，没找到

**Comment by karlspace7** [comment]
下载源码后搜索RequestDate，主要参数有3个：
data，泛型数组
success，是否查询成功
total，总记录数

**Comment by karlspace7** [comment]
下载源码后搜索RequestData，主要参数有3个：
data，泛型数组
success，是否查询成功
total，总记录数

**Comment by xgj1988** [comment]
@karlspace7  额，说到下载源码我就不问了

**Comment by chenshuai2144** [comment]
https://protable.ant.design/getting-started#%E8%AF%B7%E6%B1%82%E6%95%B0%E6%8D%AE

看看这个
