### ISSUE TITLE
👑 [需求]protable 的valueType是否可以支持 boolean，就用Switch，或者有什么办法可以自定义吗

### ISSUE THREAD

**Issue by xgj1988** [ant-design/pro-table#524]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
protable 的valueType是否可以支持 boolean，就用Switch，或者有什么办法可以自定义吗
### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
valueType支持bool，最好支持自定义。

**Comment by chenshuai2144** [comment]
支持用 renderFromItem 进行自定义的
