### ISSUE TITLE
👑 [需求]proTable 为valueEnum 的时候，Select没有clear。

### ISSUE THREAD

**Issue by xgj1988** [ant-design/pro-table#525]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
proTable 为valueEnum 的时候，Select没有clear。这样查询的时候必须要带上一个值，而且如果条件多了。我不可能点击重置。。
### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
所有的search 组件都应该带上clear。闭关是Input还是DatePicker，还是Select

**Comment by chenshuai2144** [comment]
来个 pr?

**Comment by xgj1988** [comment]
@chenshuai2144  大哥。。我是搞后端的，我怕写的代码不规范啊。。还有就是不支持Select比较可惜。

**Comment by chenshuai2144** [comment]
formItemProps 中配置 clear 就可以了

**Comment by pengzj** [comment]
@chenshuai2144  找了半天，formItemProps并不支持 clear，能否给出具体的使用说明。

**Comment by xgj1988** [comment]
@pengzj  2.4.0好像支持了。但是2.4.0如果用了onChange.要调用一下 属性里面的onChange方法。。

**Comment by pengzj** [comment]
@xgj1988  你好，能否给个例子呢？

**Comment by xgj1988** [comment]
@pengzj  好像又不行了。

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/98791564-345dc700-2440-11eb-9c6c-329ac9ad995f.png)


可以在fieldProps 里设置
