### ISSUE TITLE
这里忘记删除了

### ISSUE THREAD

**Issue by mushroomlb** [ant-design/pro-table#531]
https://github.com/ant-design/pro-table/blob/6f6feb4a289b3bf8c7ba0824559371fd57e3cf9c/src/Table.tsx#L492

**Comment by lvyuanying** [comment]
可以，你很细嘛

**Comment by mabelyong** [comment]
希望快点合并，要不然控制台很难看

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/pro-table/pull/530
