### ISSUE TITLE
👑 [需求]能否实现从其他页面返回列表以后保持原来的查询状态和数据？

### ISSUE THREAD

**Issue by zhusongwen** [ant-design/pro-table#534]
能否实现从其他页面返回列表以后保持原来的查询状态和数据？

**Comment by zhusongwen** [comment]
建议：search 提供一个initialValues属性， 可以把值初始到search form，带给request的params

**Comment by mabelyong** [comment]
这个也是我想要的

**Comment by chenshuai2144** [comment]
initialValues 是有的，和 antd@4 的是现实一样的。

> 能否实现从其他页面返回列表以后保持原来的查询状态和数据

这个可能需要 drawer了，不然存不住

**Comment by zhusongwen** [comment]
经测试form传initialValues可以实现初始化，问题已解决，谢谢
