### ISSUE TITLE
🐛[BUG]selectedRows 结果不对

### ISSUE THREAD

**Issue by pengzj** [ant-design/pro-table#539]
### © 版本信息

- Ant Design Pro 版本: 5.0.0-alpha.0
- umi 3.1
- chrome
- 开发环境 mac OS

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
<img width="1505" alt="Screen Shot 2020-06-10 at 8 24 01 PM" src="https://user-images.githubusercontent.com/6027468/84267342-7bc1ed80-ab58-11ea-950f-b6cee545ddfd.png">

**Comment by chenshuai2144** [comment]
fixed in https://github.com/ant-design/pro-table/releases/tag/v2.3.5
