### ISSUE TITLE
🐛[BUG] 秒要"小写"  YYYY-MM-DD HH:mm:ss

### ISSUE THREAD

**Issue by kaoding** [ant-design/pro-table#54]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

新增加的 defaultRender.tsx 中有时间格式，秒要"小写"
正确：YYYY-MM-DD HH:mm:ss
错误：YYYY-MM-DD HH:mm:SS

### 🏞 期望结果 [描述你原本期望看到的结果]

YYYY-MM-DD HH:mm:ss

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by kaoding** [comment]
@chenshuai2144 新增加的 defaultRender.tsx  秒也要"小写"，要不然秒就变成了魔幻数字了。

**Comment by chenshuai2144** [comment]
来个pr

**Comment by afc163** [comment]
close by #53
