### ISSUE TITLE
👑 [需求] 查询栏里支持AutoComplete

### ISSUE THREAD

**Issue by bambookai** [ant-design/pro-table#543]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
在查询栏里支持AutoComplete，方便搜索

**Comment by chenshuai2144** [comment]
https://protable.ant.design/getting-started#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A1%A8%E5%8D%95%E9%A1%B9

试试这个
