### ISSUE TITLE
🐛[BUG]column 的dataIndex如果是嵌套关系 ，导致form提交无法获取到数据问题。

### ISSUE THREAD

**Issue by xgj1988** [ant-design/pro-table#544]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
column 的dataIndex如果是嵌套关系,所以dataIndex的值为['dept','name']，那么这个column生成的查询框，里面放的是TreeSelect，提交的时候，居然得到的值为空。(beforeSearchSubmit里面打印出来)
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

1：选择查询条件里面的内容。
2：点击查询。
3：查看控制台，并没有获取部门的value值。
### 🏞 期望结果 [描述你原本期望看到的结果]

应该获取到部门的value值。
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

https://codesandbox.io/s/pro-table-sol55

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by xgj1988** [comment]
@chenshuai2144  大哥，来讲解一下

**Comment by xgj1988** [comment]
@afc163 大哥，这个是一个BUG吧。。

**Comment by chenshuai2144** [comment]
Value和onchange绑定了吗

**Comment by xgj1988** [comment]
代码就在上面的。还要绑定onchange的吗？？用form也没说要班定撒

**Comment by chenshuai2144** [comment]
现在有个自动绑定了
