### ISSUE TITLE
👑 [需求]如何修改search的form的label

### ISSUE THREAD

**Issue by xgj1988** [ant-design/pro-table#548]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
我想根据column 来生成 查询表单，但是有个问题，formItem的label是根据title来的。有什么办法设置label吗？我设置了 formItemProps:{label}，具体如下，
```
  {
      title: '名字',
      dataIndex: 'name',
      formItemProps:{label:'顶级菜单名字'}
    },
```
现在如果要实现我的需求，必须这样。
```
     {
      title: '名字',
      dataIndex: 'name',
      hideInTable: true,
    },
    {
      title: '顶级菜单名字',
      dataIndex: 'name',
      hideInTable: true,
    },
```
### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
为了避免和type的form生成的Item区别，建议在Column增加searchFormLabel属性

**Comment by chenshuai2144** [comment]
有兴趣来个 pr 吗？title 支持function，

`title: (type,defaultDom)=>ReactNode`

**Comment by xgj1988** [comment]
@chenshuai2144  大哥 。https://github.com/ant-design/pro-table/issues/544这个问题帮我看看啊。。

**Comment by xgj1988** [comment]
@chenshuai2144  title 是 column的属性？

**Comment by chenshuai2144** [comment]
给你写了个特供的 api。看看

**Comment by xgj1988** [comment]
谢谢

**Comment by luopeihai** [comment]
"@ant-design/pro-table": "2.2.7" type是underfind, 没有这个api 后面升级到 2.4.1才有
使用:
```
      title: (_, type) => (type === 'table' ? <span>提问者ID</span> : <span>提问者昵称</span>),
```
