### ISSUE TITLE
🧐[问题]valueType 是 dateTimeRange 时的使用问题

### ISSUE THREAD

**Issue by x1nGoo** [ant-design/pro-table#549]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
当column 里 valueType 使用 dateTimeRange时,
`{ title: "创建时间", dataIndex: "created_at", valueType: "dateTimeRange", width: "20%" },`
点击查询, 从F12 network header中看到 时间的参数名都是 created_at, 该怎么把字段名分开?

还有截图里最后那个_timeStamp 参数是怎么回事, 代码里没这个查询条件
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
https://codesandbox.io/s/dumi-demo-wew39?file=/demo.tsx
### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![image](https://user-images.githubusercontent.com/20261541/84615492-c0081180-aefb-11ea-8948-ff66347a2958.png)

**Comment by chenshuai2144** [comment]
https://protable.ant.design/getting-started#%E8%AF%B7%E6%B1%82%E6%95%B0%E6%8D%AE
看看这个文档
