### ISSUE TITLE
🐛[BUG] selectedRows数据量不正确，老是多一条

### ISSUE THREAD

**Issue by dmdoit** [ant-design/pro-table#556]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
table中我选中了2条，但是打印selectedRows时却显示有3条，selectedRowKeys是正确的

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
多选table数据， 在toolBarRender中打印selectedRows

### 🏞 期望结果 [描述你原本期望看到的结果]
期望数据量正确

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
<img width="832" alt="WeChat1df198eb2666c0f1dada21e43272a87f" src="https://user-images.githubusercontent.com/19385704/84883246-e3c98400-b0c2-11ea-815f-cc79cfb60f08.png">

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by yuhu-maxiang** [comment]
就你一个人出问题
