### ISSUE TITLE
👑 [需求]能否隐藏toolbar 部分，当作普通的table 使用 效果如下

### ISSUE THREAD

**Issue by xiyionxiong** [ant-design/pro-table#56]
### 🥰 需求描述 能否隐藏toolbar 部分，当作普通的table 使用 效果如下

![image](https://user-images.githubusercontent.com/14977994/71570278-4af07d80-2b0f-11ea-8983-ec356f597a43.png)

隐藏后的效果如下 ：
![image](https://user-images.githubusercontent.com/14977994/71570285-580d6c80-2b0f-11ea-857a-7edf555efeaf.png)

**Comment by chenshuai2144** [comment]
toolBarRender={false}

**Comment by xiyionxiong** [comment]
我给用成了 如下 然后不生效。。。。 糗大了。
```
toolBarRender={()=>false}
```
