### ISSUE TITLE
🐛[BUG]TreeSelect不能选择，在有onChange的时候

### ISSUE THREAD

**Issue by xgj1988** [ant-design/pro-table#567]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
TreeSelect onChange导致没有值显示。

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题
1：选择TreeSelect的值。
2：没有具体的文本内容。

### 🏞 期望结果 [描述你原本期望看到的结果]
1：应该文本框里面会显示出内容。

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://codesandbox.io/s/pro-table-2g4ue?file=/src/index.tsx

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by xgj1988** [comment]
复现代码地址 搞错了。。

最新的是：https://codesandbox.io/s/pro-table-2g4ue?file=/src/index.tsx。

选择TreeSelect的值，文本框没内容。。。2.4.0才有的。

**Comment by chenshuai2144** [comment]
可以的吧，我刚才看了看
