### ISSUE TITLE
🐛[BUG]dataIndex在嵌套属性的时候，语义有问题。

### ISSUE THREAD

**Issue by xgj1988** [ant-design/pro-table#569]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
1：当在查询的时候，我们的数据结构是。
```
{
username:'张三',
dept:{
      name:'部门1',
      id:'1'
    }
}
```
那么我们的column的dataIndex肯定是['dept','name']，但是我们查询的时候肯定又是根据dept.id来查询。。我给column设置formItemProps: { name: 'dept.id' }, 也无效。这种双重语义下面，改如何区别，是不是也要和title一样，根据table来判断？

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
点击查询，dept.name作为参数传递，
### 🏞 期望结果 [描述你原本期望看到的结果]
但是希望的是dept.id
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://codesandbox.io/s/pro-table-7vmf0
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
最好的办法

你用 renderText 改一下的。renderText={(_,row)=>row.data.id}

hack 的办法
你可以设置两个 一个是 data.name 但是 hideInSearch  ，在设置 data.id hideInTable
