### ISSUE TITLE
ts valueType 为 dateTimeRange时的类型问题

### ISSUE THREAD

**Issue by yedajiang44** [ant-design/pro-table#572]
如果列配置中某个配置项的valuetype为dateTimeRange，类型会被强制改为数组，此时由于泛型约束，又无法拿到集合，导致原本泛型中为string的属性，提交后变为string[]

**Comment by lxy0424** [comment]
这是不是时间类型或数据类型，用来按区间查询用 ？
我们也碰到类似的问题，后来直接增加　仅仅用于查询的列  ，比如说createTime字段
我们就增加两个查询字段，分别叫startCreateTime,endCreateTime ,

**Comment by yedajiang44** [comment]
@lxy0424 目前我也是这么干的，但是这样及其不友好

**Comment by shenjo** [comment]
在request中拿到参数了之后，自己转一下

**Comment by yedajiang44** [comment]
> 在request中拿到参数了之后，自己转一下

ts是有泛型约束的
