### ISSUE TITLE
🧐[问题]valueEnum枚举自定义色值没生效

### ISSUE THREAD

**Issue by Lnncoco** [ant-design/pro-table#575]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
open: {
          text: '未解决',
          status: '#2db7f5',
        }
这样使用自定义色值，但无法生效。是使用问题还是不支持？Geekblue这样的色值也无法显示

antd官网的Badge文档中色值用的是小写，但插件里面必须强制首字母大写才能生效。而且只支持其中部分色值显示

**Comment by chenshuai2144** [comment]
不支持自定义的，status是我实现的。你可以来个 pr
