### ISSUE TITLE
👑 [需求]希望选择器提供清空内容按钮

### ISSUE THREAD

**Issue by Lnncoco** [ant-design/pro-table#576]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
表格使用的是valueEnum，在顶部的搜索区也增加了搜索选项，但搜索框中的下拉选择框已选中之后就没办法删除已选中的值
希望能有清空内容按钮

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/57341815/85529781-ff430a80-b63f-11ea-9ba9-95cba26ed087.png)

**Comment by chenshuai2144** [comment]
这个默认加了

**Comment by pengzj** [comment]
@chenshuai2144  没有效果呀？

**Comment by pengzj** [comment]
确认 最新版本 2.4.2 里面已经支持这个feature了

**Comment by liuhong1happy** [comment]
怎么配置不需要清空内容的按钮呢

**Comment by chenshuai2144** [comment]
使用 fieldProps 里的clear 来设置
