### ISSUE TITLE
👑 [需求]Select表单在formItemProps的allowClear属性设置为true后，clear的Icon没有显示出来

### ISSUE THREAD

**Issue by yjhtry** [ant-design/pro-table#578]
### 🚑 其他信息
如图
  
![image](https://user-images.githubusercontent.com/39440537/85943463-d7ff7c80-b962-11ea-9a0d-25daafbd8b43.png)
代码 
![image](https://user-images.githubusercontent.com/39440537/85943477-e8aff280-b962-11ea-94f0-d430faca7ec1.png)

版本2.4.0

**Comment by yjhtry** [comment]
showSearch 的搜索图标也没显示出来

**Comment by shenjo** [comment]
我看了下代码，应该是这个6/20号的改动造成的,我手动把这个干掉就显示出来了
![image](https://user-images.githubusercontent.com/13912646/85944165-53632d00-b967-11ea-9f68-0e19a5fe354a.png)
@chenshuai2144

**Comment by yjhtry** [comment]
好的
