### ISSUE TITLE
👑 [需求]可否增加关闭搜索折叠功能？

### ISSUE THREAD

**Issue by zyb758** [ant-design/pro-table#58]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
能否增加一个属性，可以自定义打开还是关闭搜索栏的折叠功能。
* 选择打开的时候，和目前一样。
* 选择关闭的时候，显示出所有搜索选项，并隐藏折叠按钮。

谢谢！

**Comment by chenshuai2144** [comment]
应该不会做这种功能，你是希望解决什么问题

**Comment by zyb758** [comment]
![111](https://user-images.githubusercontent.com/3351079/71575402-c8c08300-2b27-11ea-805f-ec5237272829.jpg)
![222](https://user-images.githubusercontent.com/3351079/71575404-ca8a4680-2b27-11ea-9031-d0fe0d7bfe2b.jpg)

如图一有四列支持搜索，截图一里显示一行三列， 隐藏一列， 没问题。
截图二里，展开之后，显示一行四列。 只有一行， 但是还显示一个收起， 感觉很奇怪。

有的客户喜欢折叠，但是也有不喜欢折叠起来，就喜欢一次都显示出来的客户。

**Comment by chenshuai2144** [comment]
那你可能需要的是默认展开功能。

**Comment by zyb758** [comment]
对，默认展开也能满足需求。

**Comment by kaoding** [comment]
1. 有一些是希望可以展开，看到全部查询条件
2. 有的希望折叠起来，只看主要查询条件

**Comment by ousing9** [comment]
刚好在这里提一下，[值类型](https://protable.ant.design/value-type)这里展开之后的样式有点问题，我这显示器是2K的，Windows 10下缩放125%
![image](https://user-images.githubusercontent.com/32257773/71578067-92880100-2b31-11ea-81f1-fac1d87a3941.png)
