### ISSUE TITLE
🐛[BUG]文档中对submitText的描述和默认值有误

### ISSUE THREAD

**Issue by liaoyu6188** [ant-design/pro-table#588]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
API文档描述bug
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
https://protable.ant.design/api#columns
search里面的submitText属性描述和默认值让人费解
### 🏞 期望结果 [描述你原本期望看到的结果]
能给个demo，或者修正描述
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/31678719/86080937-ab647580-bac6-11ea-9f0f-b180e494e87e.png)

**Comment by chenshuai2144** [comment]
来个 pr？

**Comment by liaoyu6188** [comment]
已提pr

**Comment by chenshuai2144** [comment]
感谢你的 pr

💕
