### ISSUE TITLE
👑 [需求]分页是否可增加配置？现在没法开启QuickJumper

### ISSUE THREAD

**Issue by lixin0724** [ant-design/pro-table#589]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
目前分页不可配置，无法开启快速跳转，为何不增加此项配置呢？

**Comment by chenshuai2144** [comment]
是可以，你是怎么使用的？

**Comment by lixin0724** [comment]
![image](https://user-images.githubusercontent.com/53106140/87275739-5a666f80-c511-11ea-9c4b-7dad73422cf4.png)
![image](https://user-images.githubusercontent.com/53106140/87275722-520e3480-c511-11ea-8f9f-146586cd0615.png)
![image](https://user-images.githubusercontent.com/53106140/87275767-68b48b80-c511-11ea-8ebb-07716be90f08.png)
pagination其他配置项正常 但QuickJumper失效

**Comment by lixin0724** [comment]
> 是可以，你是怎么使用的？

抱歉 之前没看到您的回复。 我贴代码了。pagination其他配置项 showSizeChanger showTotal都能正常配置 但QuickJumper失效

**Comment by WynterDing** [comment]
showQuickJumper 
showQuickJumperL

亲，这两词是不同的
