### ISSUE TITLE
👑 [需求]建议增加搜索重置及选中重置功能！

### ISSUE THREAD

**Issue by birdycn** [ant-design/pro-table#59]
不知道目前是否支持，搜索表单重置调用，以及选中重置功能。

应用场景：
1、新增数据后，需要重置搜索表单，防止reload因搜索条件而无法及时显示新增后的数据，用户不友好。
2、删除数据后应重置选中key，防止toobar提示误导用户。

**Comment by chenshuai2144** [comment]
新增数据后， 和删除数据 table 都是不知道的，所以需要你去手工触发一下。
你可以用 formRef 重置表单，也可以用 selectKeys 来重置 toolbar

**Comment by birdycn** [comment]
@chenshuai2144 
感谢，formRef我再了解一下。目前我通过actionRef新增了一个handleSelected方法可以设置选中值，但toobar默认已有“清空选项”的按钮，是否可以考虑开放这个方法，

例如action.reload()  action.resetSelected()，因为组件内置可以清空选项，为何不考虑开放api。

**Comment by afc163** [comment]
@chenshuai2144

这就是为啥不建议去放开 action 的原因，有一个用户就会产生依赖而不去考虑使用属性。

**Comment by chenshuai2144** [comment]
resetSelected 不符合 react 的哲学，涉及到 ui 更新的应该尽量用 props。同样的输入应该展示同样的界
