### ISSUE TITLE
🧐[问题]request的参数中除了默认带有current,pageSize之外,原型链上还挂载了时间戳‘_timestamp’需要格外处理造成麻烦;

### ISSUE THREAD

**Issue by BluesVN** [ant-design/pro-table#594]
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/27759401/86211710-649b7c00-bba9-11ea-9458-936531371e55.png)
打印出requestData中会带有一个 ‘_timestamp’ 下划线开头本身也会触发代码检查报错;
其次往往在业务开发中,接口定义的字段不会按照ant框架的来,往往需要把_timestamp、current、pageSize这些字段去除掉或者重新加工一下,不能直接使用,违背了protable的设计初衷和设计原则;
![image](https://user-images.githubusercontent.com/27759401/86211861-990f3800-bba9-11ea-9e9c-9e42653fb2bf.png)

**Comment by WynterDing** [comment]
protable 的设计初衷就是大多数场景下的规则，我们生成约定好的模式给你。

绝大多数情况下，分页都是我们考虑的格式，你的需求可能还是要自己处理一下，暂不考虑支持。
