### ISSUE TITLE
👑 [需求]支持导出excel

### ISSUE THREAD

**Issue by xgj1988** [ant-design/pro-table#597]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
首先我认为这个组件很多地方都考虑到了。但是我想的是能不能支持导出excel，因为 这个需求实在是，实在是太常见了。可以结合react-html-table-to-excel这个来导出。而且这个导出支持类似request的请求，因为一般导出都是导出所有数据，而不是只是当前页面数据，当然也认为也可以支持只导出当前页面最好。可以和 react-html-table-to-excel 这个组件想结合。

### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
提供一个excel api ，比如
```
excel={{filename:"excel名字",sheetName:"sheet名字",currentPage:true|false,request:'http://localhost/test/data.json'}}
```

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
无

**Comment by qylc** [comment]
我们也需要这个功能

**Comment by xgj1988** [comment]
@qylc  常用功能。

**Comment by qylc** [comment]
我们自己倒是做了一个，但希望成为组件自带功能

**Comment by xgj1988** [comment]
@qylc  提交一个PR嘛。。
