### ISSUE TITLE
👑 [可否增加列设置（columnSetting）的回调，增加列设置的初始化选中配置]

### ISSUE THREAD

**Issue by libaofeng** [ant-design/pro-table#600]

**Comment by chenshuai2144** [comment]
https://protable.ant.design/example#%E5%8F%97%E6%8E%A7%E6%A8%A1%E5%BC%8F

你要的是这个

**Comment by sunsmeil** [comment]
> https://protable.ant.design/example#%E5%8F%97%E6%8E%A7%E6%A8%A1%E5%BC%8F
> 
> 你要的是这个

您的意思是自己定义配置区吗

**Comment by libaofeng** [comment]
是的，列设置完之后返回列设置的排序，可以入库。后来自己实现了下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/pro-table"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月30日(星期二) 晚上6:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/pro-table] 👑 [可否增加列设置（columnSetting）的回调，增加列设置的初始化选中配置] (#600)





  
https://protable.ant.design/example#%E5%8F%97%E6%8E%A7%E6%A8%A1%E5%BC%8F
 
你要的是这个
  
您的意思是自己定义配置区吗
