### ISSUE TITLE
👑 [需求]折叠起来的搜索表单项拿不到表单值

### ISSUE THREAD

**Issue by yjhtry** [ant-design/pro-table#607]
### 🥰 需求描述 因为表格的搜索条件比较多，故用户经常在添完搜索条件后，折叠搜索内容，在一屏内看到更多的搜索结果。但是这种方式会导致拿不到折叠起来的表单项的值。

版本2.4.0

**Comment by WynterDing** [comment]
和 #581 同一个问题，关注那个 issue 就好
