### ISSUE TITLE
🐛[BUG]使用了国际化组件 时间筛选依旧是英文的

### ISSUE THREAD

**Issue by MrMeiyu** [ant-design/pro-table#614]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

现在时间筛选还是英文的，并且主页的栗子上也是这样的

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/25768318/86988979-03d4fa80-c1cc-11ea-8fd5-08ba4bd7a956.png)

**Comment by chenshuai2144** [comment]
时间筛选器是 antd 控制的。
https://ant.design/components/config-provider-cn/

**Comment by MrMeiyu** [comment]
> 时间筛选器是 antd 控制的。
> https://ant.design/components/config-provider-cn/



> 时间筛选器是 antd 控制的。
> https://ant.design/components/config-provider-cn/

@chenshuai2144 您好，我在app入口定义过这个国际化的还是不行哦~请问这是为什么了？

**Comment by MrMeiyu** [comment]
> 时间筛选器是 antd 控制的。
> https://ant.design/components/config-provider-cn/

@chenshuai2144 您好，我在app入口定义过这个国际化的还是不行哦~请问这是为什么了？
