### ISSUE TITLE
国际化配置无法从外部传递进去

### ISSUE THREAD

**Issue by darkmice** [ant-design/pro-table#618]
@chenshuai2144 

> 可以用这个 https://ant.design/components/config-provider-cn/

用这个也不能生效，应该是   
https://github.com/ant-design/pro-table/blob/11c3709c7239ad0680537c04f6ff403848587d36/src/Table.tsx#L894-L898
这里定义了，所以外面定义的传不进来

_Originally posted by @darkmice in https://github.com/ant-design/pro-table/issues/204#issuecomment-656583730_

**Comment by chenshuai2144** [comment]
升级一下 antd 的版本，某一个 antd 的版本又 bug 导致不能继承，默认是继承的

**Comment by gaoweijun2018** [comment]
@chenshuai2144 
帅哥，我用react devtool调试,
cinfigProvider.ConfigConsumer的context的value只有getPrefixCls和renderEmpty

**Comment by gaoweijun2018** [comment]
只有protable的国际化有问题

**Comment by chenshuai2144** [comment]
@zombieJ cc

是不是不继承了

**Comment by zombieJ** [comment]
看看 antd 版本，存不存在多版本的情况

**Comment by gaoweijun2018** [comment]
@zombieJ 
antd 4.4.0
pro-table 2.4.0
umi 3.2.0

**Comment by zombieJ** [comment]
看起来是没问题的，给个 codesandbox 看看~

**Comment by MrMeiyu** [comment]
目前我也是这样子的情况
这是我的版本情况
![image](https://user-images.githubusercontent.com/25768318/87618265-098e8b00-c74c-11ea-9062-22b178acd2e7.png)

**Comment by darkmice** [comment]
我这边又自动好了，我之前的环境是 lerna bootstrap --hoist 模式，后面换成普通的lerna bootstrap 安装依赖，莫名其妙的又自动好了。
