### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by vedatkilic** [ant-design/pro-table#62]
Hi, 

It is possible to set placeholder text for search? Now, it is not suitable for i18n.

Thanks

**Comment by chenshuai2144** [comment]
https://protable.ant.design/example
look here

**Comment by vedatkilic** [comment]
Hi, I have, but I didn't get it how text is replaced. Is there a way to pass text for any language? For example Turkish?

**Comment by vedatkilic** [comment]
Thank you
