### ISSUE TITLE
👑 [需求]升级到最新2.4.2,首列缩进没有对齐

### ISSUE THREAD

**Issue by l745230** [ant-design/pro-table#623]
### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![image](https://user-images.githubusercontent.com/15940920/87381757-0a96af80-c5c8-11ea-90b4-651b55d63f00.png)

**Comment by l745230** [comment]
![image](https://user-images.githubusercontent.com/15940920/87381889-4e89b480-c5c8-11ea-80e8-594349eba11b.png)
小屏访问,最右边按钮没有pandding

还是就是,小屏访问时,headerTitle能不能支持隐藏掉.感觉显示效果很突兀

**Comment by chenshuai2144** [comment]
这个应该是你自己设置的 title right，不是 table 的问题

**Comment by l745230** [comment]
@chenshuai2144 并没有设置title right. 是受排序影响了
![image](https://user-images.githubusercontent.com/15940920/88245015-24bb4680-ccc8-11ea-9a82-9f798b5fce0e.png)
![image](https://user-images.githubusercontent.com/15940920/88245090-6c41d280-ccc8-11ea-9a22-48da96543c0e.png)

**Comment by l745230** [comment]
话说,这issue里提了3个小疑问...  回答了一句就关单子.. 这.....

**Comment by chenshuai2144** [comment]
升级一下最新版本看看  issue最好细一点
