### ISSUE TITLE
🐛[BUG] pageSize的change事件没有执行

### ISSUE THREAD

**Issue by MyPacker** [ant-design/pro-table#625]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
在分页器中将pageSize由10改成100，但是在 request 里 params 的 pageSize 还是10

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
test环境没有这个问题，但是staging稳定复现，我把本地代码回滚到test环境的版本之后发现本地也还是存在这个问题。所以排除了我本地逻辑的问题，这个是因为官方的npm包更新了吗？

### 🏞 期望结果 [描述你原本期望看到的结果]
pageSize改变

### © 版本信息
依赖版本信息
```
    "ant-design-pro": "^2.1.1",
    "antd": "^4.2.0",
    "umi": "2.13.0",
    "umi-plugin-antd-icon-config": "1.0.2",
    "umi-plugin-antd-theme": "1.2.0-0",
    "umi-plugin-pro-block": "1.3.2",
    "umi-plugin-react": "1.14.10",
    "umi-request": "1.0.8",
    "use-merge-value": "1.0.1"
```

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by leesama** [comment]
我也遇到该问题了
@chenshuai2144  帅哥来看看

**Comment by MyPacker** [comment]
> 我也遇到该问题了
> @chenshuai2144 帅哥来看看

我把antd版本固定了一下就好了：
去掉packagg前面的^符号
```
    "ant-design-pro": "2.1.1",
    "antd": "4.2.0",
```
你可以试试看

**Comment by leesama** [comment]
> > 我也遇到该问题了
> > @chenshuai2144 帅哥来看看
> 
> 我把antd版本固定了一下就好了：
> 去掉packagg前面的^符号
> ```
>     "ant-design-pro": "2.1.1",
>     "antd": "4.2.0",
> ```
> 你可以试试看

还是等修复吧。这也不是个办法呀

**Comment by leesama** [comment]
>     "ant-design-pro": "2.1.1",
>     "antd": "4.2.0",

我刚试了确实可以了， 但是console会有报错，影响到react-quills组件的运行了，还是得等修复

**Comment by chenshuai2144** [comment]
修复了
