### ISSUE TITLE
🧐[问题]表单中某个renderFormItem渲染多个组件，如何提交

### ISSUE THREAD

**Issue by guogeer** [ant-design/pro-table#626]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
表单中某个renderFormItem渲染多个组件，不知道如何提交Input.Group中的Select+Input的值
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
    {
      title: '关键字',
      dataIndex: 'key',
      hideInTable: true,
      renderFormItem: (item, { defaultRender, ...rest }) => {
        return <Input.Group {...rest} compact>
        <Select id='key' defaultValue='uid'>
        {
          Object.keys(gSearchKeys).map((v)=><Select.Option value={v}>{gSearchKeys[v]}</Select.Option>)
        }
        </Select>
        <Input id='value' style={{width:160}} />
        </Input.Group>
      },
    },

**Comment by guogeer** [comment]
看了下ant design表单。https://ant.design/components/form-cn/
![image](https://user-images.githubusercontent.com/5010851/87540214-db6c6500-c6d1-11ea-8535-6f4fb3439cf6.png)
有例子参考。已解决

**Comment by kcunitary** [comment]
> 看了下ant design表单。https://ant.design/components/form-cn/
> ![image](https://user-images.githubusercontent.com/5010851/87540214-db6c6500-c6d1-11ea-8535-6f4fb3439cf6.png)
> 有例子参考。已解决

请问一下，最后你是怎么传值给request的...我死活只能捕获到input的值
