### ISSUE TITLE
https://protable.ant.design/api 列子中报错

### ISSUE THREAD

**Issue by wxf-start** [ant-design/pro-table#631]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

![image](https://user-images.githubusercontent.com/37679380/87644622-f0530200-c77e-11ea-8553-265f334088d9.png)

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
![image](https://user-images.githubusercontent.com/37679380/87644553-da454180-c77e-11ea-8e24-23d9f468ca5e.png)

**Comment by chenshuai2144** [comment]
来个 pr

**Comment by WynterDing** [comment]
render 如果定义成数组的话，你需要给数组里每个 ReactNode 增加一个 key，不然就会有这个warn.
