### ISSUE TITLE
🧐[问题]column 如何输出html

### ISSUE THREAD

**Issue by pengzj** [ant-design/pro-table#632]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
column 有时候不是字符串 而是html 代码，需要 显示效果而不是源码， 求解
<img width="263" alt="Screen Shot 2020-07-16 at 10 26 11 PM" src="https://user-images.githubusercontent.com/6027468/87683362-8e60bf80-c7b3-11ea-88f3-63b221ca85af.png">

**Comment by chenshuai2144** [comment]
和 react 一样的用 dangerouslySetInnerHTML 

https://reactjs.org/docs/dom-elements.html
