### ISSUE TITLE
🐛[BUG]Setting valueType: "textarea" still uses input for search filter

### ISSUE THREAD

**Issue by phillip-mofadeng** [ant-design/pro-table#633]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
Setting valueType property of column to "textarea" renders normal input instead of textarea input in search filter 
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
Setting valueType property of column to "textarea"
### 🏞 期望结果 [描述你原本期望看到的结果]
Be able to render textarea input in search filter
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://codesandbox.io/s/mystifying-rgb-h6ux3?file=/demo.tsx
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
Only in the from mode will it be displayed as a text field. The default is an input. If you have any requirements, you need to display the untext field in the query form
