### ISSUE TITLE
🧐[问题] ProColumnType ts 语法错误

### ISSUE THREAD

**Issue by WangXiaoXiaoG** [ant-design/pro-table#635]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
columns 加入children的时候一直报ts语法错误

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

![image](https://user-images.githubusercontent.com/37679380/87745099-a0784780-c81f-11ea-85f1-006ac7e8199f.png)

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/37679380/87745076-922a2b80-c81f-11ea-954e-e4fa190ddf99.png)

**Comment by chenshuai2144** [comment]
用 `ProColumns`，ProColumnGroupType 和 ProColumnType 是不一样的
