### ISSUE TITLE
🐛[BUG] 2.4.3toolbar发生了位移，是新设计还是bug？

### ISSUE THREAD

**Issue by liujiayii** [ant-design/pro-table#640]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
pc下本应在右边的toolbar跑到了左边
![image](https://user-images.githubusercontent.com/38902744/87896102-d6186d00-ca79-11ea-95a1-bf21c64b4085.png)
手机模式下貌似位置也不太对
![image](https://user-images.githubusercontent.com/38902744/87896140-fa744980-ca79-11ea-9a0b-635ed42c9935.png)

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
2.4.2没有这个问题，升级到2.4.3出现的

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by kaoding** [comment]
在 headerTitle 不设置的情况会出现 toolbar 和 opation 在左边显示的情况.。

**Comment by gameruleCEO** [comment]
同样遇到，这个就应该可以自定义位置才对。

**Comment by chenshuai2144** [comment]
ref https://github.com/ant-design/pro-table/pull/651
