### ISSUE TITLE
🐛[BUG] request初始触发无法获取columns配置的initialValue

### ISSUE THREAD

**Issue by ziitar** [ant-design/pro-table#644]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

request初始请求无法获取columns配置的initialValue

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

columns中设置initialValue, 在request中console.log(params), 控制台只打印了{current: 1, pageSize: 20}。没有initialValue。

### 🏞 期望结果 [描述你原本期望看到的结果]

request包含initialValue值

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

https://codesandbox.io/s/jolly-williamson-g2m4h?file=/demo.tsx

### © 版本信息

- Ant Design Pro 版本: [2.4.3]
- umi 版本
- 浏览器环境[chrome]
- 开发环境 [windows]

**Comment by ziitar** [comment]
在<ProTable form={{initialValues: {} }}>配置的初始值有效
![image](https://user-images.githubusercontent.com/33385784/87928524-8e183b00-cab7-11ea-8c8a-148140496af1.png)
这里只取了form里配置的初始值

**Comment by chenshuai2144** [comment]
columns 的 initialValue 优先级很低，不会支持的。
