### ISSUE TITLE
🐛[BUG]使用toolbar快速搜索，第二次无效

### ISSUE THREAD

**Issue by hs185556** [ant-design/pro-table#645]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
使用toolbar快速搜索，第二次无效
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
在options中设置search, 在request中打断点, 只在第一次点击快速搜索有进断点。
### 🏞 期望结果 [描述你原本期望看到的结果]
toolbar快速搜索可以重复点击搜索。
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
```
     options={{
        search: {
          name: 'qixian',
        },
      }}
```
### © 版本信息
- Ant Design Pro 版本: [2.4.3]
- umi 版本
- 浏览器环境[chrome]
- 开发环境 [mac]

**Comment by nylqd** [comment]
mark，同样的问题

**Comment by hanguihe** [comment]
帅哥，提了pr，有空review下~ @chenshuai2144
