### ISSUE TITLE
🐛[BUG] 列表分页每页条数无效

### ISSUE THREAD

**Issue by gameruleCEO** [ant-design/pro-table#648]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
切换每页条数无效，默认只能是20，切换10，50，100均无效
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
![image](https://user-images.githubusercontent.com/32796170/88131871-933ccd80-cc10-11ea-823a-ba751eafd85e.png)
### 🏞 期望结果 [描述你原本期望看到的结果]
修复此bug啊
### © 版本信息
![image](https://user-images.githubusercontent.com/32796170/88131780-5c66b780-cc10-11ea-833e-1325fc760f25.png)

**Comment by jsdocker** [comment]
试试 antd 的4.2.0版本

**Comment by ll009366** [comment]
protable升到2.4.4
