### ISSUE TITLE
🐛[BUG] 状态栏，筛选状态为全部，不会展示所有数据，会清空表格

### ISSUE THREAD

**Issue by 172297555** [ant-design/pro-table#65]
![image](https://user-images.githubusercontent.com/40484787/71707648-1984f400-2e26-11ea-9536-c6b3ac8e7d78.png)
![image](https://user-images.githubusercontent.com/40484787/71707663-39b4b300-2e26-11ea-807a-96347c511e92.png)

**Comment by 172297555** [comment]
正在使用中.....急，谢谢大哥

**Comment by chenshuai2144** [comment]
全部是我们自己加的，我内置一下对 all 的支持。
