### ISSUE TITLE
🧐[问题] form 表单中 required 与 非require 红色星号 对齐 

### ISSUE THREAD

**Issue by mtianyan** [ant-design/pro-table#658]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

如下图所示， 我选择左对齐后，required 与 非require 无法对齐。

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
    {
      title: '备注',
      hideInSearch: true,
      dataIndex: 'remark',
      rules: [
        {
          required: false,
        },
      ],
    },

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/15145231/88371286-4ef32e00-cdc6-11ea-8a47-fb8a97c667bb.png)

**Comment by 521707** [comment]
没有这个属性哦 ，亲 rules
