### ISSUE TITLE
🧐[问题]pro-table对于日期类查询条件，是否支持范围查询

### ISSUE THREAD

**Issue by aaronlam** [ant-design/pro-table#66]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
由于业务需求，需要对表格内某一日期类型列的数据进行范围查询。找了很久没找到怎么用？所以想问下pro-table对于日期类查询条件，是否支持范围查询？

**Comment by H5futurehreohanshuo** [comment]
可以考虑使用 renderFormItem 方法自定义搜索项

**Comment by aaronlam** [comment]
> 可以考虑使用 renderFormItem 方法自定义搜索项

好的，谢谢！我去试一下。
不过我感觉对于日期类型的列值，按范围查询应该是挺常用的。

**Comment by liuwei0514** [comment]
valueType: 'dateRange',
但是这种方式创建时候的form item也是变成了dateRange  
搜索的form设置跟create update的form设置要区分开设置就好了

**Comment by liuwei0514** [comment]
{
        title: '开放日期',
        dataIndex: 'disparkTime',
        valueType: 'dateTime',
        // hideInForm: true,
        // hideInTable: true,
        hideInSearch: true,
      },
      {
        title: '开放日期',
        dataIndex: 'disparkTime',
        valueType: 'dateRange',
        hideInForm: true,
        hideInTable: true,
        // hideInSearch: true,
      },

变成两个column 一个用在 表格、创建form ，另外一个用在searchform
不知道有没有会不会有其他问题

**Comment by Amous-th** [comment]
这个问题又更优雅的方法吗，求教

**Comment by PeakFish** [comment]
可以多用一列来实现，一个 hideInSearch 用来展示数据， 一个  hideInTable 用来搜索。
