### ISSUE TITLE
🧐[问题]使用pro-table编译后的页面体积很大

### ISSUE THREAD

**Issue by Lnncoco** [ant-design/pro-table#661]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
![image](https://user-images.githubusercontent.com/57341815/88382640-7274a380-cddb-11ea-84e3-8bc6ad0b819b.png)
这是umi默认生成的v5项目,ListTableList页面占用300多K

自己写的项目每个引入的页面体积都在300~400  
![image](https://user-images.githubusercontent.com/57341815/88382768-bbc4f300-cddb-11ea-8a49-758f54bf76ad.png)

**Comment by WynterDing** [comment]
正在计划这部分的跟进: 

后续可以参考这个issue 的推进 https://github.com/ant-design/pro-components/issues/50
