### ISSUE TITLE
👑 [需求] search不仅支持span，是不是可以支持offset/pull/push等

### ISSUE THREAD

**Issue by qingfengmy** [ant-design/pro-table#663]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
search不仅支持span，是不是可以支持offset/pull/push等

只有一个搜索项的时候，会孤零零的在最左边，按钮在最右边。希望一个搜索项的时候可以跟按钮一起在右边。

**Comment by chenshuai2144** [comment]
> 只有一个搜索项的时候，会孤零零的在最左边，

只有一搜索项时就不应该显示，span 只是为了显示列
