### ISSUE TITLE
👑 [需求] form的时候，是否支持吧几个input 排成一排

### ISSUE THREAD

**Issue by Niofh** [ant-design/pro-table#665]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
**可以根据Row col 来布局，我可以设置2个input为一行，现在没有api可以配置**
![image](https://user-images.githubusercontent.com/15324717/88533176-6a656f80-d038-11ea-8159-cd26f1138a4c.png)

### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
可以改成这样的
![image](https://user-images.githubusercontent.com/15324717/88533477-f5466a00-d038-11ea-8eee-d3513b368ca5.png)

**Comment by chenshuai2144** [comment]
现在只能等分，你可以设置 search.span:2 来 二等分或者 只显示一行。

```
search={{
 span:2
}}
```
