### ISSUE TITLE
🐛[BUG]表头带合并列、合并行的 自定义显示列怎么控制，有没案例参考下

### ISSUE THREAD

**Issue by xiexingen** [ant-design/pro-table#669]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by WynterDing** [comment]
Protable 是 antd Table 的扩展，Table 的合并行、列 API 同样适用于 ProTable

参考: https://ant.design/components/table-cn/#components-table-demo-colspan-rowspan 即可

**Comment by xiexingen** [comment]
![image](https://user-images.githubusercontent.com/7939085/88668938-d8cc2f80-d115-11ea-8745-57fecfbddad5.png)
其实我是这个意思，表头存在合并列的情况 右侧那个控制列显示隐藏的控不到，可以用pro-table的一个在线例子试试
