### ISSUE TITLE
👑 [需求]能否支持将查询表单放在Modal中呢？

### ISSUE THREAD

**Issue by xiongs** [ant-design/pro-table#670]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
能否支持将查询表单放在Modal中呢？
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
实现这种效果
![image](https://user-images.githubusercontent.com/8221769/88611208-1fd90700-d0bb-11ea-8220-b484568e8eaa.png)

**Comment by WynterDing** [comment]
没有get 到点，是说查询部分在modal，table 主体在页面？

还是说 整个table 放在modal中使用？

后者是支持的，直接用就可以。前面这个需求比较奇怪，应该支持不了
