### ISSUE TITLE
官网例子搜索无效问题

### ISSUE THREAD

**Issue by sunluby** [ant-design/pro-table#672]
官网例子中的第二例子:toolbar 搜索, 在官网上搜索内容是有效的, 
`request={(params = {}) =>
        Promise.resolve({
          data: tableListDataSource.filter((item) => {
            if (!params.keyWord) {
              return true;
            }
            return item.name.includes(params.keyWord) || item.status.includes(params.keyWord);
          }),
          success: true,
        })
      }
      options={{
        search: {
          name: 'keyWord',
        },
      }}`
但拷贝到项目中发现只能搜索第一次,第二次就无效了. 不知道是什么原因...下面是我项目中的代码
 useEffect(() => {
    if (dispatch) {
      dispatch({type: 'student/queryStudents'});
    }}, []);

  const columns: ProColumns<TableListItem>[] = [
    {
      title: '姓名',
      key: 'name',
      dataIndex: 'name',
    },
......
  ];

  return (
      <ProTable<TableListItem, { keyWord?: string }>
        loading={loading}
        columns={columns}
        request={(params = {}) =>
          Promise.resolve({
            data: dataSource.filter((item) => {
              if (!params.keyWord) {
                return true;
              }
              return item.name.includes(params.keyWord);
            }),
            success: true,
          })
        }
        options={{
          search: {
            name: 'keyWord',
          },
        }}
        rowKey="key"
        size="middle"
        search={false}
        pagination={{
          showSizeChanger: true, showQuickJumper: true
        }}
      />
)

**Comment by chenshuai2144** [comment]
不要在这里发 issue
