### ISSUE TITLE
🐛[BUG] Typescript and export type {...}

### ISSUE THREAD

**Issue by Ovederax** [ant-design/pro-table#682]
When i use npm i in my react-typescript project i see error:  
TypeScript error in .../node_modules/@ant-design/pro-table/lib/index.d.ts(9,1):  
Declaration or statement expected.  TS1128  
export type { ProTableProps, IntlType, ColumnsState, ProColumnsValueType, ProColumns, ActionType, RequestData, };  

So, i think u can delete 'type' from export in 'src/index.tsx' on line 24 to fix that problem?

**Comment by VingoChen** [comment]
@Ovederax  I have the same problem , how to save it now?

**Comment by Ovederax** [comment]
@VingoChen i just used a new version of typescript in my project.  
I think the support for _import/export type_ contains TS 3.8 or newer
