### ISSUE TITLE
🧐[问题]type="form"时如何给指定dataIndex设置为必填或者选填项？

### ISSUE THREAD

**Issue by 521707** [ant-design/pro-table#693]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
type="form"时如何给指定dataIndex设置为必填或者选填项？ （主要问题）
在显示多个输入框的时候，如何设置指定的输入框为必选项。
在form组件中都是写在item上， table时 type = form 的时候，没有item可操作位置呢。

如何修改提交按钮的文字，或者增加按钮？ （次要）

**Comment by gzelda** [comment]
rules 标签没了，你是怎么实现的？
