### ISSUE TITLE
在columns中用renderFormItem自定义搜索输入框，如何在点击搜索后把值传到request里面🧐[问题]

### ISSUE THREAD

**Issue by Jidahan** [ant-design/pro-table#71]
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

{
      title: '问题搜索',
      dataIndex: 'searchName',
      hideInTable: true,
      renderFormItem: (item, props:{value,onChange}) => {
        return (
          <Input placeholder="编号/姓名/问题描述" />
        )
      },
    },

**Comment by Jidahan** [comment]
title: '问题搜索',
      dataIndex: 'searchName',
      hideInTable: true,
      renderFormItem: (item, props:{value,onChange}) => {
        return (
          <Input placeholder="编号/姓名" />
        )
      },
    },

**Comment by Jidahan** [comment]
return里面显示不出来 我重发下    <Input placeholder="请输入编号/姓名/问题" />

**Comment by chenshuai2144** [comment]
```
   renderFormItem: (item, props)=> {
        return (
          <Input placeholder="编号/姓名/问题描述"{....props} />
        )
      },
```
