### ISSUE TITLE
👑 [需求] when column sort server side render can trigger request 

### ISSUE THREAD

**Issue by aniude** [ant-design/pro-table#73]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
列排序时需要用服务器排序，点击列排序时好像没有办法触发到 request 事件，如果再引入fech 加 dataSource 的逻辑感觉有点冗余（或者又更好的办法我不知道）

**Comment by erguotou520** [comment]
请问如何解决获取排序问题的？
