### ISSUE TITLE
如何配置table上面的formItem的label,并不想用table里的title

### ISSUE THREAD

**Issue by bai3** [ant-design/pro-table#74]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
如何配置table上面的formItem的label,并不想用table里的title

### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
column加个配置项

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
还有就是怎么搜索使用RangePicker，目前好像不支持

**Comment by bai3** [comment]
已解决

**Comment by xclw2000** [comment]
> 已解决

怎么解决的，也不分享一下

**Comment by chenshuai2144** [comment]
@xclw2000 应该是直接用 lable 覆盖了 table 里面的
