### ISSUE TITLE
🐛[BUG]pro-table例子样式不统一

### ISSUE THREAD

**Issue by birdycn** [ant-design/pro-table#80]
如：https://jmshh.csb.app/

每个表格都存在ant-table-row-cell-break-word

<td class="ant-table-row-cell-break-word"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">2020-01-14 18:40:57</font></font></td>

自己的项目实际应用中：<td class=""></td>

这是为啥呢

**Comment by chenshuai2144** [comment]
估计是 antd 4 和 3 的不同，我来检查一下

**Comment by birdycn** [comment]
@chenshuai2144 
看了一下好像不是这个问题

比如
    {
      title: '操作',
      key: 'option',
      valueType: 'option',
      render: () => [<a>操作</a>, <a>删除</a>],
    },

我的解析：
<td class=""><div class="ant-pro-table-option-cell"><div class="ant-pro-table-option-cell-item"><a>操作</a></div><div class="ant-pro-table-option-cell-item"><a>删除</a></div></div></td>

例子解析：
<td class=""><div class="ant-pro-table-option-cell"><div class="ant-pro-table-option-cell-item"><a><font style="/* vertical-align: inherit; */"><font style="/* vertical-align: inherit; */">操作</font></font></a></div><div class="ant-pro-table-option-cell-item"><a><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">删除</font></font></a></div></div></td>

**Comment by chenshuai2144** [comment]
fixed
