### ISSUE TITLE
🐛[BUG] 表格设置行合并报错

### ISSUE THREAD

**Issue by hanguihe** [ant-design/pro-table#81]
### 🐛 bug 描述
基础Table组件里可以设置render返回`{children:xx, props: { rowSpan: 1 }}`设置行合并，但是在pro-table同样的设置报错`Objects are not valid as a React child`

### 📷 复现步骤 
在columns的render中返回`{children: "xx", props: { rowSpan: 1 }}`

### 🏞 期望结果
表格正确的合并行

### 💻 复现代码
https://ant.design/components/table-cn/#components-table-demo-colspan-rowspan
```
const columns = [
   {
      dataIndex: 'test',
      title: 'test',
      render: text => ({ children: text, props: { rowSpan: 1 } })
    },
]
```

**Comment by hanwensheng666** [comment]
问题解决了吗，同问题求助

**Comment by hanguihe** [comment]
<img width="668" alt="截屏2020-03-24下午4 19 07" src="https://user-images.githubusercontent.com/29910482/77403604-65bf4f00-6deb-11ea-94d6-a4b42abda105.png">
源码里有看到，我直接关闭了吧，感谢大佬们！
