### ISSUE TITLE
自定义search组件后，通过onchange方法异步加载，接口请求成功，如何把数据渲染到表格🧐[问题]

### ISSUE THREAD

**Issue by Jidahan** [ant-design/pro-table#82]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
自定义search组件后，通过onchange方法异步加载数据，接口请求成功，如何把数据渲染到表格内。
也就是说在选择后，执行onchange方法请求数据，渲染数据

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

--自定义search头
{
      title: '',
      dataIndex: 'radioMe',
      hideInTable: true,
      renderFormItem: (item, props:{value: any, onChange: any}) => (
          <Radio.Group defaultValue="全部问题" name="radiogroup"
            onChange={async e => {
              if (e.target.value === '全部问题') {
                await handleGet(e.target.value);
              } else {
                await handleGet(sessionStorage.getItem("USERID"));
              }
            }}
            // {...props}
          >
            <Radio value="全部问题">全部问题</Radio>
            <Radio value="关联我的">关联我的</Radio>
          </Radio.Group>
        ),
    },

---onChange方法
const handleGet = async (fields: any) => {
  const hide = message.loading('正在加载');
 try {
    await getTableData({
      current: 1,
      pageSize: 10,
      cteatedBy_id: fields,
   });
    hide();
    message.success('加载成功');
    return true;
  } catch (error) {
    hide();
    message.error('加载失败，请重试！');
    return false;
  }
};

**Comment by chenshuai2144** [comment]
这个有点复杂，现在支持不了了
