### ISSUE TITLE
🧐[问题] 使用Antd 3版本时，出现Warning

### ISSUE THREAD

**Issue by blueandhack** [ant-design/pro-table#83]
### 🧐 问题描述
介于Antd 4.0还在RC阶段还未正式发布，目前项目还在用3+
浏览器Console出现警告

### 💻 示例代码 
比如把Antd降级为3+后，pro-table升级至最新
```
    "@ant-design/pro-table": "1.0.31",
    "antd": "3.25.2",
```
https://codesandbox.io/s/pro-table-4wp53

### 🚑 其他信息
<img width="1053" alt="Snipaste_2020-01-17_23-09-21" src="https://user-images.githubusercontent.com/4150885/72660156-6ae0c780-397e-11ea-8ad2-fd8879238b2f.png">

**Comment by chenshuai2144** [comment]
因为我们使用了兼容包的原因，可以支持在 3 和 4 中一起使用

**Comment by blueandhack** [comment]
所以只是Warning，不影响使用？我看这条Warning用来`console.error()`来输出的，所以担心是否有严重的兼容问题。

**Comment by wulucxy** [comment]
目前使用下来对 icon 引入好像有冲突，使用 antd 原生 Table 没问题
