### ISSUE TITLE
👑 [需求]如何通过代码触发查询

### ISSUE THREAD

**Issue by xclw2000** [ant-design/pro-table#84]
拿到formRef后，想通过代码设置form中的字段，然后触发查询
`
  const filterBatchNo = batchNo => {
    formRef.current.resetFields();
    formRef.current.setFieldsValue({ BATCH_NO: batchNo });
    actionRef.current.reload();
  };`

发现新的查询条件并没有生效，传到后台的查询条件还是上一次点击”查询“后条件。能不能把formSearch的submit方法暴露出来,或者reload方法能不能获取一次新的查询条件

**Comment by chenshuai2144** [comment]
可以通过 formRef来获得。

**Comment by xclw2000** [comment]
> 可以通过 formRef来获得。

formRef只能获得我现在要应用的查询条件，问题获得之后怎么传给reload方法呢？reload不知道这些条件发生变化了呀。

**Comment by chenshuai2144** [comment]
@xclw2000 赋值给 params 就好了。

**Comment by chenshuai2144** [comment]
@xclw2000  你使用的是 2.0 版本还是1.x ?

**Comment by xclw2000** [comment]
> @xclw2000 你使用的是 2.0 版本还是1.x ?

2.0.1

**Comment by chenshuai2144** [comment]
@xclw2000 我将发布一个新的版本
