### ISSUE TITLE
🐛[BUG] 在antd4.0中，使用pro-table有警告，不知道是否影响功能

### ISSUE THREAD

**Issue by sussertod891015** [ant-design/pro-table#87]
### 🐛 bug 描述 
在umi ui可视化工具中，选择【模板】->【表哥】->【添加到项目】。下载完成后，跳转到该页面出现如下警告，不知道是否会影响功能使用，是否有计划全部兼容到antd4.0？

### 📷 
在umi ui可视化工具中，选择【模板】->【表哥】->【添加到项目】

### 🏞 
无警告，完全兼容antd4.0

### 💻 
在umi ui可视化工具中，选择【模板】->【表哥】->【添加到项目】

### © 版本信息

- @ant-design/pro-layout  [4.11.0-0]
- @ant-design/pro-table [^1.0.33]
- @ant-design/pro-cli [^1.0.14]
- antd [^4.0.0-rc.0]
- umi 版本 [^2.8.7]
- 浏览器环境 [chrome 79.0.3945.117]
- 开发环境 [mac OS]

### 🚑 
![image](https://user-images.githubusercontent.com/10465307/72704654-5ece5300-3b94-11ea-9c66-a466e29dfb45.png)

index.js:1 Warning: [antd-compatible: Icon] The legacy component has been deprecated, and ant design 4.0 now released! Please follow https://ant.design/components/icon to upgrade.
console.<computed> @ index.js:1
warning @ warning.js:6
call @ warning.js:20
warningOnce @ warning.js:25
(anonymous) @ warning.js:3
(anonymous) @ upgradeMessage.js:3
Icon @ index.js:28
renderWithHooks @ react-dom.development.js:16260
mountIndeterminateComponent @ react-dom.development.js:18794
beginWork$1 @ react-dom.development.js:20162
beginWork$$1 @ react-dom.development.js:25756
performUnitOfWork @ react-dom.development.js:24698
workLoopSync @ react-dom.development.js:24671
performSyncWorkOnRoot @ react-dom.development.js:24270
(anonymous) @ react-dom.development.js:12199
unstable_runWithPriority @ scheduler.development.js:697
runWithPriority$2 @ react-dom.development.js:12149
flushSyncCallbackQueueImpl @ react-dom.development.js:12194
flushSyncCallbackQueue @ react-dom.development.js:12182
scheduleUpdateOnFiber @ react-dom.development.js:23709
dispatchAction @ react-dom.development.js:17076
(anonymous) @ index.js:35
requestAnimationFrame (async)
(anonymous) @ index.js:34
commitHookEffectList @ react-dom.development.js:22030
commitPassiveHookEffects @ react-dom.development.js:22064
callCallback @ react-dom.development.js:336
invokeGuardedCallbackDev @ react-dom.development.js:385
invokeGuardedCallback @ react-dom.development.js:440
flushPassiveEffectsImpl @ react-dom.development.js:25392
unstable_runWithPriority @ scheduler.development.js:697
runWithPriority$2 @ react-dom.development.js:12149
flushPassiveEffects @ react-dom.development.js:25361
performSyncWorkOnRoot @ react-dom.development.js:24251
(anonymous) @ react-dom.development.js:12199
unstable_runWithPriority @ scheduler.development.js:697
runWithPriority$2 @ react-dom.development.js:12149
flushSyncCallbackQueueImpl @ react-dom.development.js:12194
flushSyncCallbackQueue @ react-dom.development.js:12182
scheduleUpdateOnFiber @ react-dom.development.js:23709
enqueueSetState @ react-dom.development.js:13994
umi../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:325
(anonymous) @ index.esm.js:90
Promise.then (async)
load @ index.esm.js:86
DynamicComponent @ index.esm.js:66
constructClassInstance @ react-dom.development.js:14204
updateClassComponent @ react-dom.development.js:18413
beginWork$1 @ react-dom.development.js:20186
beginWork$$1 @ react-dom.development.js:25756
performUnitOfWork @ react-dom.development.js:24698
workLoopSync @ react-dom.development.js:24671
performSyncWorkOnRoot @ react-dom.development.js:24270
scheduleUpdateOnFiber @ react-dom.development.js:23698
updateContainer @ react-dom.development.js:27103
(anonymous) @ react-dom.development.js:27528
unbatchedUpdates @ react-dom.development.js:24433
legacyRenderSubtreeIntoContainer @ react-dom.development.js:27527
render @ react-dom.development.js:27608
_callee$ @ umi.js:65
tryCatch @ runtime.js:45
invoke @ runtime.js:271
prototype.<computed> @ runtime.js:97
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
clientRender @ umi.js:32
(anonymous) @ runtimePlugin.js:89
(anonymous) @ umi.js:80
Promise.then (async)
./src/pages/.umi/umi.js @ umi.js:78
__webpack_require__ @ bootstrap:774
fn @ bootstrap:129
0 @ utils.js:55
__webpack_require__ @ bootstrap:774
(anonymous) @ bootstrap:953
(anonymous) @ bootstrap:953
index.js:1 Warning: [antd-compatible: Form] The legacy component has been deprecated, and ant design 4.0 now released! Please follow https://ant.design/components/form to upgrade.
console.<computed> @ index.js:1
warning @ warning.js:6
call @ warning.js:20
warningOnce @ warning.js:25
(anonymous) @ warning.js:3
(anonymous) @ upgradeMessage.js:3
Form @ Form.js:70
constructClassInstance @ react-dom.development.js:14204
updateClassComponent @ react-dom.development.js:18413
beginWork$1 @ react-dom.development.js:20186
beginWork$$1 @ react-dom.development.js:25756
performUnitOfWork @ react-dom.development.js:24698
workLoopSync @ react-dom.development.js:24671
performSyncWorkOnRoot @ react-dom.development.js:24270
(anonymous) @ react-dom.development.js:12199
unstable_runWithPriority @ scheduler.development.js:697
runWithPriority$2 @ react-dom.development.js:12149
flushSyncCallbackQueueImpl @ react-dom.development.js:12194
flushSyncCallbackQueue @ react-dom.development.js:12182
flushPassiveEffectsImpl @ react-dom.development.js:25420
unstable_runWithPriority @ scheduler.development.js:697
runWithPriority$2 @ react-dom.development.js:12149
flushPassiveEffects @ react-dom.development.js:25361
(anonymous) @ react-dom.development.js:25240
workLoop @ scheduler.development.js:641
flushWork @ scheduler.development.js:596
performWorkUntilDeadline @ scheduler.development.js:203
index.js:1 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `Trigger`.
    in DensityIcon (created by Trigger)
    in Trigger (created by ForwardRef(Tooltip))
    in ForwardRef(Tooltip) (created by Context.Consumer)
    in Tooltip (created by ToolBar)
    in span (created by ToolBar)
    in div (created by ToolBar)
    in div (created by ToolBar)
    in ToolBar (created by Context.Consumer)
    in WarpToolBar (created by ProTable)
    in div (created by Context.Consumer)
    in div (created by Context.Consumer)
    in Card (created by ProTable)
    in div (created by ProTable)
    in LocaleProvider (created by Context.Consumer)
    in SizeContextProvider (created by Context.Consumer)
    in LocaleReceiver (created by ConfigProvider)
    in ConfigProvider (created by ProTable)
    in ProTable (created by Context.Consumer)
    in Provider (created by ProviderWarp)
    in ProviderWarp (created by TableList)
    in div (created by PageHeaderWrapper)
    in div (created by GridContent)
    in GridContent (created by PageHeaderWrapper)
    in div (created by PageHeaderWrapper)
    in PageHeaderWrapper (created by TableList)
    in TableList (created by Form(TableList))
    in Form(TableList) (created by DynamicComponent)
    in DynamicComponent (created by Context.Consumer)
    in Route (created by RouteWithProps)
    in RouteWithProps (created by Context.Consumer)
    in Switch (created by Context.Consumer)
    in Authorized (created by BasicLayout)
    in div (created by WrapContent)
    in LocaleProvider (created by Context.Consumer)
    in SizeContextProvider (created by Context.Consumer)
    in LocaleReceiver (created by ConfigProvider)
    in ConfigProvider (created by ResizeObserver)
    in ResizeObserver (created by WrapContent)
    in main (created by Basic)
    in Basic (created by Context.Consumer)
    in Adapter (created by WrapContent)
    in WrapContent (created by BasicLayout)
    in section (created by Context.Consumer)
    in BasicLayout (created by Context.Consumer)
    in Adapter (created by BasicLayout)
    in section (created by Context.Consumer)
    in BasicLayout (created by Context.Consumer)
    in Adapter (created by BasicLayout)
    in div (created by BasicLayout)
    in Provider (created by BasicLayout)
    in BasicLayout (created by BasicLayout)
    in BasicLayout (created by ConnectFunction)
    in ConnectFunction (created by DynamicComponent)
    in DynamicComponent (created by Context.Consumer)
    in Route (created by RouteWithProps)
    in RouteWithProps (created by RouterWrapper)
    in Switch (created by RouterWrapper)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Context.Consumer)
    in ConnectedRouterWithContext (created by ConnectFunction)
    in ConnectFunction (created by RouterWrapper)
    in sfc (created by LocaleWrapper)
    in IntlProvider (created by LocaleWrapper)
    in LocaleProvider (created by Context.Consumer)
    in SizeContextProvider (created by Context.Consumer)
    in LocaleReceiver (created by ConfigProvider)
    in ConfigProvider (created by LocaleWrapper)
    in LocaleWrapper (created by RouterWrapper)
    in RouterWrapper
    in Provider (created by _DvaContainer)

**Comment by chenshuai2144** [comment]
不影响的，是 warning ，
我们会发布一个基于 antd@4 的版本来解决这个 warning

**Comment by HappyManYun** [comment]
protable 2.2.8 此警告仍存在

**Comment by sussertod891015** [comment]
对的，昨天更新了antd 4.2.4，pro-table 2.2.8，然后这个警告又出现了，之前antd 4.2.0，pro-table2.1.1是没有问题的
