### ISSUE TITLE
🧐[问题]列的显示顺序如何调整?

### ISSUE THREAD

**Issue by xclw2000** [ant-design/pro-table#88]
我的列有两列是固定的(如A,B)，还有一些列是动态的(C到Z)中的任意多个，最终显示的时候把固定的列和动态的列合并在一起显示，动态列是从服务端获取的，现在发现显示顺序不对，并且不知道怎么调整这个顺序。
例如：获取动态列是C, E , F, 我想显示的顺序是 A, C, E, F, B, 但是现在的显示顺序是C, E, F, A, B. 也就说固定的列永远显示在最后，动态列永远显示在前面。我期望的是把动态的列放在A和B中间。
另外，你们为什么不直接按我传的columns中的顺序显示列呢？

**Comment by chenshuai2144** [comment]
来个重现？
我们现在就是 按照传入数据的顺序的

**Comment by wulucxy** [comment]
sortKeyColumns 存在明显bug。

我本地列的顺序是这样的：

```
[
      { dataIndex: 'id', title: '应用 ID', hideInSearch: true, width: 80 },
      { dataIndex: 'code', title: '应用编码', width: 120 },
      { dataIndex: 'name', title: '应用名称', width: 200 },
      { dataIndex: 'updated_time', title: '更新时间', width: 200, render: formatDate, hideInSearch: true, },
      { dataIndex: 'creator', title: '创建人', hideInSearch: true, width: 80 },
      {
        title: '操作',
        key: 'action',
        width: 120,
        render: (text, record) => {
          return (
            <span className="m-action-group">
              <a onClick={() => editRecord(record)}>编辑</a>
            </span>
          )
        },
      },
    ],
```

通过`sortColumnsKeys` 之后操作列被排序到第二位，实际我的期望是跟原始值保持一致。

通过 `debug` 发现有一段神奇的逻辑：

```
useDeepCompareEffect(function () {
    var keys = counter.sortKeyColumns.join('-');
    var tableColumn = genColumnList(propsColumns, counter.columnsMap);

    if (keys.length > 0) {
      tableColumn = tableColumn.sort(function (a, b) {
        var aKey = "".concat(a.key || '', "-").concat(a.dataIndex || '');
        var bKey = "".concat(b.key || '', "-").concat(b.dataIndex || '');

        return keys.indexOf(aKey) - keys.indexOf(bKey);
      });
    }

    if (tableColumn && tableColumn.length > 0) {
      counter.setColumns(tableColumn);

      if (keys.length < 1) {
        counter.setSortKeyColumns(tableColumn.map(function (item, index) {
          return genColumnKey(item.key, item.dataIndex) || "".concat(index);
        }));
      }
```

这里如果有一列没传 dataIndex（比如我这里的操作列），就会出问题了

我的疑问是：

1. 为什么这里要手动加这段 sort 逻辑？
2. 如果要加，是否强制都要加 dataIndex 索引？
3. 类似的操作列应该添加什么索引值？

@chenshuai2144

**Comment by chenshuai2144** [comment]
这个是为了
![image](https://user-images.githubusercontent.com/8186664/73432969-cba8d080-437e-11ea-9b6a-9c0a9801f152.png)
的拖动排序，他不会更改顺序的，你是默认有一个，然后又修改成另外一个了？

**Comment by wulucxy** [comment]
@chenshuai2144 最后一列（我的是操作列）如果不加 dataIndex 属性就会导致顺序错误

**Comment by chenshuai2144** [comment]
那应该是个bug了，我应该根据name生成一下

**Comment by chenshuai2144** [comment]
@wulucxy  非常感谢，已经重现了

**Comment by xclw2000** [comment]
升级到最新版本，列的顺序是对了，但是又报这个warning
![image](https://user-images.githubusercontent.com/32091566/73605329-ea55d400-45d7-11ea-84a7-7a94445e68ae.png)

**Comment by zlyyyy** [comment]
我也遇到这个问题了。。升级到最新的也是报这个错。。 @chenshuai2144

**Comment by johnnylc** [comment]
同样的报错 mark

**Comment by Gzbox** [comment]
我也遇到这个问题了。。升级到最新的也是报这个错。。 @chenshuai2144

**Comment by Gzbox** [comment]
升级到最新版本V2.1.6，报这个warning @chenshuai2144 

Warning: The final argument passed to useEffect changed size between renders. The order and size of this array must remain constant.

Previous: [[object Object], [object Object], [object Object], [object Object], [object Object]]
Incoming: [[object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object]]
in ProTable (created by Context.Consumer)

![](https://user-images.githubusercontent.com/32091566/73605329-ea55d400-45d7-11ea-84a7-7a94445e68ae.png)

**Comment by liuwei0514** [comment]
传入的columns 不能变 ，变了之后就会报上面的错
