### ISSUE TITLE
sorting not working

### ISSUE THREAD

**Issue by AKedar21** [ant-design/pro-table#9]
sorting not working if i am adding sorter property on column in ProColumns[]

**Comment by aliceYouBob** [comment]
it is working in pro-table；for example the type of clumn is number,the code is 
**sorter: (a,b)=>a.callNo-b.callNo**

**Comment by AKedar21** [comment]
> it is working in pro-table；for example the type of clumn is number,the code is
> **sorter: (a,b)=>a.callNo-b.callNo**

@aliceYouBob Thanks it is working after implementing this.
But if I pass true/false it will not work there which I was passing before.
There needs to be some documentation for this sorter function of the Pro Column.
