### ISSUE TITLE
🐛[BUG]ellipsis省略表现错误

### ISSUE THREAD

**Issue by myonlylonely** [ant-design/pro-table#96]
### 🐛 bug 描述
column的ellipsis没有正常表现，总是显示全部内容在一行里。

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
复现代码：
https://codesandbox.io/s/father-doc-demo-610vx?fontsize=14&hidenavigation=1&theme=dark
![image](https://user-images.githubusercontent.com/8188177/73282825-2c27f880-422d-11ea-9b0a-3489c64913c2.png)

### 🏞 期望结果 [描述你原本期望看到的结果]
Ant Design原始的Table能够正常表现省略，如下图：
![image](https://user-images.githubusercontent.com/8188177/73282778-19adbf00-422d-11ea-9dd8-e8fba0dcbacf.png)

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://codesandbox.io/s/father-doc-demo-610vx?fontsize=14&hidenavigation=1&theme=dark

### © 版本信息

- Ant Design Pro 版本: 4
- umi 版本
- 浏览器环境 Chrome
- 开发环境 MacOS

**Comment by chenshuai2144** [comment]
需要设置宽度，不然无法获取到真实宽度
