### ISSUE TITLE
👑 [需求] 希望能添加日期和数值的范围搜索功能

### ISSUE THREAD

**Issue by RoscoeZhao** [ant-design/pro-table#97]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
开发时候发现多个表单的多个column，主要包括金额和日期/时间相关的column，时常需要用到范围搜索。希望能添加日期和数值的范围搜索功能。

### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
目前可以每个都用renderFormItem重做成对应的范围搜索。不过还是希望能整合到pro-table里。
或许可以在column里添加一个属性用来选择是否开启范围搜索？

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
非常感谢您的帮助。

**Comment by chenshuai2144** [comment]
有点不好生成。

valueType： dateRange
render：_________
fromItem: ________

帮忙填空一下？

**Comment by wangxingkang** [comment]
这个需求确实很常见

**Comment by dazyzsy** [comment]
数值的范围搜索功能 似乎还是缺少的
