### ISSUE TITLE
🐛[BUG] Antd 3.26.7版本项目使用Pro-table 2.0版本时导致普通Form样式变化，Table的Width变窄

### ISSUE THREAD

**Issue by blueandhack** [ant-design/pro-table#98]
### 🐛 bug 描述 
可能与Pro-table使用Antd 4.0有关

### 📷 复现步骤
Antd使用3.26.7，Pro-table使用2.0

### 🏞 期望结果
现在继续使用Pro-table 1.0+版本没有问题

### 💻 复现代码
Null

### © 版本信息

- Ant Design Pro 版本: 3.26.7
- 浏览器环境 
- 开发环境 macOS

### 🚑 其他信息 
Null

**Comment by chenshuai2144** [comment]
兼容一下样式把
